### ISSUE TITLE
still some warnings with -Wswitch-default

### ISSUE THREAD

**Issue by DenisExcoffier** [westes/flex#103]
Hello (again),

The following piece of code (see below) is ok under
flex (2.6.1 or 2.6.2) but still produces annoying warnings
when given to the -Wswitch-default option of gcc (i'm using gcc-6.2.0):

cm2.cc: In function 'int yylex()':
cm2.cc:814:15: warning: switch missing default case [-Wswitch-default]

cm2.cc: In function 'int yyinput()':
cm2.cc:1140:11: warning: switch missing default case [-Wswitch-default]

Addition of a simple 'default: break;' at various places inside the
flex code (2.6.1 or 2.6.2) corrects the problem.

%{
%}
%S INSIDE
%%
"beg of inside" { ECHO; BEGIN INSIDE; };
<INSIDE>"end of inside" { ECHO; BEGIN INITIAL; };
%%

**Comment by turboscholz** [comment]
Can confirm this error for example when compiling https://github.com/gcmd/gnome-commander/blob/ConvertWarningsToErrors/src/gnome-cmd-advrename-lexer.ll#L164 using flex-2.6.1.
