### ISSUE TITLE
discrepancy 1 within #line directives in some cases

### ISSUE THREAD

**Issue by DenisExcoffier** [westes/flex#104]
Hello,

Please consider cm41.lex and cm42.lex (see below). They are the
same, except for an additional line (namely a comment in this case) after
the first `%%`.

Run flex, compile and run (under some recent flex version).

./cm41 produces:
`cm41.lex 10`
while ./cm42 produces:
`cm42.lex 12`

Conclusion:
- cm41 is correct since the `printf()` is indeed located line 10 of cm41.lex
- cm42 is wrong since the `printf()` is indeed located line 11 of cm42.lex

Adding more (indented) lines immediately after the first `%%` does not
increase the mismatch. See also Debian bug #542482.

This is cm41.lex:
<code>%{</code>
<code>%}</code>
<code>%S INSIDE</code>
<code>%%</code>
<code>"&lt;inside>" { ECHO; BEGIN INSIDE; };</code>
<code>&lt;INSIDE>"&lt;/inside>" { ECHO; BEGIN INITIAL; };</code>
<code>%%</code>
<code>int yywrap() { return(1); };</code>
<code>int main() {</code>
<code>  printf("%s %d\n", __FILE__, __LINE__);</code>
<code>  //yylex();</code>
<code>};</code>

This is cm42.lex:
<code>%{</code>
<code>%}</code>
<code>%S INSIDE</code>
<code>%%</code>
<code>  /\* text */</code>
<code>"&lt;inside>" { ECHO; BEGIN INSIDE; };</code>
<code>&lt;INSIDE>"&lt;/inside>" { ECHO; BEGIN INITIAL; };</code>
<code>%%</code>
<code>int yywrap() { return(1); };</code>
<code>int main() {</code>
<code>  printf("%s %d\n", __FILE__, __LINE__);</code>
<code>  //yylex();</code>
<code>};</code>

**Comment by DenisExcoffier** [comment]
Not quite. This is true for flex-2.6.2 only. Under flex-2.6.1, the results are 11 and 12.

To sum up, with the two examples given:
- The correct results should be:&nbsp;&nbsp;&nbsp;10 and 11
- flex-2.6.1 provides:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;11 and 12
- flex-2.6.2 provides:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;10 and 12

**Comment by westes** [comment]
@DemiMarie could you have a look at this?

**Comment by westes** [comment]
I didn't have good luck building the test cases against master.

Could you have a look, especially given the tweek in #218?

**Comment by DenisExcoffier** [comment]
Please reopen. The tweek in #218 does improve the generated file but does nothing on this issue. I would see something more like the following, which does the job at least for cm41.lex and cm42.lex
(sorry, spaces lost at beginning of lines):

`diff -uNr flex-2.6.4o/src/scan.l flex-2.6.4p/src/scan.l`
`--- flex-2.6.4o/src/scan.l	2017-05-03 22:16:10.000000000 +0200`
`+++ flex-2.6.4p/src/scan.l	2018-05-10 20:29:29.000000000 +0200`
`@@ -103,7 +103,7 @@`
` `
` #define START_CODEBLOCK(x) do { \`
`     /* Emit the needed line directive... */\`
`-    if (indented_code == false) { \`
`+    if ((indented_code == false) && (sectnum != 2)) { \`
`         linenum++; \`
`         line_directive_out(NULL, 1); \`
`     } \`
