### ISSUE TITLE
libfl_pic.a contains the non-PIC objects

### ISSUE THREAD

**Issue by AdrianBunk** [westes/flex#105]
libfl_pic.a contains the same non-PIC object files as libfl.a, not the PIC object files (tested building flex 2.6.1 on Debian).

If this didn't cause build breakage anywhere, this kinda implies that noone actually needs libfl_pic.a

**Comment by Explorer09** [comment]
libfl is intended to be linked with flex-generated code, and is not strictly needed to build flex itself.
That's why I say (GitHub issue #99) they should allow disabling it.

**Comment by AdrianBunk** [comment]
I know what libfl is, and your suggestion is completely unrelated.

**Comment by westes** [comment]
Looking at src/Makefile.am, I see there's no flags to specify pic. which is not what I recall. Yes, it's an easy fix. I'm not sure that it's a widely used feature, but I do recall a debian patch that provided it, it's easy enough, so why not.

**Comment by AdrianBunk** [comment]
The last Debian release that carried this change was released in 2013:
https://sources.debian.net/src/flex/2.5.35-10.1/Makefile.am/

In the next Debian release the change had disappeared:
https://sources.debian.net/src/flex/2.5.39-8+deb8u2/Makefile.am/

This issue is actually originally a Debian bug:
https://bugs.debian.org/837658
PIE in the static library is sufficient for PIE binaries, but this uncovered in that case that libfl_pic.a was not PIC.
Debian has a libfl.so -> libfl_pic.a linker script hack, that's the only reason why programs attempt to link wth libfl_pic.a instead of libfl.a on Debian.
libfl_pic.a and libfl.a are identical in Debian (same checksum).

If I add the libfl_pic_a_CFLAGS change in src/Makefile.am of 2.6.1, I still get the non-PIC objects in libfl_pic.a

I am not sure whether this was ever working, and I do not see how this could have been working recently.

Do you have any easy fix where you have confirmed that you actually get PIC objects in libfl_pic.a?

**Comment by westes** [comment]
No, I don't have an easy fix and after looking over the libtool and automake documentation, I don't see how to make it work, so yes, I'll just drop the pic labeled stuff.

**Comment by westes** [comment]
I think I should just [do this](https://github.com/westes/flex/tree/nopic). Any reason not to? I just removed the pic labeled stuff.

**Comment by westes** [comment]
I just dropped the _pic variant. See master for details.

**Comment by Explorer09** [comment]
@westes @AdrianBunk
How do I reopen this issue? I believe I found a **workaround**, but I don't like to see this closed without an ideal fix.

From what I tested, it is possible to build PIC version of libfl via an explicit `--with-pic` option in `configure`, but that way, the non-PIC archive will then contain PIC code.
It seems that the build system currently in flex-2.6.2 just creates both libfl.a and libfl_pic.a from the same set of sources (libmain.o and libyywrap.o) with recompiling the '.o' files!

For now, can we just note in the documentation that if you want PIC code, then **try one of following method:**
(1) Specify `--with-pic` when invoking configure.
(2) Specify `--enable-shared` and `--enable-static`, then see both versions of object files built. But then you need to do `ar cru .libs/libfl_pic.a  .libs/libmain.o .libs/libyywrap.o && ranlib .libs/libfl_pic.a` manually.

**Comment by westes** [comment]
Thanks for the pointers. I'll make a note in the manual. I will also give the automake and libtool docs another pass to see what I can glean about making automake do this.

**Comment by AdrianBunk** [comment]
I do not think there is anything that should be documented:
When someone builds flex himself, the shared library is installed by default. At that point there is no reason why a user should want to use libfl_pic.a - just like with any other library, the user already has PIC and non-PIC versions installed side by side by default.

Section 4.2 "Building true and false" of the automake manual gives some suggestions, and something along these lines could likely be made working with libtool.

But then there is my original point:
Debian/Ubuntu have not been shipping any version of libfl containing PIC for years, and there is no indication that this has caused problems for anyone.
Did you ever get a bug report from someone who had a problem due to libfl_pic.a not containing PIC?
Noone seems to actually use libfl in shared libraries?

**Comment by Explorer09** [comment]
@AdrianBunk 
Shared library is different from PIC static library. Don't confuse the two.
PIC static library may be used when someone wishes to link a shared library code that includes flex code. But that case can be easily worked-around by just embedding libmain.c and libyywrap.c into their project (and sometimes that would produce a better-optimized code, by the way).

Yes, libfl_pic.a is not needed. But my point is that we would better document that **we are not preventing user to build PIC library at all**. (It's just under a different option: `--with-pic` provided by libtool.)

**Comment by AdrianBunk** [comment]
@Explorer09 
Can you give an example of an existing shared library that is actually requiring libfl?
Not a theoretical case, a shared library that is actually used.
My current understanding is that there is none.

And the proper solution for shared libraries would anyway be guaranteeing sufficient ABI stability of libfl.so, so that more Linux distributions would ship it. Is there any current or historic reason explaining why distributions do not want to ship libfl.so?

Documenting what someone compiling flex could do is pretty pointless, in the end your code has to work with with how flex is shipped by Linux distributions.

**Comment by westes** [comment]
> Documenting what someone compiling flex could do is pretty pointless, in the end your code has to work with with how flex is shipped by Linux distributions.

NOt true in the least.

The whole point of flex is that you use flex to make new things. Given that, a knowledgeable user will do whatever is necessary to make the code the way he'd like it to be.

Since flex used to provide a (unfortunately non-working) PIC version of libfl, it's worth documenting how to get one.

Ideally, I'd include both in the build targets of flex, but I don't see how to do that at the moment. So I'll document how to produce the apparently less frequent one.

**Comment by Explorer09** [comment]
I think there's no need to show an actual case (of a shared lib using libfl), because when I think of a future distro that builds everything with LTO, the PIC and non-PIC distinction will be no longer relevant.
It will be a distro's job to choose whether to ship PIC libfl, or non-PIC one, or libfl in IR for LTO toolchain.

By the way, I should mention the Bison project that could have the same problem as ours -- they have liby, but they don't use the similar liby_pic.a or something like that.

**Comment by AdrianBunk** [comment]
@westes 
There is nothing bad about documenting --with-pic, but it shouldn't be required for the people who could potentially need it.

A knowledgeable user who builds flex himself for including the static library into his shared library should already know such things (at least the more basic CFLAGS trick).

**Comment by westes** [comment]
> but it shouldn't be required for the people who could potentially need it.

It's not. The point of documenting things is to show how they can be done. If there are other ways to do things, that's great. The documentation will describe the existing libtool/configure interface because the prior automake-based method was incorrect and the existing libtool/configure method works without me having to change anything.

**Comment by westes** [comment]
This has been resolved by no longer distributing a pic-labeled version of the library.
