### ISSUE TITLE
Current git tree is impossible to build

### ISSUE THREAD

**Issue by asavah** [westes/flex#107]
If flex is not already present on the system it is currently impossible to build it from git.
Therefore "You need the following tools to build flex from the maintainer's repository:" in README.md is no longer valid.

automake 1.15/autoconf 2.69/libtool 2.4.6/bison 3.0.4
```
/bin/bash ../build-aux/ylwrap scan.l .c scan.c -- /bin/bash /opt/kross/src/flex/build-aux/missing flex
/home/asavah/kross/src/flex/build-aux/missing: line 81: flex: command not found
WARNING: 'flex' is missing on your system.
         You should only need it if you modified a '.l' file.
         You may want to install the Fast Lexical Analyzer package:
         <http://flex.sourceforge.net/>
Makefile:1355: recipe for target 'scan.c' failed
make[3]: *** [scan.c] Error 127
```
Release tarball already contains pregenerated scan.c .

**Comment by westes** [comment]
Yes, bootstrapping is a pain. You can grab the 2.6.2 archive and compile that. It doesn't need flex to build -- so long as you change nothing that would trigger needing flex.
