### ISSUE TITLE
Provide man page by default

### ISSUE THREAD

**Issue by selkfoster** [westes/flex#114]
Hello,

The new version of flex 2.6.2 requires help2man to generate the man page for flex.  This will be fail if you are doing a GNU/Linux from scratch, which is my case, because flex needs to be available early, and help2man depends on perl, and perl is available later. (See also "Linux From Scratch").

P.S: Thanks for provide flex in lzip format.

**Comment by Explorer09** [comment]
It's already fixed in master. Try this commit.
https://github.com/westes/flex/commit/92311a56b34363d150ed6badfad3450bcfe09a2f

This issue report is duplicate of #108

**Comment by selkfoster** [comment]
Ok, I'm closing this duplicate in order to try the commit for having flex 2.6.2.
