### ISSUE TITLE
Feature Request: Release package signing

### ISSUE THREAD

**Issue by g4jc** [westes/flex#117]
Hello,
There is currently no way to verify the complete integrity of releases. Please consider signing your releases so that package maintainers can verify the sources prior to packaging.

See here for how-to and complete details:
https://wiki.debian.org/Creating%20signed%20GitHub%20releases

Thank you

**Comment by westes** [comment]
Thanks for the link. It's officially on the list of things to get done sooner rather than later.

**Comment by vcunat** [comment]
The commits are signed, at least.

**Comment by westes** [comment]
It's a reasonable request and the linked documentation is helpful. It will happen.

On Saturday, 19 November 2016,  9:32 am -0800, Vladimír Čunát <notifications@github.com> wrote:

> The commits are signed, at least.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/117#issuecomment-261727415

-- 
Will Estes
westes575@gmail.com

**Comment by vcunat** [comment]
Yes, I didn't mean to imply something else.

**Comment by westes** [comment]
This is planned for 2.6.4. I will get 2.6.3 out the door so that some important breakage can be addressed, then I'll sort out how to do release signing going forward.

**Comment by westes** [comment]
Now that I've reviewed the linked document, it only describes a manual process for signing the auto-archives that github makes -- which is not what a flex release is. I'd like to simply create the signatures through "make dist". Surprisingly, there isn't anything coming up when I google for a rule/fragment/etc for doing this already. Which seems wrong since lots of other packages are signing their releases.

**Comment by vcunat** [comment]
Well, you've got tarballs locally, I guess, and creating the signatures for them is a simple command, e.g. the one that's in that document. Then you can upload it alongside the tarballs, at least, if github provides no direct support (I don't know that).

**Comment by westes** [comment]
I want to be able to run something like:

$ make distcheck
$ make distsign

And have all the files generated. I suppose that we're talking tar.{gz,lz}{,sha512sum}{,.sig}

Partly I'm just surprised that this isn't a canned solution already since it's a done thing for a lot of packages.

**Comment by vcunat** [comment]
You can easily add lines like.
```
gpg --output release.tar.xz.sig --detach-sig release.tar.xz
```
(Or better, more general rules for this, but that might be over-engineering at this point.) As people tend to protect their private keys by a passphrase at least, you can't avoid unlocking your keyring anyway, so it can't be "fully automatic".

**Comment by westes** [comment]
I've loked at this. Doing it manually is certainly pretty straightforward. PUtting a braindead wrapper -- where everything is hardcoded, e.g. -- is also straight forward.

What I need to do is to create a proper set of keys with subkeys as per the guide linked to above and push that out to key servers so folks can pick up the signing that way.

**Comment by westes** [comment]
Flex 2.6.4 is released and signed -- both the tag in git and the tar balls themselves.
