### ISSUE TITLE
yyleng should be typed as "yy_size_t", not "int"

### ISSUE THREAD

**Issue by Derek61** [westes/flex#118]
yyleng is treated throughout as a "size_t"-equivalent type; it is not correct to type it as an "int". This change was made sometime between 2.6.0 and 2.6.2, and it breaks existing code.

**Comment by westes** [comment]
No.

http://pubs.opengroup.org/onlinepubs/7908799/xcu/lex.html

The expectation that yyleng is int is longstanding.

To be sure, the flex code needs cleanup.

**Comment by Derek61** [comment]
No, this is counter the entire history of flex, and the gratuitous change breaks existing code. Who cares what lex did or does — which predates the correct usage of size_t in any case?

**Comment by Derek61** [comment]
This breaks so many things!

Dozens of messages like this:
scanner.l:248:39: error: non-constant-expression cannot be narrowed from type
      'int' to 'size_type' (aka 'unsigned long') in initializer list
      [-Wc++11-narrowing]
  yylval->value = std::string{yytext, yyleng};
                                      ^~~~~~
aux/scanner.cc:155:16: note: expanded from macro 'yyleng'

and this:
aux/scanner.cc:1951:3: error: implicit conversion loses integer precision:
      'size_t' (aka 'unsigned long') to 'int' [-Werror,-Wshorten-64-to-32]

Everyone caused by the fundamental  error of pretending that "int" is equivalent to "size_t", which hasn't been true since c89 — some 27 years.
