### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_yywrap"

### ISSUE THREAD

**Issue by Lelouch5023** [westes/flex#121]
When I typed "gcc lex.yy.c" on my mac terminal, I get this:
Undefined symbols for architecture x86_64:
  "_yywrap", referenced from:
      _yylex in ccSIYu86.o
      _input in ccSIYu86.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status

Is there something wrong with gcc? I tried Clang and Homebrew gcc v 6.2.0, and both got this result.

**Comment by westes** [comment]
No, you need to read the manual, though. Particularly the bits about linking against libfl or providing your own yylex function.
