### ISSUE TITLE
flex misses rule boundaries

### ISSUE THREAD

**Issue by fxdupont** [westes/flex#139]
In Kea the eval library uses in its flex input (a Kea copy is available on GitHub, I can give a pointer to the whole file) for its first 2 rules:

----- .ll code -----
{blank}+   {
    // Ok, we found a with space. Let's ignore it and update loc variable.
    loc.step();
}

[\n]+      {
    // Newline found. Let's update the location and continue.
    loc.lines(evalleng);
    loc.step();
}
----- end of .ll -----

flex 2.6.2 (but not 2.6.1 or any previous version) produces an incorrect code:
----- bad .cc -----
                switch ( yy_act )
        { /* beginning of action switch */
/* %% [13.0] actions go here */
case 1:
YY_RULE_SETUP
#line 83 "lexer.ll"
{
    // Ok, we found a with space. Let's ignore it and update loc variable.
    loc.step();
}

[\n]+      {
    // Newline found. Let's update the location and continue.
    loc.lines(evalleng);
    loc.step();
}
        YY_BREAK
case 2:
YY_RULE_SETUP
#line 94 "lexer.ll"
{
...
----- end of bad .cc -----

in place of:

----- good .cc -----
                switch ( yy_act )
        { /* beginning of action switch */
/* %% [13.0] actions go here */
case 1:
YY_RULE_SETUP
#line 82 "lexer.ll"
{
    // Ok, we found a with space. Let's ignore it and update loc variable.
    loc.step();
}
        YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 87 "lexer.ll"
{
    // Newline found. Let's update the location and continue.
    loc.lines(evalleng);
    loc.step();
}
        YY_BREAK
case 3:
YY_RULE_SETUP
#line 93 "lexer.ll"
{
...
----- end of good .cc -----

Note it seems to be bound to {{{//}}} C++ comments in actions (which flex is supposed to copy verbatim).
I can help you, just send a message to fdupont@isc.org

**Comment by HBBroeker** [comment]
That input file is broken independently of flex versions.  It lacks some crucial indendation in the action parts of its rules.  If that ever worked with any version of flex, it was by happenstance.

**Comment by fxdupont** [comment]
The issue was fixed in the last version of flex. Closing.
