### ISSUE TITLE
"Macro redefined" warnings with multiple_scanners_r (in testsuite)

### ISSUE THREAD

**Issue by Explorer09** [westes/flex#142]
```bash
$ ./autogen.sh && ./configure && make
$ cd tests && make multiple_scanners_r
```
I can get multiple "macro redefined" warnings from this:

```
gcc -DHAVE_CONFIG_H -I. -I../src  -I../src -I../src   -g -O2 -MT multiple_scanners_r_main.o -MD -MP -MF .deps/multiple_scanners_r_main.Tpo -c -o multiple_scanners_r_main.o multiple_scanners_r_main.c
In file included from multiple_scanners_r_main.c:25:0:
multiple_scanners_r_2.h:20:0: warning: "yy_create_buffer" redefined [enabled by default]
 
 ^
In file included from multiple_scanners_r_main.c:24:0:
multiple_scanners_r_1.h:20:0: note: this is the location of the previous definition
 
 ^
In file included from multiple_scanners_r_main.c:25:0:
multiple_scanners_r_2.h:22:0: warning: "yy_delete_buffer" redefined [enabled by default]
 
 ^
In file included from multiple_scanners_r_main.c:24:0:
multiple_scanners_r_1.h:22:0: note: this is the location of the previous definition
 
 ^
In file included from multiple_scanners_r_main.c:25:0:
multiple_scanners_r_2.h:24:0: warning: "yy_scan_buffer" redefined [enabled by default]
 
 ^
[...]
```

This seems to be a regression introduced in 347652c32b4614995acd4ee0d686499da2070d9e "fix backwards incompatible changes in 2.6.2."

**Comment by HBBroeker** [comment]
Unfortunately this concerns not just test cases.  It affects real-world projects.  GNU gdb fails to build from GIT source, because of it.

**Comment by Explorer09** [comment]
@HBBroeker I don't think gdb's breakage is *directly* caused by this testcase error.
See issue #162. If it's not the same issue, then you would better file another proper issue report.

**Comment by HBBroeker** [comment]
It's caused by the same root cause as the testcase warning: flex-2.63 exports #defines into its output that were never there before.

**Comment by GitMensch** [comment]
> Unfortunately this concerns not just test cases. It affects real-world projects. GNU gdb fails to build from GIT source, because of it.

This is a real big issue. Is it possible to move this to 2.6.4 milestone?

**Comment by westes** [comment]
Yes, with a pull request.

On Tuesday,  2 May 2017, 12:11 pm -0700, Simon Sobisch <notifications@github.com> wrote:

> > Unfortunately this concerns not just test cases. It affects real-world projects. GNU gdb fails to build from GIT source, because of it.
> 
> This is a real big issue. Is it possible to move this to 2.6.4 milestone?
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/142#issuecomment-298731922

-- 
Will Estes
westes575@gmail.com

**Comment by GitMensch** [comment]
Is it just possible to remove the defines for now? Did you identified the offending commits yet?

**Comment by DemiMarie** [comment]
Bug is as follows: Flex used to use an M4 macro for this, but I switched it to a C preprocessor macro to avoid it being expanded in string literals.  However, if multiple scanners are used, the macro is redefined, so we get this warning.

Patch coming.

**Comment by DemiMarie** [comment]
@GitMensch I am the one who caused these changes, so let me explain.

Flex has (for a very long time) used the M4 macro processor to process input files.  M4 expands macros *anywhere,* even in C string literals.  So the M4 macros that were there instead of the `#define`s had to go.

That broke backwards compatibility though.  So I had to add the `#define`s to restore it.

**Comment by westes** [comment]
For those of you watching this thread, There is a fix on master -- described there as partial. Please give feedback on how it effects your particular use case. Much thanks!

**Comment by Explorer09** [comment]
@DemiMarie While I appreciate your work on fixing this problem, could you please also add some relevant tests to flex's testsuite? I mean for example, a test of behavior you mention in this text:
>This is a partial solution. It can still break if the user expects the old behavior
> of the yy_* macros in user header files not affecting the yy_* identifiers in the
> user's Lex file.

And a test about "not expanding macro tokens in string literals" is also useful as well.
What I hope is this big issue will never happen again in future flex versions.

**Comment by westes** [comment]
The limited feedback says that this issue is resolved. While the described solution is partial, let's see how things do.
