### ISSUE TITLE
No INSTALL file in master

### ISSUE THREAD

**Issue by hkiang01** [westes/flex#15]

**Comment by westes** [comment]
Note the section in README that details how to build flex from the maintainer's repository. 
 The distribution build process installs a generic INSTALL file as per standard autoconf practice.

What problem are you experiencing?

**Comment by hkiang01** [comment]
The README is misleading in that it hints at the existence of a file called "INSTALL" in master. I see the installation instructions in the README itself and am following them. I'm in the middle of installing dependencies.
