### ISSUE TITLE
[PATCH: flex.skl] drop unnecessary cast of fprintf output

### ISSUE THREAD

**Issue by jannick0** [westes/flex#151]
This is to have `fprintf` statements undecorated by any preceeding `(void)`, consistently throughout `lex.yy.c`. I bumped into this when trying to redirect the stderr output to a string stream (held back until an error occurs). 

Separately, a related suggestion: `fprintf`statements could be governed by preprocessor directives like `YYFPRINTF` in bison.

Thanks,
J.

```diff
--- a/flex.skl	Mon Feb 29 14:53:04 2016
+++b/flex.skl	Thu Jan 05 14:15:34 2017
@@ -2556,7 +2556,7 @@
 {
 	M4_YY_DECL_GUTS_VAR();
 	M4_YY_NOOP_GUTS_VAR();
-	(void) fprintf( stderr, "%s\n", msg );
+	fprintf( stderr, "%s\n", msg );
 	exit( YY_EXIT_FAILURE );
 }
 %endif
```

**Comment by westes** [comment]
> Separately, a related suggestion: fprintfstatements could be governed by preprocessor directives like YYFPRINTF in bison.



Please open that as a separate issue.

**Comment by westes** [comment]
Patch on master and will be included in the next release.

**Comment by jannick0** [comment]
suggestion in separate issue #158
