### ISSUE TITLE
"yywrap" macro redefined when %option noyywrap given

### ISSUE THREAD

**Issue by nvinson** [westes/flex#155]
Description:
This is based on the error seen with Gentoo bug #604732 (https://bugs.gentoo.org/show_bug.cgi?id=604732).

Specifying the noyywrap option causes GCC to emit a warning about yywrap being redefined.  This does not happen if `%option noyywrap` is replaced with a correct yywrap() function definition.

Steps to reproduce:
Create input file:
```
%option noyywrap
%%
%%
```

Run flex input.l
gcc -c input.c
observe warning

The expected result is for no warning to be emitted.

**Comment by westes** [comment]
@DemiMarie do you have any thoughts on this? I assume this is the same issue as in #152 and #154.

**Comment by jannick0** [comment]
I think in the proposed case the macro `yywrap` is defined __twice__ in `input.c`:
```c
#define yywrap yywrap // since flex 2.6.2 or 2.6.3, NB: to be guarded if yywrap defined below, i.e. %option noyywrap
```
and further down
```c
#define yywrap() (/*CONSTCOND*/1)
```

**Comment by jannick0** [comment]
Why not simpy defining `yywrap` as a function instead of a macro (see main.c:1588++)?

Separately, it appears that in flex.skl:58 (see snip below) m4's `ifelse` statement always drops into the false branch, as by code interpretation this should no be the case if the prefix is not redefined.

```c
%not-for-header
%if-c-only
%if-not-reentrant
m4_ifelse(M4_YY_PREFIX,yy,,
#define yy_create_buffer M4_YY_PREFIX[[_create_buffer]]
[snip]
)
```

**Comment by jannick0** [comment]
A suggested patch to define `yywrap` as function instead of a macro I just tested for simple cases:

```diff
--- main.c	Thu Dec 29 21:03:14 2016
+++ main.c	Fri Jan 13 13:28:59 2017
@@ -1586,9 +1588,9 @@
 	if (!do_yywrap) {
 		if (!C_plus_plus) {
 			 if (reentrant)
-				outn ("\n#define yywrap(yyscanner) (/*CONSTCOND*/1)");
+				outn ("\nint yywrap(yyscanner) { return /*CONSTCOND*/1; }");
 			 else
-				outn ("\n#define yywrap() (/*CONSTCOND*/1)");
+				outn ("\nint yywrap(void) { return /*CONSTCOND*/1; }");
 		}
 		outn ("#define YY_SKIP_YYWRAP");
 	}
```

**Comment by westes** [comment]
Looks like the same issue as #162; please confirm that you see this fixed for you on master now.

**Comment by nvinson** [comment]
Fixed on master.  Thanks.
