### ISSUE TITLE
[PATCH] optional argument for switch '--stdout' for anonymized preprocessor #line statements with <stdout>

### ISSUE THREAD

**Issue by jannick0** [westes/flex#159]
flex 2.6.3: `flex -t ...` creates _anonymized_ preprocessor line statements for proper flex code lines since no output file name is known:
```c
# line 123 "<stdout>"
```

Suggestion: additional __optional__ argument to switch `-t` providing the output file name for cpp line statements. 

Example:
```cmd
flex -t test.c test.l | pipe_me.exe > test.c
```
where the pipe result `test.c` has cpp line statements referring to `test.c` (instead of `stdout`) and `test.l`.

**Comment by jannick0** [comment]
Here a proposed patch which allows an optional argument for `--stdout` only. To avoid ambiguous args parsing, `-t` must not have an optional argument.

```diff
--- main.c	Thu Dec 29 21:03:14 2016
+++ main.c	Fri Jan 13 12:26:42 2017
@@ -1131,6 +1131,10 @@
 		case OPT_NO_LINE:
 			gen_line_dirs = false;
 			break;
+
+        case OPT_STDOUT:
+			use_stdout = true;
+			/* fall through */
 
 		case OPT_OUTFILE:
 			outfilename = arg;
@@ -1173,10 +1177,6 @@
 			spprdflt = true;
 			break;
 
-		case OPT_STDOUT:
-			use_stdout = true;
-			break;
-
 		case OPT_NO_UNISTD_H:
 			//buf_strdefine (&userdef_buf, "YY_NO_UNISTD_H", "1");
             buf_m4_define( &m4defs_buf, "M4_YY_NO_UNISTD_H",0);
@@ -1813,7 +1813,8 @@
 		  "\n" "Files:\n"
 		  "  -o, --outfile=FILE      specify output filename\n"
 		  "  -S, --skel=FILE         specify skeleton file\n"
-		  "  -t, --stdout            write scanner on stdout instead of %s\n"
+		  "  -t, --stdout[=FILE]     write scanner on stdout instead of %s,\n"
+		  "                            with FILE used in #line directives instead of <stdout>\n"
 		  "      --yyclass=NAME      name of C++ class\n"
 		  "      --header-file=FILE   create a C header file in addition to the scanner\n"
 		  "      --tables-file[=FILE] write tables to FILE\n" "\n"
--- options.c	Fri Oct 21 01:43:44 2016
+++ options.c	Fri Jan 13 11:52:33 2017
@@ -187,7 +187,7 @@
 	,
 	{"-t", OPT_STDOUT, 0}
 	,
-	{"--stdout", OPT_STDOUT, 0}
+	{"--stdout[=FILE]", OPT_STDOUT, 0}
 	,			/* Write generated scanner to stdout. */
 	{"-T", OPT_TRACE, 0}
 	,
```

**Comment by Explorer09** [comment]
Read the manual. This extension is redundant. Try this instead:

    flex -t -o test.c test.l | pipe_me.exe > test.c

Manual says:

       -ooutput
	      directs  flex to write the scanner to the file out-
	      put instead of lex.yy.c.	If you	combine	 -o  with
	      the  -t option, then the scanner is written to std-
	      out but its #line directives  (see  the  -L  option
	      above) refer to the file output.

**Comment by jannick0** [comment]
Many thanks again! Agree. I just checked that it works as you quoted from the manual. ... then the suggestion is  obsolete, of course.
