### ISSUE TITLE
flex 2.6.3 breaks building wine

### ISSUE THREAD

**Issue by julliard** [westes/flex#160]
make[1]: Entering directory '/home/julliard/wine/wine/programs/winhlp32'
flex -omacro.lex.yy.c macro.lex.l
gcc -m32 -c -o macro.lex.yy.o macro.lex.yy.c -I. -I../../include -D__WINESRC__ -D_REENTRANT -fPIC -Wall -pipe \
  -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body -Wignored-qualifiers \
  -Wshift-overflow=2 -Wstrict-prototypes -Wtype-limits -Wunused-but-set-parameter -Wvla \
  -Wwrite-strings -Wpointer-arith -Wlogical-op -gdwarf-2 -gstrict-dwarf -fno-omit-frame-pointer \
  -Werror -g -O2 -fno-diagnostics-show-caret
../../tools/winegcc/winegcc -o winhlp32.exe.so -B../../tools/winebuild -m32 -fasynchronous-unwind-tables \
  -mwindows callback.o hlpfile.o macro.o string.o winhelp.o macro.lex.yy.o winhlp32.res -lshell32 \
  -lcomctl32 -lcomdlg32 -luser32 -lgdi32 ../../libs/port/libwine_port.a -Wb,-dshell32 -Wb,-dcomctl32 \
  -Wb,-dcomdlg32 
macro.lex.yy.o: In function `yylex':
/home/julliard/wine/wine/programs/winhlp32/macro.lex.yy.c:1032: undefined reference to `yywrap'
collect2: error: ld returned 1 exit status
winegcc: gcc failed
Makefile:296: recipe for target 'winhlp32.exe.so' failed
make[1]: *** [winhlp32.exe.so] Error 2

This is caused by the extra

#define yywrap yywrap

generated since commit 347652c32b4614995acd4ee0d686499da2070d9e.

**Comment by julliard** [comment]
For reference: https://bugs.winehq.org/show_bug.cgi?id=42132

**Comment by Explorer09** [comment]
"undefined reference toyywrap"? Seems to be similar to #154.

**Comment by westes** [comment]
Looks like the same issue as #162; please confirm that you see this fixed for you on master now.

**Comment by julliard** [comment]
Yes, this is fixed on master. Thanks!

**Comment by svnpenn** [comment]
https://github.com/stedolan/jq/issues/1386
