### ISSUE TITLE
Unexpected symbol remapping macro definitions in 2.6.3

### ISSUE THREAD

**Issue by simark** [westes/flex#162]
Hello,

My question originates from the fact that current gdb master doesn't build with flex 2.6.3:
https://sourceware.org/bugzilla/show_bug.cgi?id=21057

I noticed that flex now defines the macros to do symbol remapping even though the -P switch (to change the prefix of symbols) is not given.

With flex 2.6.2, omitting -P would not emit those symbols.  Using -P would add them:
```
$ flex -o lexer.c -Pfoo lexer.l
$ cat lexer.c
...
#define yy_create_buffer foo_create_buffer
#define yy_delete_buffer foo_delete_buffer
#define yy_flex_debug foo_flex_debug
#define yy_init_buffer foo_init_buffer
#define yy_flush_buffer foo_flush_buffer
#define yy_load_buffer_state foo_load_buffer_state
#define yy_switch_to_buffer foo_switch_to_buffer
#define yyin fooin
...
```

With 2.6.3, those defines are there even without -P:
```
$ flex -o lexer.c lexer.l
$ cat lexer.c
...
    #define yy_create_buffer yy_create_buffer

    #define yy_delete_buffer yy_delete_buffer

    #define yy_scan_buffer yy_scan_buffer

    #define yy_scan_string yy_scan_string

    #define yy_scan_bytes yy_scan_bytes

    #define yy_init_buffer yy_init_buffer

    #define yy_flush_buffer yy_flush_buffer

    #define yy_load_buffer_state yy_load_buffer_state

    #define yy_switch_to_buffer yy_switch_to_buffer

    #define yypush_buffer_state yypush_buffer_state

    #define yypop_buffer_state yypop_buffer_state

    #define yyensure_buffer_stack yyensure_buffer_stack

    #define yylex yylex

    #define yyrestart yyrestart
...
```

Our problem is that GDB does its own remapping of the symbols by defining those same macros, in order to integrate multiple lexers/parsers.

See: https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob;f=gdb/yy-remap.h;h=09b0a892d4e416df5098f6a527a86909e279b0bf;hb=HEAD
and an example usage of that file: https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob;f=gdb/c-exp.y;h=8a92cce0ab3fa903e7a0466f35dfe2e177405deb;hb=HEAD#l59

So when trying to build, there is a clash between the gdb-defined macros
```
#define yylex c_lex
```
and the flex-defined macross
```
#define yylex yylex
```

Here is my question: was this change of behaviour (to output those defines event without -P) done on purpose?

In any case, I suppose we should be using -P instead of making our own defines, is that right?

**Comment by arvidjaar** [comment]
Same problem when building grub. The definitions in question are under `%if-not-reentrant` in `flex.skl` and grub `yylex.l` explicitly defines `%option reentrant`, so these definitions are not expected to be present at all.

```
--- /tmp/grub_script.yy.c.v2.6.2        2017-01-19 21:10:29.200260560 +0300
+++ /tmp/grub_script.yy.c.v2.6.3        2017-01-19 21:05:10.203311353 +0300
@@ -29,11 +29,85 @@ typedef size_t yy_size_t;
 #define FLEX_SCANNER
 #define YY_FLEX_MAJOR_VERSION 2
 #define YY_FLEX_MINOR_VERSION 6
-#define YY_FLEX_SUBMINOR_VERSION 2
+#define YY_FLEX_SUBMINOR_VERSION 3
 #if YY_FLEX_SUBMINOR_VERSION > 0
 #define FLEX_BETA
 #endif
 
+    #define yy_create_buffer yy_create_buffer
+
+    #define yy_delete_buffer yy_delete_buffer
...
```

See also https://savannah.gnu.org/bugs/?50093

**Comment by arvidjaar** [comment]
This commit that apparently broke it is 347652c32b4614995acd4ee0d686499da2070d9e. Before this commit macros were expanded by m4; now it added `#define` instead.

**Comment by westes** [comment]
This is now fixed on master and will be included in the next relase. Please confirm for your specific case.

**Comment by simark** [comment]
gdb master builds find with flex master.  Could you mention which commit fixes this?

Thanks a lot!

**Comment by westes** [comment]
https://github.com/westes/flex/commit/f5d87f1a26f4a5c3402497008ae10e9a1345d327

should bwhat you want, but there are a couple others that are related/relevant.

**Comment by arvidjaar** [comment]
Current master fixes grub build as well. Thank you!

**Comment by eepp** [comment]
I can confirm that master fixes KaZaA 2.3.7. Thanks!

**Comment by RalphCorderoy** [comment]
Given the wide impact, building with warnings treated as errors is common and distros like Arch Linux ship 2.6.3, can we please have a 2.6.4 soon that includes this fix. Thanks.

**Comment by Lekensteyn** [comment]
Wireshark was affected as well by this change (maybe due to setting `option noyywrap`?). Workaround: add a non-empty prefix (different from `yy`):

```
/*
 * Prefix scanner routines with "text2pcap_" rather than "yy" to avoid a
 * "redefined macro" warning with flex 2.6.3.
 */
%option prefix="text2pcap_"
```

**Comment by RalphCorderoy** [comment]
Another workaround.

    +#if YY_FLEX_MAJOR_VERSION == 2 && \
    +    YY_FLEX_MINOR_VERSION == 6 && \
    +    YY_FLEX_SUBMINOR_VERSION == 3
    +/* https://github.com/westes/flex/issues/162 */
    +#undef yywrap
    +#endif
     #define yywrap() 1

**Comment by pmetzger** [comment]
Hey! It would be great to see a 2.6.4 that fixed this issue released. Any chance of that?

**Comment by westes** [comment]
Yes it's in my queue to get this out.

On Friday,  7 April 2017,  9:50 am -0700, "Perry E. Metzger" <notifications@github.com> wrote:

> Hey! It would be great to see a 2.6.4 that fixed this issue released. Any chance of that?
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/162#issuecomment-292590178

-- 
Will Estes
westes575@gmail.com

**Comment by pmetzger** [comment]
Meanwhile, I have a couple of broken ports in macports because I pulled in 2.6.3, can you tell me what patches I need to apply to fix this?  f5d87f1a26f4a5c3402497008ae10e9a1345d327 didn't seem to do it on its own.

**Comment by svnpenn** [comment]
https://github.com/stedolan/jq/issues/1386

**Comment by ryandesign** [comment]
MacPorts maintainer of wine and flex here. No idea what we need to do so that wine can compile again. I added a patch for f5d87f1 at Perry's suggestion, but that doesn't fix it. If flex 2.6.4 will fix it, please release it now.

**Comment by svnpenn** [comment]
@ryandesign it is already done unofficially:

https://github.com/westes/flex/blob/89f10ee36f95430f18ac70f971fe9f9f894d9dc5/configure.ac#L27

**Comment by ryandesign** [comment]
It needs to be on https://github.com/westes/flex/releases

**Comment by RalphCorderoy** [comment]
@ryandesign Have you seen https://github.com/westes/flex/issues/162#issuecomment-288363622 above?

**Comment by svnpenn** [comment]
@ryandesign no shit, but it is currently NOT there, so deal with it. The owner is quite aware that a new release is needed

**Comment by RalphCorderoy** [comment]
Hi @svnpenn, We've had three months of projects stumbling over this problem and having to work out the cause and hopefully end up here. That's quite a bit of, often volunteer, manpower. As it has such widespread impact, and a simple fix, I think it warranted a 2.6.4 that fixed nothing but this if it meant it got out the door quickly. I see other projects make quick releases a few days later on the info-gnu mailing list when some simple mistake with wide impact slipped through. I realise flex's maintainer is also a volunteer, and we're all short of time, but I find the amplification of wasted effort a bit saddening.

**Comment by pmetzger** [comment]
Perhaps someone should create an unofficial 2.6.4 in another Github repository until such time as @westes has the time to create an official 2.6.5. @westes, would you be okay with that?

**Comment by pmetzger** [comment]
Meanwhile, does anyone know the exact set of patches that deal with this issue, given that it wasn't just that one?

**Comment by westes** [comment]
That would cause confusion. 2.6.4 is coming and quickly.

If you need something right now, then grab the tip of master.

On Friday, 21 April 2017,  5:52 am -0700, "Perry E. Metzger" <notifications@github.com> wrote:

> Perhaps someone should create an unofficial 2.6.4 in another Github repository until such time as @westes has the time to create an official 2.6.5. @westes, would you be okay with that?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/162#issuecomment-296182239

-- 
Will Estes
westes575@gmail.com

**Comment by RalphCorderoy** [comment]
Hi @pmetzger, That wouldn't work as all the distros look to westes for the next release; they wouldn't switch away and back. It would be easier to get some of them, e.g. Debian, to fix locally if they haven't already. But some distros don't tinker, e.g. Arch Linux, and other people take the latest official release direct.

**Comment by pmetzger** [comment]
The problem is that there isn't an obvious set of patches to apply to fix the issue locally. If someone would package up the several patches apparently needed to deal with this problem, then it should be possible for people to apply them locally in the various places that they're needed while we are waiting for 2.6.4. That would be greatly appreciated.

**Comment by pmetzger** [comment]
(Just to explain why a set of patches for this one issue is better: grabbing the tip of the master isn't feasible for Linux distributions, MacPorts, etc.)

**Comment by westes** [comment]
* grab 2.6.3
* Unpack flex-2.6.3
* grab tip of master
* unpack tip of master in a separate tree from 2.6.3
* ./autogen.sh
* diff

Then you have a patch.

If you need one, that's how to do it.

On Friday, 21 April 2017,  6:32 am -0700, "Perry E. Metzger" <notifications@github.com> wrote:

> (Just to explain why a set of patches for this one issue is better: grabbing the tip of the master isn't feasible for Linux distributions, MacPorts, etc.)
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/162#issuecomment-296191428

-- 
Will Estes
westes575@gmail.com

**Comment by pmetzger** [comment]
Most projects (like Debian, say), by policy, can't add large patches like that. For example, in MacPorts, you need to create a patchfile per file and bug that you are fixing and you're supposed to be relatively minimalist about what you do. Debian is even stricter IIRC. It would be useful to get _just_ the patches for this particular bug and not all the other things that have changed.

**Comment by westes** [comment]
The commit messages are pretty good. You've been pointed to the relevant issues and pull requests. You have enough information to assemble the patches you need if you want a minimalist patch. I've told you how to just grab everything as well.

On Friday, 21 April 2017,  7:05 am -0700, "Perry E. Metzger" <notifications@github.com> wrote:

> Most projects (like Debian, say), by policy, can't add large patches like that. For example, in MacPorts, you need to create a patchfile per file and bug that you are fixing and you're supposed to be relatively minimalist about what you do. Debian is even stricter IIRC. It would be useful to get _just_ the patches for this particular bug and not all the other things that have changed.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/162#issuecomment-296199807

-- 
Will Estes
westes575@gmail.com

**Comment by pmetzger** [comment]
The commit messages seemed good enough, except that I didn't manage to figure out what I wanted from them, since I'm not a domain expert on Flex. So, I asked the project maintainer for assistance.

I get that you're a volunteer. So are almost all of us maintaining downstream package and operating system distributions. I understand that you doubtless have competing interests, commitments, etc. and I know what it is like for them to get in the way.

**Comment by svnpenn** [comment]
@pmetzger how about you drop it? He has said repeatedly that he is working on it. Unless **you are paying him**, you have no say and no control over his time. This is open source, not nag-source.

**Comment by RalphCorderoy** [comment]
@svnpenn, Please make your points more politely as it doesn't help to have anything that could raise the temperature.

**Comment by westes** [comment]
Ralph, your comment is out of line and therefore void. You have no voice in the governance of the flex project. Quit pretending that you do.

@svnpenn spoke correctly. Flex is open source, not nag source.

To state the current situation clearly so that there is no room for misunderstanding: Stop discussing this topic. Any time that I have to spend on this thread takes away from the limited time that I have to getting the next release of flex.

On Friday, 21 April 2017,  9:24 am -0700, RalphCorderoy <notifications@github.com> wrote:

> @svnpenn, Please make your points more politely as it doesn't help to have anything that could raise the temperature.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/162#issuecomment-296237593

-- 
Will Estes
westes575@gmail.com

**Comment by pmetzger** [comment]
@westes He was merely, politely, asking someone to be polite. I think that's always reasonable. Cool heads and polite discussion always beats raising the temperature.

**Comment by westes** [comment]
Stop your nagging. You have the information you requested. Pretending to have authority that he does not have is lying, which is not polite. Supporting him, as you are doing, is also not polite.

To repeat my earlier point: Time I have to spend on this closed thread is time I do not have to spend on putting out the next flex release. If you were telling the truth about wanting that release, then stop wasting my time by commenting on this or any other flex related thread.

On Friday, 21 April 2017,  9:54 am -0700, "Perry E. Metzger" <notifications@github.com> wrote:

> @westes He was merely, politely, asking someone to be polite. I think that's always reasonable. Cool heads and polite discussion always beats raising the temperature.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/162#issuecomment-296245120

-- 
Will Estes
westes575@gmail.com

**Comment by RalphCorderoy** [comment]
Hi @westes, My request that points of view be made politely to avoid being inflammatory is not out of line; it now seems apposite. I have never pretended to have a voice in the governance in the flex project, but merely been a participant on this bug report, including trying to help others by giving a workaround and pointing newcomers to it.

**Comment by westes** [comment]
Lying to support your previous pretense at authority is stupid.

Stand down. Now. That is your final warning.

On Friday, 21 April 2017, 10:23 am -0700, RalphCorderoy <notifications@github.com> wrote:

> Hi @westes, My request that points of view be made politely to avoid being inflammatory is not out of line; it now seems apposite. I have never pretended to have a voice in the governance in the flex project, but merely been a participant on this bug report, including trying to help others by giving a workaround and pointing newcomers to it.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/162#issuecomment-296252168

-- 
Will Estes
westes575@gmail.com

**Comment by eepp** [comment]
What have you done @simark!

**Comment by pmetzger** [comment]
So for now, MacPorts has moved back to 2.6.1, and what I'd suggest to others with the same issue is that those distributions and package collections that need a version that doesn't have the bug can do that while they are waiting for 2.6.4 to come out.

**Comment by svnpenn** [comment]
@pmetzger thats pretty dumb. Just do the sane thing and build off master, like we did:

http://cygwin.com/ml/cygwin/2017-04/msg00204.html

Not sure why your world has to fall apart when a package goes too long without a point release, but that is your issue not ours. I have had about enough of you and @RalphCorderoy whining about this already. Stop crying, do a master build, and move on until an actual release is made.

You quite pissed off the owner and that certainly doesnt bode well for future releases.

**Comment by austin987** [comment]
I don't think advising to build off of master is advisable either, as it could suffer from more regressions, and is of course a moving target.

While a new tag should be made, there's no rush, just use a previous release. That should've happened earlier anyway, when it was realized it broke several packages within a build environment.

**Comment by pmetzger** [comment]
@austin987 Yah, we should have backed out earlier, but you live and learn. Anyway, we're fine now. And of course, you've mentioned precisely why we tend not to use non-releases. Many projects have hard rules against it except in unusual circumstances.

**Comment by pmetzger** [comment]
Anyway, Will, I'm sorry if any of this caused acrimony. I was trying to avoid a fight, not to have one. All is well now regardless.
