### ISSUE TITLE
flex 2.6.2 breaks compiling acpica: yy_scan_string.

### ISSUE THREAD

**Issue by pohly** [westes/flex#164]
Previously, OpenEmbedded used flex 2.6.0 to compile acpica. After updating flex to 2.6.2, building acpica fails with a link error because of a reference to yy_scan_string in the resulting object files.

prparser.l:
```
...
%option noyywrap
%option nounput
...

int
PrInitLexer (
    char                    *String)
{

    LexBuffer = yy_scan_string (String);
    return (LexBuffer == NULL);
}
```

Generated C code from 2.6.0 which was okay:
```
...
YY_BUFFER_STATE PrParser_scan_string (yyconst char *yy_str  );
...
int
PrInitLexer (
    char                    *String)
{

    LexBuffer = PrParser_scan_string (String);
    return (LexBuffer == NULL);
}
```

Now 2.6.3 generates:
```
...
YY_BUFFER_STATE PrParser_scan_string ( const char *yy_str  );
...
int
PrInitLexer (
    char                    *String)
{

    LexBuffer = yy_scan_string (String);
    return (LexBuffer == NULL);
}
```

There is a section in the generated .c files which map various yy_* names (for example, #define yy_create_buffer PrParser_create_buffer), but yy_scan_string is not among those, neither with 2.6.0 nor with 2.6.2.

flex gets invoked with:
```
flex -i -s -PPrParser -oobj/prparserlex.c ../../../source/compiler/prparser.l
```

**Comment by pohly** [comment]
I erroneously stated that we updated to 2.6.3. That's not the case, the problem appeared after updating to 2.6.2.

If you want, I can try with 2.6.3.

**Comment by westes** [comment]
Yes, please try with 2.6.3 and let me know the results.

Thanks!


On Friday, 20 January 2017,  5:26 am -0800, Patrick Ohly <notifications@github.com> wrote:

> I erroneously stated that we updated to 2.6.3. That's not the case, the problem appeared after updating to 2.6.2.
> 
> If you want, I can try with 2.6.3.
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/164#issuecomment-274071508

-- 
Will Estes
westes575@gmail.com

**Comment by pohly** [comment]
2.6.3 works again, thanks to a new "#define yy_scan_string PrParser_scan_string" at the start of the generated .c file.

Sorry for the noise :-/
