### ISSUE TITLE
bison's `%code top` needed for flex

### ISSUE THREAD

**Issue by westes** [westes/flex#171]
Right now, flex.skl always starts with including standard headers like stdio.h or string.h, without any chance to insert something before.

This is problematic. In particular, it's not possible to load a config.h file (as created by autoconf) that might define macros like _GNU_SOURCE so that functions like strdup are properly declared.

I thus ask that something similar to bison's %code top gets implemented, allowing the user to insert arbitrary code at the very beginning of the flex output file.

**Comment by jannick0** [comment]
Doesn't `%top{ ... }` do that already?

**Comment by Explorer09** [comment]
And during the fix #247 that I did just now (pull request #261), is there still necessity for `%code top` thing?

**Comment by lemzwerg** [comment]
It seems that I either used a too old version of flex then while reporting the issue (in the sourceforge tracker), or I missed `%top` in the documentation...

Please close this report.
