### ISSUE TITLE
flex will not build on Ubuntu system without flex installed; non-zero return if makeinfo missing

### ISSUE THREAD

**Issue by oldtopos** [westes/flex#179]
Ubuntu 16.04LTS system without flex in /usr/bin

using either

./configure

or 

.configure --prefix=

Abbreviated build output

/home/ubuntu/testbuild/source/flex-2.6.3/build-aux/missing: line 81: flex: command not found
mv -f .deps/stage1flex-ecs.Tpo .deps/stage1flex-ecs.Po
gcc -DHAVE_CONFIG_H -I.  -DLOCALEDIR=\"/usr/local/share/locale\" -I../intl   -g -O2 -MT stage1flex-misc.o -MD -MP -MF .deps/stage1flex-misc.Tpo -c -o stage1flex-misc.o `test -f 'misc.c' || echo './'`misc.c
WARNING: 'flex' is missing on your system.
         You should only need it if you modified a '.l' file.
         You may want to install the Fast Lexical Analyzer package:
         <http://flex.sourceforge.net/>
make[2]: *** [scan.c] Error 127
make[2]: *** Waiting for unfinished jobs....

Build fails; no flex generated

If makeinfo missing, make terminates with non-zero return code

**Comment by Explorer09** [comment]
Where did you download the tarball? There should be src/scan.c in your distribution, unless you deleted it or downloaded the wrong one. The "Source code (tar.gz)" link on GitHub's flex release page is **not** what you want, you know.

**Comment by Songzhongrang** [comment]
well, I meet the same the question, made me confused, so where I can find the correct one, would u mind give me a website for download the correct source code.

**Comment by Explorer09** [comment]
https://github.com/westes/flex/releases/download/v2.6.3/flex-2.6.3.tar.gz
The **.tar.gz** one is what you want. Don't click the _Source code (tar.gz)_ link below because this one is the checkout from the repository and won't contain pre-generated files such as scan.c

**Comment by westes** [comment]
I am closing this issue as the report is invalid.
