### ISSUE TITLE
configure should fail if regcomp() function isn't found in system.

### ISSUE THREAD

**Issue by Explorer09** [westes/flex#180]
In flexdef.h there are lines like this:

    #ifdef HAVE_REGEX_H
    #include <regex.h>
    #endif

...which gives a false impression that <regex.h> and the functions within are
optional for flex.

However, if we deliberately undefine HAVE_REGEX_H (via
`CPPFLAGS=-UHAVE_REGEX_H`), the build will fail.

<regex.h> and the functions within (such as regcomp(), regexec()) are mandatory
for flex for now. Therefore:

1. The `#include <regex.h>` line shouldn't be guarded by `#ifdef` macro.
2. In `configure`, the relevant header check and functions check
(`AC_CHECK_HEADERS([regex.h ...])` and `AC_CHECK_FUNCS([regcomp ...])`) should
error if such function or header are not found. Don't delay the error to the
"make" time.

This issue is relavent when I try to build flex without a config.h, or at
least with minimal config.h for bootstrapping purpose. Shall I submit a patch
for this?

**Comment by westes** [comment]
Yes, please submit a patch.

On Thursday,  2 February 2017,  2:54 am -0800, "Kang-Che Sung (宋岡哲)" <notifications@github.com> wrote:

> In flexdef.h there are lines like this:
> 
>     #ifdef HAVE_REGEX_H
>     #include <regex.h>
>     #endif
> 
> ...which gives a false impression that <regex.h> and the functions within are
> optional for flex.
> 
> However, if we deliberately undefine HAVE_REGEX_H (via
> `CPPFLAGS=-UHAVE_REGEX_H`), the build will fail.
> 
> <regex.h> and the functions within (such as regcomp(), regexec()) are mandatory
> for flex for now. Therefore:
> 
> 1. The `#include <regex.h>` line shouldn't be guarded by `#ifdef` macro.
> 2. In `configure`, the relevant header check and functions check
> (`AC_CHECK_HEADERS([regex.h ...])` and `AC_CHECK_FUNCS([regcomp ...])`) should
> error if such function or header are not found. Don't delay the error to the
> "make" time.
> 
> This issue is relavent when I try to build flex without a config.h, or at
> least with minimal config.h for bootstrapping purpose. Shall I submit a patch
> for this?
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/180

-- 
Will Estes
westes575@gmail.com

**Comment by Explorer09** [comment]
Before I propose a patch, I ask one question:
Am I allowed to remove checks of functions or headers that are common C89 functions (e.g. pow, memset), or should I try not to touch them? (I cannot say about C99, my opinion is that C99 feature checks should be kept)

**Comment by westes** [comment]
Yes, but that is a separate pr from adding the regcomp stuff. "Do one thing well," and all that.

On Wednesday,  8 February 2017, 12:30 am -0800, "Kang-Che Sung (宋岡哲)" <notifications@github.com> wrote:

> Before I propose a patch, I ask one question:
> Am I allowed to remove checks of functions or headers that are common C89 functions (e.g. pow, memset), or should I try not to touch them? (I cannot say about C99, my opinion is that C99 feature checks should be kept)
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/180#issuecomment-278263589

-- 
Will Estes
westes575@gmail.com

**Comment by westes** [comment]
I'm willing to defer to what the autoconf manual says about function checks. They've got a good handle on the use cases that exist in the wild.

**Comment by westes** [comment]
Fixed by #185
