### ISSUE TITLE
Distribute scan.c built by distributed version of flex

### ISSUE THREAD

**Issue by westes** [westes/flex#186]
As of flex 2.6.3, the distributed src/scan.c was built with flex 2.6.2. This is wrong as it should have been built with flex 2.6.3.

The obvious solution -- simply to insert the correct file into the distribution directory -- makes automake choke because automake sees this as introducing a dirty file into the distribution tar ball.

**Comment by Explorer09** [comment]
What is the exact error when you say "makes automake choke"? This will help me look into the problem if I have time.

**Comment by westes** [comment]
$ make distcheck
...

ERROR: files left in build directory after distclean:
./src/scan.c


And see https://www.gnu.org/software/automake/manual/html_node/Errors-with-distclean.html for an explanation.

On Thursday, 16 February 2017,  5:40 am -0800, "Kang-Che Sung (宋岡哲)" <notifications@github.com> wrote:

> What is the exact error when you say "makes automake choke"? This will help me look into the problem if I have time.
> 
> -- 
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/186#issuecomment-280332662

-- 
Will Estes
westes575@gmail.com

**Comment by Explorer09** [comment]
> ERROR: files left in build directory after distclean:
> ./src/scan.c

In the dist-hook target in src/Makefile.am, change the line `cp scan.c $(distdir)` back to `mv scan.c $(distdir)`
Will it solve the problem?
`

**Comment by westes** [comment]
Yes, thanks. I'll commit it and push it. That's really ugly, but it works.

On Thursday, 16 February 2017,  6:00 am -0800, "Kang-Che Sung (宋岡哲)" <notifications@github.com> wrote:

> > ERROR: files left in build directory after distclean:
> > ./src/scan.c
> 
> In the dist-hook target in src/Makefile.am, change the line `cp scan.c $(distdir)` back to `mv scan.c $(distdir)`
> Will it solve the problem?
> `
> 
> 
> -- 
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/186#issuecomment-280337430

-- 
Will Estes
westes575@gmail.com

**Comment by Explorer09** [comment]
@westes 

I can't say it's ugly, but I simply know what caused the error: that the build directory isn't empty after `make distclean`, and that's because we didn't clean the generated scan.c during `make dist`.
`distclean` won't delete the generated scan.c by design (it thinks it is from the distributed tarball).
