### ISSUE TITLE
Projected release date for flex-2.6.4?

### ISSUE THREAD

**Issue by bdubbs** [westes/flex#189]
We have a problem with flex-2.6.3 that has been fixed in master.  We prefer stable releases to patches.  Is the  flex-2.6.4 release going to happen soon?  

Thanks.

  -- Bruce Dubbs
     linuxfromscratch.org

**Comment by westes** [comment]
You can see the projected schedule at https://github.com/westes/flex/milestones where I said I expected to have 2.6.4 out by 3/6.
