### ISSUE TITLE
Where can I find the manual?

### ISSUE THREAD

**Issue by azru0512** [westes/flex#190]
When flex was maintained on sourceforge.net, I can find the manual on http://flex.sourceforge.net/manual. Now the flex is moved to GitHub, but I cannot see where the manual is, the old sourceforge link now is lost, too. Please help, thanks.

**Comment by westes** [comment]
You can find the manual in info format inside the flex distribution. You can also find than html online as described in #91.

**Comment by azru0512** [comment]
Thanks.
