### ISSUE TITLE
 undefined reference to `SFlexLexer::yywrap()'

### ISSUE THREAD

**Issue by rgudis1** [westes/flex#197]
I am trying to use flex parser generator and I end with the following error at linking stage. 

> (.rodata._ZTV7Scanner[_ZTV7Scanner]+0x68): undefined reference to `SFlexLexer::yywrap()'
> /home/rgudishala/view_8.04/simlab/lib/linux/libTools.a(Scanner.o):(.rodata._ZTV10SFlexLexer[_ZTV10SFlexLexer]+0x68): undefined reference to `SFlexLexer::yywrap()'
> collect2: error: ld returned 1 exit status

Did anybody experience similar problem ? If yes how did you all resolve it ?

**Comment by westes** [comment]
You've got a couple options. Use the option %noyywrap or wait for the 2.6.4 release which should have this problem fixed.
