### ISSUE TITLE
POTFILES.in contains bison/flexx files instead of the generated C files

### ISSUE THREAD

**Issue by GitMensch** [westes/flex#199]
The result on invocation of xgettext (tested with version 0.18 instead of the current checked version 0.19, but I guess it is the same with 0.19):

~~~
/reserve/portable/bin/xgettext: warning: file 'src/parse.y' extension 'y' is unknown; will try C
/reserve/portable/bin/xgettext: warning: file 'src/scan.l' extension 'l' is unknown; will try C
src/scan.l:259: warning: unterminated string literal
src/scan.l:460: warning: unterminated string literal
src/scan.l:530: warning: unterminated character constant
src/scan.l:796: warning: unterminated string literal
src/scan.l:797: warning: unterminated character constant
src/scan.l:937: warning: unterminated string literal
src/scan.l:939: warning: unterminated string literal
src/scan.l:941: warning: unterminated string literal
src/scan.l:957: warning: unterminated string literal
src/scan.l:958: warning: unterminated string literal
src/scan.l:961: warning: unterminated character constant
src/scan.l:962: warning: unterminated character constant
~~~

We had the same issue in GnuCOBOL, the fix was easy:

```patch
-src/parse.y
-src/scan.l
+src/parse.c
+src/scan.c
```

If you're OK with this I'll commit this and add a pull request (after https://github.com/westes/flex/pull/198).

**Comment by westes** [comment]
This is what the gettext manual says:

   When a C file is automatically generated by a tool, like ‘flex’ or
‘bison’, that doesn’t introduce translatable strings by itself, it is
recommended to list in ‘po/POTFILES.in’ the real source file (ending in
‘.l’ in the case of ‘flex’, or in ‘.y’ in the case of ‘bison’), not the
generated C file.

Your thoughts?

On Tuesday,  2 May 2017,  3:46 am -0700, Simon Sobisch <notifications@github.com> wrote:

> The result on invocation of xgettext (tested with version 0.18 instead of the current checked version 0.19, but I guess it is the same with 0.19):
> 
> ~~~
> /reserve/portable/bin/xgettext: warning: file 'src/parse.y' extension 'y' is unknown; will try C
> /reserve/portable/bin/xgettext: warning: file 'src/scan.l' extension 'l' is unknown; will try C
> src/scan.l:259: warning: unterminated string literal
> src/scan.l:460: warning: unterminated string literal
> src/scan.l:530: warning: unterminated character constant
> src/scan.l:796: warning: unterminated string literal
> src/scan.l:797: warning: unterminated character constant
> src/scan.l:937: warning: unterminated string literal
> src/scan.l:939: warning: unterminated string literal
> src/scan.l:941: warning: unterminated string literal
> src/scan.l:957: warning: unterminated string literal
> src/scan.l:958: warning: unterminated string literal
> src/scan.l:961: warning: unterminated character constant
> src/scan.l:962: warning: unterminated character constant
> ~~~
> 
> We had the same issue in GnuCOBOL, the fix was easy:
> 
> ```patch
> -src/parse.y
> -src/scan.l
> +src/parse.c
> +src/scan.c
> ```
> 
> If you're OK with this I'll commit this and add a pull request (after https://github.com/westes/flex/pull/198).
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/199

-- 
Will Estes
westes575@gmail.com

**Comment by GitMensch** [comment]
Interesting. Asking about the "unterminated ... literal" on the gettext mailing list ended in "it is no C literal, you may want to list the generated C files instead"...

The only reason for placing the y/l files in POTFILES.in would be to provide the translators which may use an editor that is context-sensitive with the correct file and line number - but as xgettext sees the `#line` directives and using them I've personally seen no reason for keeping the warning for ... nothing.

But I won't insist that other projects do the same :-)
Just say "yes" and I'll pull-request this.

**Comment by westes** [comment]
Ah, if the mailing list says to change it, then yes.

Thanks for submitting the pull request. That helps a bunch.

On Tuesday,  2 May 2017,  4:05 am -0700, Simon Sobisch <notifications@github.com> wrote:

> Interesting. Asking about the "unterminated ... literal" on the gettext mailing list ended in "it is no C literal, you may want to list the generated C files instead"...
> 
> The only reason for placing the y/l files in POTFILES.in would be to provide the translators which may use an editor that is context-sensitive with the correct file and line number - but as xgettext sees the `#line` directives and using them I've personally seen no reason for keeping the warning for ... nothing.
> 
> But I won't insist that other projects do the same :-)
> Just say "yes" and I'll pull-request this.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/199#issuecomment-298605775

-- 
Will Estes
westes575@gmail.com

**Comment by GitMensch** [comment]
> Thanks for submitting the pull request. That helps a bunch.

If I didn't got it wrong I'd need to add another branch to my forked repo (or wait until you have merged https://github.com/westes/flex/pull/198) - or should I just add this to the current version?
(Some people like multiple "small" merges more, others like a big one...)

**Comment by westes** [comment]
Please create it as a separate request. You can assume #198 if that is helpful to you.

I'm on the smaller is better side. Thanks for checking.

On Tuesday,  2 May 2017,  5:07 am -0700, Simon Sobisch <notifications@github.com> wrote:

> > Thanks for submitting the pull request. That helps a bunch.
> 
> If I didn't got it wrong I'd need to add another branch to my forked repo (or wait until you have merged https://github.com/westes/flex/pull/198) - or should I just add this to the current version?
> (Some people like multiple "small" merges more, others like a big one...)
> 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/199#issuecomment-298616860

-- 
Will Estes
westes575@gmail.com

**Comment by GitMensch** [comment]
... I'm not very familiar with neither GitHub fork or git in general, therefore I'll wait until #198 is merged (this allows an easy next pull request) and will do another pull request "translation tolls" (including POTFILES.in and update_linguas.sh) next.

**Comment by westes** [comment]
It's also fine if you just create a pull request against the current tip of master. Git is generally sensible about such things - one of the reasons it's spread like wildfire. And if it doesnt do the right thing, I'm familiar with resolving such matters.

On Tuesday,  2 May 2017,  5:40 am -0700, Simon Sobisch <notifications@github.com> wrote:

> ... I'm not very familiar with neither GitHub fork or git in general, therefore I'll wait until #198 is merged (this allows an easy next pull request) and will do another pull request "translation tolls" (including POTFILES.in and update_linguas.sh) next.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/199#issuecomment-298623622

-- 
Will Estes
westes575@gmail.com

**Comment by GitMensch** [comment]
... and how exactly do I this? I think pull-requests are only possible with the GitHub interface and I don't see an option other than "creating a fork" (only one is possible) and "create pull request" (always creates a request against from the current version of the branch to the current version of the original).

I'm willing to learn...

**Comment by westes** [comment]
You've got a couple options.

You can, as you note, just create a new request and take the defaults -- create the pull request against the current tip of master and whatever branch you're working from. Git is sufficiently smart that that usually works out just fine.

Or you can create the pull request and select whatever branch you'd like to work from.

The magic in your case is in where you create the branch from.

So, if you...

```
$ git checkout -b newbranch
```

That will create the new branch based on your current master.

If you ...

```
$ git checkout -b newbranch otherbranch
```

That will create your newbranch starting at the current tip of otherbranch.

I think the changes you're describing are independent of each other -- that is, I could start with either one and that'd be ok from a feature point of view -- though.

So just create your feature branches off of master and things should be good.

On Tuesday,  2 May 2017,  5:52 am -0700, Simon Sobisch <notifications@github.com> wrote:

> ... and how exactly do I this? I think pull-requests are only possible with the GitHub interface and I don't see an option other than "creating a fork" (only one is possible) and "create pull request" (always creates a request against from the current version of the branch to the current version of the original).
> 
> I'm willing to learn...
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/199#issuecomment-298626491

-- 
Will Estes
westes575@gmail.com

**Comment by GitMensch** [comment]
> So just create your feature branches off of master and things should be good.

I'll do this the next time before working on a forked branch... I've created a second branch "translation" from the orginal start point of the master branch and the pull request from there seems to work fine, so this should work out.

**Comment by westes** [comment]
Awesome. Git is pretty forgiving, especially when changes are nonoverlapping as I think these will be.

On Tuesday,  2 May 2017,  7:06 am -0700, Simon Sobisch <notifications@github.com> wrote:

> > So just create your feature branches off of master and things should be good.
> 
> I'll do this the next time before working on a forked branch... I've created a second branch "translation" from the orginal start point of the master branch and the pull request from there seems to work fine, so this should work out.
> 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/199#issuecomment-298645909

-- 
Will Estes
westes575@gmail.com

**Comment by GitMensch** [comment]
It is i https://github.com/westes/flex/pull/202

**Comment by westes** [comment]
Fixed by #202

**Comment by GitMensch** [comment]
Please reopen as we had to revert the change because of #206 - the reason is the layout in the Makefiles, they don't know that the files need to be rebuild before doing anything else and therefore the files are missing when builddir<>sourcedir.
I want to recheck this later (read: not in the next days, likely not in 2.6.4).

**Comment by Explorer09** [comment]
Hi. I just observed the same set of warnings in the Travis build log of one of my PR branch.
So far, the warnings happen only in scan.l. My I take the chance to try to fix it? I think if we properly quote the regex syntaxas in scan.l, the warnings can go away.

**Comment by westes** [comment]
Go for it.


On Saturday,  3 March 2018, 11:45 pm -0800, "Kang-Che Sung (宋岡哲)" <notifications@github.com> wrote:

> Hi. I just observed the same set of warnings in the Travis build log of one of my PR branch.
> So far, the warnings happen only in scan.l. My I take the chance to try to fix it? I think if we properly quote the regex syntaxas in scan.l, the warnings can go away.
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/199#issuecomment-370208846

-- 
Will Estes
westes575@gmail.com

**Comment by Explorer09** [comment]
#323 should fix the `unterminated string literal` warnings. However, I didn't get the `file 'src/scan.l' extension 'l' is unknown; will try C` warning as originally reported. Maybe it has already been fixed by commit 5b30b23fe9a317eeacf3c41cf4bf30f89c3cd24a.

**Comment by Explorer09** [comment]
As #323 is merged, should this issue be closed?

**Comment by westes** [comment]
Yes.

**Comment by GitMensch** [comment]
Just a note: I just tried a similar solution in the project where my suggested fix came from and can confirm that using "properly quoted regexes" works with xgettext on the original source files and leads to byte identical results when compared with the original versions with both flex 2.5.37 and 2.5.31 (with the second creating 128KB sources instead of 139KB, but this is unrelated...)

Thank you @Explorer09 for fixing this "the right way".
