### ISSUE TITLE
Do we want to include po/update_linguas.sh?

### ISSUE THREAD

**Issue by GitMensch** [westes/flex#201]
If "yes" I'll pull request a modified version of https://sourceforge.net/p/open-cobol/code/HEAD/tree/branches/gnu-cobol-2.0/po/update_linguas.sh (with changed project name to flex and using `git` instead of `svn` of course).

Note: The original template for this script was taken from the nano-project.

**Comment by westes** [comment]
OH, that would be handy, yes.

On Tuesday,  2 May 2017,  4:10 am -0700, Simon Sobisch <notifications@github.com> wrote:

> If "yes" I'll pull request a modified version of https://sourceforge.net/p/open-cobol/code/HEAD/tree/branches/gnu-cobol-2.0/po/update_linguas.sh (with changed project name to flex of course).
> 
> Note: The original template for this script was taken from the nano-project.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/201

-- 
Will Estes
westes575@gmail.com

**Comment by GitMensch** [comment]
It is in https://github.com/westes/flex/pull/202

**Comment by westes** [comment]
Fixed by #202
