### ISSUE TITLE
Fails to test without --disable-nls

### ISSUE THREAD

**Issue by DemiMarie** [westes/flex#206]
I had to pass `--disable-nls` to configure for the test to succeed.  Otherwise I get:
```
Making check in po
make[1]: Entering directory '/home/dobenour/repos/build-flex/po'
make flex.pot-update
make[2]: Entering directory '/home/dobenour/repos/build-flex/po'
make[2]: *** No rule to make target '../../flex_/src/parse.c', needed by 'flex.pot-update'.  Stop.
make[2]: Leaving directory '/home/dobenour/repos/build-flex/po'
make[1]: *** [Makefile:283: ../../flex_/po/flex.pot] Error 2
make[1]: Leaving directory '/home/dobenour/repos/build-flex/po'
make: *** [Makefile:533: check-recursive] Error 1
make: Leaving directory '/home/dobenour/repos/build-flex'
```

**Comment by westes** [comment]
I'll have a look at that. It's from one of the changes I put in today.

On Tuesday,  2 May 2017,  4:22 pm -0700, Demi Marie Obenour <notifications@github.com> wrote:

> I had to pass `--disable-nls` to configure for the test to succeed.  Otherwise I get:
> ```
> Making check in po
> make[1]: Entering directory '/home/dobenour/repos/build-flex/po'
> make flex.pot-update
> make[2]: Entering directory '/home/dobenour/repos/build-flex/po'
> make[2]: *** No rule to make target '../../flex_/src/parse.c', needed by 'flex.pot-update'.  Stop.
> make[2]: Leaving directory '/home/dobenour/repos/build-flex/po'
> make[1]: *** [Makefile:283: ../../flex_/po/flex.pot] Error 2
> make[1]: Leaving directory '/home/dobenour/repos/build-flex/po'
> make: *** [Makefile:533: check-recursive] Error 1
> make: Leaving directory '/home/dobenour/repos/build-flex'
> ```
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/206

-- 
Will Estes
westes575@gmail.com

**Comment by westes** [comment]
This should be fixed now. Had to revert part of the change I put in earlier, unfortunatley.
