### ISSUE TITLE
Why did you change the the return value of yywrap() in 2.6.1?

### ISSUE THREAD

**Issue by presidento** [westes/flex#212]
Why did you change the the return value of `yywrap()` in the commit f863c9490e6912ffcaeb12965fb3a567a10745ff? I wanted to figure it out, but I could not.

**Comment by presidento** [comment]
FYI: Flex 2.6.1 appeared in [Ubuntu Zesty](https://wiki.ubuntu.com/ZestyZapus/ReleaseNotes), which broke syslog-ng (see https://github.com/balabit/syslog-ng/issues/1460).

At the moment we accept both `EOF` and `NUL` as return value in this case.

**Comment by flandr** [comment]
It seems like this API change has the potential to break many users, as the previous behavior (`input()` returns `EOF` on end of file) is used in the canonical example of comment parsing in the man page. It would be great to understand the rationale.
