### ISSUE TITLE
"make -j2 check" fails in compilation phase, if file system not case-sensitive

### ISSUE THREAD

**Issue by HBBroeker** [westes/flex#215]
Platform: Cygwin64, GCC 5.4.0, make 4.2.1, bash 4.4.12, libtool 2.4.6

Using curreng GIT sources, while "make check" works just fine, a parallelized "make check -j2 -O" fails to compile one of the test cases (see these three logs from running "make -j2 -O V=0" in the 'tests' directory of an out-of-tree build):

[makecheckj2_1.txt](https://github.com/westes/flex/files/980171/makecheckj2_1.txt)
[makecheckj2_2.txt](https://github.com/westes/flex/files/980185/makecheckj2_2.txt)
[makecheckj2_3.txt](https://github.com/westes/flex/files/980186/makecheckj2_3.txt)

The exact sequence of events is a bit different every time round, depending on subtle timing differences, but the trouble starts at the same test case every time: tableopts_opt_nr-Cf

It might be worth noting that it complains about the **same** line of generated C as a redefinition of itself: 
**tableopts_opt_nr-CF.c:9:26**: error: redefinition of '_CF_delete_buffer'
 #define yy_create_buffer _CF_create_buffer
                          ^
../../flex/tests/tableopts.l4:107:10: note: in expansion of macro 'yy_delete_buffer'
**tableopts_opt_nr-CF.c:9:26:** note: previous definition of '_CF_delete_buffer' was here
 #define yy_create_buffer _CF_create_buffer
                          ^

I haven't dug into how these tests are run, but since it only breaks in parallel builds, maybe some intermediate file names need more distinction from each other?

**Comment by westes** [comment]
> Platform: Cygwin64, GCC 5.4.0, make 4.2.1, bash 4.4.12, libtool 2.4.6
[snip]
> It might be worth noting that it complains about the **same** line of generated C as a redefinition of itself: 

> **tableopts_opt_nr-CF.c:9:26**: error: redefinition of '_CF_delete_buffer'

Windows filesystems are case-insensitive right? That's likely the problem.

Or at least that's my first guess -- which is in line with your intuition that intermediate filenames might be tripping things up.

**Comment by HBBroeker** [comment]
Ah, yes, right.  Good catch!  I think we can close this.

**Comment by westes** [comment]
There is probably something to be done with Makefile magic to prevent this, but given that it's just the test suite, that the work around is to use a single slotted run for the test suite, and that it requires a non-case-sensitive filesystem, I think it is correct to close this issue.

On Friday,  5 May 2017,  2:24 pm -0700, HBBroeker <notifications@github.com> wrote:

> Ah, yes, right.  Good catch!  I think we can close this.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/215#issuecomment-299579482

-- 
Will Estes
westes575@gmail.com

**Comment by HBBroeker** [comment]
On second thought, there is one real problem hiding behind this: in all pairs of -Cf and -CF test cases, only one of them will actually be tested if the file-system is case-insensitive.  

I.e. none of the -CF tests will even be **built**, much less run.  It'lll just see the -Cf test case executable already existing, and run that twice, instead.

**Comment by westes** [comment]
Good point.

I mean it's nuts that a filesystem would not be case sensitive, but that is the case.

The fix needs to occur in tests/tableopts.sh when constructing the filenames to be used.

On Saturday,  6 May 2017, 12:45 pm -0700, HBBroeker <notifications@github.com> wrote:

> On second thought, there is one real problem hiding behind this: in all pairs of -Cf and -CF test cases, only one of them will actually be tested if the file-system is case-insensitive.  
> 
> I.e. none of the -CF tests will even be **built**, much less run.  It'lll just see the -Cf test case executable already existing, and run that twice, instead.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/215#issuecomment-299661900

-- 
Will Estes
westes575@gmail.com
