### ISSUE TITLE
doc: missing localization for Ukrainian language

### ISSUE THREAD

**Issue by viktor-shepel** [westes/flex#227]
**Steps to reproduce:**
1. install clean unix box (Ubuntu 14.04 docker image have been used)
2. generate Ukrainian locale `sudo locale-gen uk_UA && sudo locale-gen uk_UA.UTF-8`
3. switch locale to one generated above `export LANGUAGE="uk_UA:uk"` and `export LANG=uk_UA.utf8`
4. execute `echo XXX | flex` and observe output

**Expected result:**
output should be in Ukrainian language
```bash
echo XXX | flex
<stdin>:1: неповне визначення імені
<stdin>:2: неочікуваний EOF
```

**Actual result:**
output is in English (default C locale) language
```bash
echo XXX | flex
<stdin>:1: incomplete name definition
<stdin>:2: premature EOF
```

proposed solution - https://github.com/westes/flex/pull/226

**Comment by westes** [comment]
As noted on the pull request, please submit the translation to the translation project.
