### ISSUE TITLE
add non-greedy regex logic

### ISSUE THREAD

**Issue by Alarty** [westes/flex#234]
Add to the syntax of flex, the '?' operator to allow non-greedy (lazy) regex possibilities.

**Comment by westes** [comment]
Is there an instance in the wild where this would be genuinely helpful?

**Comment by Alarty** [comment]
I had to catch some XML tags <text>...</text>
But in the same document we can have several text tags. And within the text tags we can have \n.
So the regex wanted is : \<text\>(.|\n)*?\<\/text\>
Because without the '?', if there is more than one text tag it catch the biggest instance possible.
With your non-greedy analyser, I had to do this awful regex : 
\<text\>([^\<]|\<[^\/]|\<\/[^t]|\<\/t[^e]|\<\/te[^x]|\<\/tex[^t]|\<\/text[^\>])*\<\/text\>

**Comment by westes** [comment]
For that case, you really want a parser.

On Monday,  3 July 2017,  7:06 am +0000, Aurelien Laviron <notifications@github.com> wrote:

> I had to catch some XML tags <text>...</text>
> But in the same document we can have several text tags. And within the text tags we can have \n.
> So the regex wanted is : \<text\>(.|\n)*?\<\/text\>
> Because without the '?', if there is more than one text tag it catch the biggest instance possible.
> With your non-greedy analyser, I had to do this awful regex : 
> \<text\>([^\<]|\<[^\/]|\<\/[^t]|\<\/t[^e]|\<\/te[^x]|\<\/tex[^t]|\<\/text[^\>])*\<\/text\> 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/234#issuecomment-312566081

-- 
Will Estes
westes575@gmail.com

**Comment by westes** [comment]
At the current time, I don't think this is criticial to the use case for flex. I'm not opposed to a pull request for it, but short of that, there are other things that need attention.
