### ISSUE TITLE
config-flex.c:(.text+0xf7c): undefined reference to lt_config_wrap

### ISSUE THREAD

**Issue by severach** [westes/flex#236]
As of flex 2.6.2 package [latrace](https://aur.archlinux.org/packages/latrace/) won't build.

**Comment by westes** [comment]
Is this true when building against flex 2.6.4?

On Saturday,  1 July 2017, 12:22 pm -0700, Chris Severance <notifications@github.com> wrote:

> As of flex 2.6.2 package [latrace](https://aur.archlinux.org/packages/latrace/) won't build. 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/236

-- 
Will Estes
westes575@gmail.com

**Comment by severach** [comment]
Same thing on 2.6.4.

**Comment by westes** [comment]
And where is the function you're missing supposed to come from? That sort of error is usuually from not passing the right link time flags.

**Comment by westes** [comment]
Ah, lookingf at the linked AUR page, there is a solution posted there. Note that the solution has nothing to do with flex. Closing as invalid.
