### ISSUE TITLE
[2.6.4/regression] out-of-source build fails with --disable-dependency-tracking when target platform requires malloc/realloc replacement

### ISSUE THREAD

**Issue by haubi** [westes/flex#244]
Combine these situations:
 - Use flex-2.6.4, where `lib/` contains only `malloc.c` and `realloc.c`, but no `Makefile` as in 2.6.3.
 - Build out-of-source, so `$top_builddir/lib/` does not exist before running `configure`.
 - Use `--disable-dependency-tracking` to render `config.status: executing depfiles commands` a no-op. This would create `.lib/.deps/*.Po` otherways.
 - Build for some target platform (like `AIX`) which requires (one of) the `malloc/realloc` replacements.
(To reproduce this on Linux, use `ac_cv_func_malloc_0_nonnull=no` instead.)

As a result, the build fails because `$top_builddir/lib/` does not exist:
```
$ mkdir -p /tmp/flex/build
$ cd /tmp/flex
$ gzip -dc flex-2.6.4.tar.gz | tar xf -
$ cd build
$ ac_cv_func_malloc_0_nonnull=no ../flex-2.6.4/configure --disable-dependency-tracking
...
checking for GNU libc compatible malloc... (cached) no
...
$ gmake
...
gcc -DHAVE_CONFIG_H -I. -I../../flex-2.6.4/src  -DLOCALEDIR=\"/usr/local/share/locale\"   -g -O2 -c -o ../lib/malloc.o ../../flex-2.6.4/src/../lib/malloc.c
Assembler messages:
Fatal error: can't create ../lib/malloc.o: No such file or directory
gmake[2]: *** [Makefile:790: ../lib/malloc.o] Error 1
gmake[2]: Leaving directory '/tmp/flex/build/src'
gmake[1]: *** [Makefile:546: all] Error 2
gmake[1]: Leaving directory '/tmp/flex/build/src'
gmake: *** [Makefile:533: all-recursive] Error 1
```
I'm unable to tell whether this should be fixed along the `malloc`/`realloc` integration into flex, within `gnulib` itself, within `flex/src/Makefile.am`, or within `configure.ac`.

Thanks!

**Comment by westes** [comment]
We have to be careful using stuff from gnulib since a lot of it is GPL and I am hazy on what exactly that would mean for flex's license.

What is the advantage of using --disable-dependency-tracking?

I would think that you want to ensure that all directories exist by the end of the configure run, so configure.ac would be the first place I'd try to fix this if I were you.

On Tuesday, 18 July 2017, 12:20 pm +0000, Michael Haubenwallner <notifications@github.com> wrote:

> Combine these situations:
>  - Use flex-2.6.4, where `lib/` contains only `malloc.c` and `realloc.c`, but no `Makefile` as in 2.6.3.
>  - Build out-of-source, so `$top_builddir/lib/` does not exist before running `configure`.
>  - Use `--disable-dependency-tracking` to render `config.status: executing depfiles commands` a no-op. This would create `.lib/.deps/*.Po` otherways.
>  - Build for some target platform (like `AIX`) which requires (one of) the `malloc/realloc` replacements.
> (To reproduce this on Linux, use `ac_cv_func_malloc_0_nonnull=no` instead.)
> 
> As a result, the build fails because `$top_builddir/lib/` does not exist:
> ```
> $ mkdir -p /tmp/flex/build
> $ cd /tmp/flex
> $ gzip -dc flex-2.6.4.tar.gz | tar xf -
> $ cd build
> $ ac_cv_func_malloc_0_nonnull=no ../flex-2.6.4/configure --disable-dependency-tracking
> ...
> checking for GNU libc compatible malloc... (cached) no
> ...
> $ gmake
> ...
> gcc -DHAVE_CONFIG_H -I. -I../../flex-2.6.4/src  -DLOCALEDIR=\"/usr/local/share/locale\"   -g -O2 -c -o ../lib/malloc.o ../../flex-2.6.4/src/../lib/malloc.c
> Assembler messages:
> Fatal error: can't create ../lib/malloc.o: No such file or directory
> gmake[2]: *** [Makefile:790: ../lib/malloc.o] Error 1
> gmake[2]: Leaving directory '/tmp/flex/build/src'
> gmake[1]: *** [Makefile:546: all] Error 2
> gmake[1]: Leaving directory '/tmp/flex/build/src'
> gmake: *** [Makefile:533: all-recursive] Error 1
> ```
> I'm unable to tell whether this should be fixed along the `malloc`/`realloc` integration into flex, within `gnulib` itself, within `flex/src/Makefile.am`, or within `configure.ac`.
> 
> Thanks!
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/244

-- 
Will Estes
westes575@gmail.com

**Comment by haubi** [comment]
Ah, when flex' malloc.c/realloc.c actually aren't from gnulib but flex-maintained, then forget about gnulib at all.

When building a distribution (either into binary packages or installing a source-based distro), package sources are built once, and both source- and build-dir are removed afterwards. In this case dependency tracking is pointless (as it is useful during development only), and disabling usually does improve build speed.

**Comment by Explorer09** [comment]
@haubi Did you try building without `--disable-dependency-tracking` ?
I personally will consider your problem as one of the peculiarities in Automake (I have caught two more already), and to be honest, I myself don't know how to fix.

The best way you can do is to revert the commit that caused this (259257623937630bb22cabf29f9897270aa62ce0), or tell us if you have found a better way.

**Comment by haubi** [comment]
Without `--disable-dependency-tracking`, the `lib` dir is created in builddir as side effect of
```
$ ./config.status src/Makefile depfiles
```
But wait, probably just found a simpler solution...

**Comment by haubi** [comment]
But using $(am__dirstamp) feels suspect, as it looks like an automake-internal...

**Comment by Explorer09** [comment]
@haubi 
1. What's wrong with `./config.status src/Makefile depfiles` creating the directory for you and work for your build? I don't understand.
2. Like I said before this problem or fault probably belongs to Automake. We have explicit AC_CONFIG_LIBOBJ_DIR in configure.ac, and Automake should be aware of it. And I expect Automake be clever enough to find out that any file in $LIBOBJS depends on $LIBOBJDIR created first, and if it doesn't it's a bug.

**Comment by westes** [comment]
@Explorer09 the issue is that for one time builds, dependency tracking is, by hypothesis, not necessary and slows down the build. So this is about performance at build time. It should work, but does not.

**Comment by haubi** [comment]
@Explorer09 Problem is that `./config.status src/Makefile depfiles` does **not** create the directory when `--disable-dependency-tracking` is active.
But indeed this feels like a bug with the AC_CONFIG_LIBOBJ_DIR autoconf macro - patch forwarded to http://lists.gnu.org/archive/html/autoconf-patches/2017-07/msg00002.html.

**Comment by westes** [comment]
That still leaves the question of what to do until the next autoconf release happens though -- and that may not be for a while, given how infrequently they do releases.

On Thursday, 20 July 2017,  1:06 pm +0000, Michael Haubenwallner <notifications@github.com> wrote:

> @Explorer09 Problem is that `./config.status src/Makefile depfiles` does **not** create the directory when `--disable-dependency-tracking` is active.
> But indeed this feels like a bug with the AC_CONFIG_LIBOBJ_DIR autoconf macro - patch forwarded to http://lists.gnu.org/archive/html/autoconf-patches/2017-07/msg00002.html.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/244#issuecomment-316696981

-- 
Will Estes
westes575@gmail.com

**Comment by Explorer09** [comment]
@haubi 
I think the patch you submitted to Autoconf is incorrect. The libobjdir should be created in the make phase, in other words it's an Automake bug, not Autoconf bug.
I think #246 you suggest is the right way (except for the am__dirstamp that I don't know what it does) -- perhaps you can bring that to Automake mailing list.

**Comment by haubi** [comment]
Problem forwarded to automake: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=27781
