### ISSUE TITLE
rpl_* functions and config.h/stdlib.h interations causes segfault with modern GCC

### ISSUE THREAD

**Issue by hobbitalastair** [westes/flex#247]
I'm cross-compiling flex 2.6.4, which used to work fine with GCC 6.2.1. However, building with GCC 7.1.1 fails, with `stage1flex` segfaulting. This is caused by `scan.c` and `stage1flex.c` including `flexdef.h` (which includes `config.h`) after `stdlib.h`, which in turn causes `rpl_malloc` and `rpl_realloc` to be used without a prototype. In GCC 6.2.1 this causes warnings (which I missed earlier, sorry about that) and in GCC 7.1.1 it causes a segfault when running `stage1flex` during the build.

The way to avoid this would be to ensure that `stage1flex.c` and `scan.c` include `config.h` before `stdlib.h`, however I'm not sure how best to integrate that with the existing system since the problematic include comes from a file generated by the system's flex.

**Comment by westes** [comment]
I'll have to sort what the right answer is, but the compiler segfaulting is always a bug, so be sure and report that there.

On Sunday, 23 July 2017,  2:49 pm -0700, Alastair Hughes <notifications@github.com> wrote:

> I'm cross-compiling flex 2.6.4, which used to work fine with GCC 6.2.1. However, building with GCC 7.1.1 fails, with stage1flex segfaulting. This is caused by `scan.c` and `stage1flex.c` including `flexdef.h` (which includes `config.h`) after `stdlib.h`, which in turn causes `rpl_malloc` and `rpl_realloc` to be used without a prototype. In GCC 6.2.1 this causes warnings (which I missed earlier, sorry about that) and in GCC 7.1.1 it causes a segfault when running `stage1flex` during the build.
> 
> The way to avoid this would be to ensure that `stage1flex.c` and `scan.c` include `config.h` before `stdlib.h`, however I'm not sure how best to integrate that with the existing system since the problematic include comes from `flex.skl`.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/247

-- 
Will Estes
westes575@gmail.com

**Comment by hobbitalastair** [comment]
@westes it is the built `stage1flex` binary which segfaults, not GCC (kind of like in #219 but with a different backtrace). I suspect it worked largely by accident with GCC 6.2.1, and GCC 7.1.1 moved things around enough to cause things to actually break.

**Comment by westes** [comment]
Ack, sorry for the misread then!

On Sunday, 23 July 2017,  9:58 pm +0000, Alastair Hughes <notifications@github.com> wrote:

> @westes it is the built `stage1flex` binary which segfaults, not GCC (kind of like in #219 but with a different backtrace). I suspect it worked largely by accident with GCC 6.2.1, and GCC 7.1.1 moved things around enough to cause things to actually break.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/247#issuecomment-317285184

-- 
Will Estes
westes575@gmail.com

**Comment by hobbitalastair** [comment]
Looking at this again, it seems that there are three options:

- Use a different skeleton when generating `scan.c` and `stage1flex.c` which includes `config.h`. I'm not sure how to do this (how do I generate a new skeleton, and what from?).
- Always include `config.h` if the appropriate define is added. This might cause problems for programs where this is unexpected, although I'm tempted to say that it also might fix them not cross compiling properly under autotools. It would also involve using a different skeleton or updated system flex to bootstrap, which is messy but certainly doable.
- Add a rule in the makefile to generate scan.c and them prepend it with the include for `config.h`. Seems easiest, but rather hacky.

@westes What are your thoughts on the approach I should be taking?

**Comment by westes** [comment]
> - Use a different skeleton when generating `scan.c` and `stage1flex.c` which includes `config.h`. I'm not sure how to do this (how do I generate a new skeleton, and what from?).

Flex does have the -S option. That being said, we want flex to bootstrap from the skeleton that users of flex will use, so you'd still have to autogenerate the building-flex skeleton from the using-flex skeleton by prepending the include line.

> - Always include `config.h` if the appropriate define is added. This might cause problems for programs where this is unexpected, although I'm tempted to say that it also might fix them not cross compiling properly under autotools. It would also involve using a different skeleton or updated system flex to bootstrap, which is messy but certainly doable.

We can't always guarantee that config.h is the file of includes from an autoconf generated run of configure. Although perhaps that case doesn't exist in the wild?

The two skeletons would be different by the inclusion of the header and nothing else...

> - Add a rule in the makefile to generate scan.c and them prepend it with the include for `config.h`. Seems easiest, but rather hacky.

I like easy, although it is something of a kludge, but then we're bootstrapping flex. The test suite has all manner of things that make automake jump through hoops just so we can do odd things to flex itself. So let's try this and see how it goes.

That make sense?
