### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by Stephen-Grant-Brown** [westes/flex#280]
Hi All,
I was hoping to use the examples in the flex source code to get my first (well your's) flex 
code running but "make -f Makefile.examples expr" but ld says "cannot find -ll". 
Neither can I.
Where is it?
Any help will be gratefully accepted.
Stephen Grant brown

**Comment by westes** [comment]
"make -f Makefile.examples expr"

What version of flex are you using?

What did you do before the quoted line? I'm not sure where "Makefile.examples" would have come from. If the linker can't find its libraries, there's probably something wrong in your setupm or you perhaps have libfl, not libl and whatever Makefile you're using doesn't know that.

On Monday, 30 October 2017, 10:03 pm +0000, Stephen-Grant-Brown <notifications@github.com> wrote:

> Hi All,
> I was hoping to use the examples in the flex source code to get my first (well your's) flex 
> code running but "make -f Makefile.examples expr" but ld says "cannot find -ll". 
> Neither can I.
> Where is it?
> Any help will be gratefully accepted.
> Stephen Grant brown
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/280

-- 
Will Estes
westes575@gmail.com

**Comment by westes** [comment]
Looks like your reply did not come through properly. Retry?
