### ISSUE TITLE
The line and character counter example doesn't work

### ISSUE THREAD

**Issue by mytbk** [westes/flex#281]
```
        int num_lines = 0, num_chars = 0;

%%
\n      ++num_lines; ++num_chars;
.       ++num_chars;

%%

int main()
        {
        yylex();
        printf( "# of lines = %d, # of chars = %d\n",
               num_lines, num_chars );
       }
```

but after I save it to counter.l and ``flex counter.l``, the generated lex.yy.c doesn't have the num_lines and num_chars declaration, so it cannot be compiled.

**Comment by mytbk** [comment]
I've just seen the next example and I know how to write this now, the code before the first ``%%`` should be:

```
%{
int num_lines = 0, num_chars = 0;
%}
```

**Comment by hkrept** [comment]
Maybe you also need add
`int yywrap()
{
    return 1;
}`
to the end. I don't know why, but I can run the out file only after I do this.

**Comment by jannick0** [comment]
@mytbk: I cannot reproduce the compilation error of your first example. Is the declaration line indented in your first example whose c file failed to be compiled? At least one leading blank on this line is needed to make flex copy the line to the c file. Enclosing it in `%{ ... %}` has the same effect as you have discovered a bit later (no indentation needed then).

**Comment by mytbk** [comment]
@jannick0 Oh, I didn't add the leading blanks.
