### ISSUE TITLE
File open error message lacks strerror(errno)

### ISSUE THREAD

**Issue by Explorer09** [westes/flex#288]
This is a minor usability bug that might be easy to fix but I'm not sure how to
do it at the moment.

When Flex fails to open a file, a "can't open" error is displayed, but it lacks
errno messages to help user further know what happened. Can't open because file
doesn't exist? Or because of permission denied? It's hard to tell.

```
$ flex not-exist
flex: can't open not-exist
```

Compare with bison and gcc, which do display errno messages:

```
$ gcc not-exist
gcc: error: not-exist: No such file or directory
gcc: fatal error: no input files
compilation terminated.
$ bison not-exist
bison: not-exist: cannot open: No such file or directory
```

**Comment by rmccullagh** [comment]
I'll take this one

**Comment by rmccullagh** [comment]
Please assign me to the issue.

**Comment by westes** [comment]
@rmccullagh just open a pull request. Since this is a personal repository, github is pedanticly unhelpful about letting me assign issues to people.
