### ISSUE TITLE
add declaration of yylex to header file

### ISSUE THREAD

**Issue by jannick0** [westes/flex#293]
Given a flex configuration, that would help to avoid any manual declaration of `yylex` (when used, e.g., in by bison/yacc) by simply `#include`ing the flex header file.

Example - The following declaration block is part of the scanner file induced by flex' `%option bison-bridge`. A part of that could go to the header file.
```
/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param );

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param )
#endif /* !YY_DECL */
```

**Comment by Explorer09** [comment]
Do you mean that the prepocessor block you mentioned should be copied to the header?

**Comment by jannick0** [comment]
Yes, exactly. That would help `flex` adjust the declaration of `yylex` based on the very `flex` options.

**Comment by jannick0** [comment]
Already implemented.
