### ISSUE TITLE
Problem with prefix option in 2.6.4.

### ISSUE THREAD

**Issue by skrah** [westes/flex#306]
The prefix option does not seem to work for https://github.com/plures/ndtypes with flex-2.6.4:

```
$ flex --version
flex 2.6.4
```

```
...
bison -Wall -o bpgrammar.c -pbp --defines=bpgrammar.h bpgrammar.y
flex -o bplexer.c -Pbp --header-file=bplexer.h bplexer.l
...
```

Flex version 2.5.35 works,  but 2.6.4 does not rewrite everything (example):

```
diff -u bplexer-2.5.35.c bplexer-2.6.4.c
```

```
-#undef bpalloc
-#undef bprealloc
-#undef bpfree
+#undef yyalloc
+#undef yyrealloc
+#undef yyfree

 void *
-bpalloc(size_t size,yyscan_t yyscanner)
+yyalloc(size_t size, yyscan_t yyscanner)
 {
     (void)yyscanner;

@@ -582,7 +803,7 @@
 }
```

**Comment by jannick0** [comment]
Would it help if `bpalloc` and friends are undefined instead of `yyalloc` etc.?

**Comment by skrah** [comment]
Thanks, removing the undefs works!

I think I accidentally left them in after discovering the "noyyalloc noyyrealloc noyyfree" options and flex<=2.6.1 somehow managed to handle it, but of course they don't make sense.
