### ISSUE TITLE
duplicate definition of INT8_MAX in Visual Studio 2015

### ISSUE THREAD

**Issue by mathstuf** [westes/flex#307]
In generated source files, [this block](https://github.com/westes/flex/blob/master/src/flexint.h#L32) is done after including `inttypes.h`, however at least on Visual Studio 2015, these are defined by `stdint.h` which is included later in the file causing redefinition warnings.

**Comment by mathstuf** [comment]
Cc: @mathturtle

**Comment by jannick0** [comment]
Would defining `YY_NO_UNISTD_H` help, e.g. `cl /DYY_NO_UNISTD_H lex.yy.c`? Then the compiler would ignore the flex int definitions.

**Comment by Explorer09** [comment]
This is not flex's fault. `inttypes.h` should contain the definitions of `stdint.h`, and if including `stdint.h` after `inttypes.h` would cause redefinition warnings, then fix the headers in your environment.
The definitions you pointed in `flexint.h` are all conditionally done, and are expected to be included _after_ `inttypes.h` or `stdint.h`, you get warnings only if you include in the wrong order.

**Comment by mathstuf** [comment]
Hrm, indeed. I'll look into the cause for the warning more. Maybe Visual Studio is not following the standard or `stdint.h` does different things based on whether other `#define`'s are set and adds these definitions.

**Comment by mathstuf** [comment]
OK, so I read the code wrong, `inttypes.h` is only included after checking `__STDC_VERSION__`. If not, `INT8_MIN` is defined unconditionally even though it may be in `stdint.h`. So it sounds like before trying to define the min/max macros, `stdint.h` should be included first.

**Comment by mathstuf** [comment]
Note that VS 2013 does *not* implement C99, so it doesn't set a suitable `__STDC_VERSION__`.

**Comment by Explorer09** [comment]
Just for another info, VS 2013 has `<inttypes.h>` in addition to `<stdint.h>`, it's just not included in the flex scanner because of the absence of `__STDC_VERSION__`macro.

**Comment by westes** [comment]
Fixed by #309.
