### ISSUE TITLE
stage1flex is failed

### ISSUE THREAD

**Issue by protonesso** [westes/flex#310]
I using GCC 7.3.0 and I have problems with compilation, there is out:
`./stage1flex   -o stage1scan.c ./scan.l
Makefile:1696: recipe for target 'stage1scan.c' failed
make[2]: *** [stage1scan.c] Segmentation fault
make[2]: Leaving directory '/home/tux/janus/build/sources/flex-2.6.4/src'
Makefile:546: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/tux/janus/build/sources/flex-2.6.4/src'
Makefile:533: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
`

**Comment by westes** [comment]
Can you provide additional debug output?

On Sunday,  4 February 2018, 12:04 pm +0000, SuperDuperHacker <notifications@github.com> wrote:

> I using GCC 7.3.0 and I have problems with compilation, there is out:
> `./stage1flex   -o stage1scan.c ./scan.l
> Makefile:1696: recipe for target 'stage1scan.c' failed
> make[2]: *** [stage1scan.c] Segmentation fault
> make[2]: Leaving directory '/home/tux/janus/build/sources/flex-2.6.4/src'
> Makefile:546: recipe for target 'all' failed
> make[1]: *** [all] Error 2
> make[1]: Leaving directory '/home/tux/janus/build/sources/flex-2.6.4/src'
> Makefile:533: recipe for target 'all-recursive' failed
> make: *** [all-recursive] Error 1
> `
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/310

-- 
Will Estes
westes575@gmail.com

**Comment by protonesso** [comment]
i fixed this issue

**Comment by jiamingzai** [comment]
How to fix this?

**Comment by westes** [comment]
@protonesso did you do something in particular to fix the issue? If so, can you explain what you did or submit a pull request with your changes?

**Comment by protonesso** [comment]
`ac_cv_func_malloc_0_nonnull=yes
ac_cv_func_realloc_0_nonnull=yes` to config cache or `ac_cv_func_malloc_0_nonnull=yes \
ac_cv_func_realloc_0_nonnull=yes \
./configure \
*ur config*`

**Comment by jiamingzai** [comment]
I explorted the two parameters that you mentioned above both in shell and configure file , and `./configure && make` againt. But the segfault issuse is still unsolved.

**Comment by protonesso** [comment]
But I had issuses with musl libc

**Comment by codeezer** [comment]
Hey,
I got the same error and tried the solution ghost mentioned but it didn't work for me.


make  all-am
make[2]: Entering directory '/home/ezer/Documents/research/flex-2.6.4/src'
./stage1flex   -o stage1scan.c ./scan.l
Makefile:1696: recipe for target 'stage1scan.c' failed
make[2]: *** [stage1scan.c] Segmentation fault (core dumped)
make[2]: Leaving directory '/home/ezer/Documents/research/flex-2.6.4/src'
Makefile:546: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/ezer/Documents/research/flex-2.6.4/src'
Makefile:534: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by wq807319473** [comment]
> : recipe for target 'stage1scan.c' failed

The same problem as you.

How to solve this problem?
