### ISSUE TITLE
Travis CI failures on gpg keyserver error

### ISSUE THREAD

**Issue by Explorer09** [westes/flex#311]
Travis CI build system (as used in flex) can fail when a GPG key is not found in a keyserver.
However it should not fail because the fault is not with the developers / patch submitters, and it would be confusing when a red X is suddenly shown in GitHub's pull request, (For a fault that truly isn't theirs.)

**Comment by westes** [comment]
So the solution is to include the gpg keys in the travis build setup. Could you submit a pull request to do that for the existing scripts?

**Comment by Explorer09** [comment]
For future reference, these two are examples of build server failures simply caused by GPG server fail:
https://travis-ci.org/westes/flex/jobs/335672015
https://travis-ci.org/westes/flex/jobs/338037463
