### ISSUE TITLE
Please to make a release?

### ISSUE THREAD

**Issue by bukzor** [westes/flex#312]
I'd like to push the fix for #241 downstream, as it's biting me and others, but there's no release which includes the necessary patch (https://github.com/westes/flex/pull/262/commits/c5a26b1).

Here's a list of packagers that are working around the issue while they wait for a release:

- https://github.com/NetBSD/pkgsrc/commit/e36e1ff77a719778189932102fb06898b9153add
- https://github.com/ruslo/hunter/pull/1119
- https://github.com/hluk/CopyQ/issues/840#issuecomment-352388742
- https://git.busybox.net/buildroot/commit/?id=c128c5f3c79b31d89256ffbc5c650ba613d3d52b
- https://patchwork.ozlabs.org/patch/817838/

**Comment by westes** [comment]
Plenty of folks include patched sources in a variety of ways. Some people use the upstream release and add their patches on top of that. Some release the sources with patches applied.

Is there something stopping you from providing the product you wish to provide to your users/customers?

Alternatively, I haven't set up the infrastructure to allow easy sponsorship of flex work, but if you're offering to improvise something with me to free up my time to do a release sooner than I had planned on doing that, please contact me privately with the details of what you're proposing.

**Comment by bukzor** [comment]
Those patches reflect work already committed to master (in c5a26b1), and all of them mention "should be fixed in next release" , each authored 3-5 months ago.

I'm just here to report that lack of a release is causing your downstreams pain, under the assumption that you're unaware. Also, I humbly request a release, to make my own plans easier.

If you're already aware, and don't plan to change your release schedule, you can close this as WAI :)

**Comment by westes** [comment]
Plenty of packaging formats permit the inclusion of patches against upstream sources.

Is there something preventing you from doing that?

There is no schedule as such for flex releases; instead it is my availability to do the work that determines when that happens.

If you are proposing to help with those arrangements, feel free to contact me privately to discuss the details of what you have in mind.

**Comment by bukzor** [comment]
Latest release is 88 commits and 15 months behind master.

https://github.com/westes/flex/compare/v2.6.4...master
