### ISSUE TITLE
build: clean not removing compiled files (e.g. skel.c)

### ISSUE THREAD

**Issue by jannick0** [westes/flex#350]
`make clean` appears to leave `skel.c`, `y.tab.h` and probably others untouched which might cause confusion when rebuilding.

Not sure if this snip from src/makefile is the culprit which I could not figure out have this is built:
```make
distclean-compile:
	-rm -f *.tab.c
```

**Comment by westes** [comment]
That is the correct behavior.



On Sunday, 22 April 2018,  4:27 pm +0000, jannick0 <notifications@github.com> wrote:

> `make clean` appears to leave `skel.c`, `y.tab.h` and probably others untouched which might cause confusion when rebuilding.
> 
> Not sure if this snip from src/makefile is the culprit which I could not figure out have this is built:
> ```make
> distclean-compile:
> 	-rm -f *.tab.c
> ```
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/350

-- 
Will Estes
westes575@gmail.com
