### ISSUE TITLE
lex/bison compiling error after ubuntu 18.04 upgrade

### ISSUE THREAD

**Issue by gaaloe** [westes/flex#359]
There is something wrong with flex when using Ubuntu 18.04. I am not shure what it is, but I have discovered that the built-in flex main()-routine is part of the problem. Since I am not using the built-in main() in my code, I removed (and destroyed) a symbol inside, and then the problem went away:
diff --git a/src/libmain.c b/src/libmain.c
index bb2fe35..b9df2cc 100644
--- a/src/libmain.c
+++ b/src/libmain.c
@@ -23,14 +23,12 @@
 
 #include <stdlib.h>
 
-extern int yylex (void);
-
 int     main (int argc, char *argv[])
 {
        (void)argc;
        (void)argv;
 
-       while (yylex () != 0) ;
+       while (0 != 0) ;
 
        exit(0);
 }

Google on "lex/bison compiling error after ubuntu 18.04 upgrade" to see a guy discovering the same problem as I see.

**Comment by westes** [comment]
- What version of flex?

- What is a minimal lexer file that reproduces the problem?

- What are you doing to compile?

**Comment by gaaloe** [comment]
It has already taken me several hours to come up with the tiny information I have provided, and now I must spend a lot more? It is the latest version of everything, gcc, Ubuntu and flex. The source code in question is at least 20 years old, I have successfully kept it updated from linux to linux over the years. I will reappear with what you ask for, sooner or later.

**Comment by westes** [comment]
I don't know what you did to produce the error, so I can't troubleshoot it.

To find out the version of flex, you can run:

flex --version

I don't have an Ubuntu 18.04 system to hand, so I don't know what version of flex got included in it. Nor do I know what changes you may have added to the system in question.

Nor do I know what scanner you used that caused the error.

On Friday, 25 May 2018, 10:38 am -0700, gaaloe <notifications@github.com> wrote:

> It has already taken me several hours to come up with the tiny information I have provided, and now I must spend a lot more? It is the latest version of everything, gcc, Ubuntu and flex. The source code in question is at least 20 years old, I have successfully kept it updated from linux to linux over the years. I will reappear with what you ask for, sooner or later.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/359#issuecomment-392129864

-- 
Will Estes
westes575@gmail.com

**Comment by gaaloe** [comment]
The bug is apparent when using g++ 7.3.0 and linker 2.30, flex 2.6.4 (Ubuntu 18.04).
It is not a bug using g++ 7.2.0 and linker 2.29.1, flex 2.6.1 (Ubuntu 17.10).
The minimal (?) lexer/yaccer, four files:

henrik@PrinsAugust:~/my_hellex$ cat hello.l
%{

  #include "y.tab.h"
  int yyerror(char *errormsg);

%}
  
%%

("hi"|"oi")"\n"       { return HI;  }
("tchau"|"bye")"\n"   { return BYE; }
[-[]+.,><]            { return yytext[0]; }
.                     { yyerror("Unknow char");  }

%%

henrik@PrinsAugust:~/my_hellex$ cat hello.y
%{

  #include <stdio.h>
  #include <stdlib.h>
  int yylex(void);
  extern "C" int yyerror(const char *s);

%}

%token HI BYE

%%

program:
         hi bye
        ;

hi:
        HI     { printf("Hello World\n");   }
        ;
bye:
        BYE    { printf("Bye World\n"); exit(0); }
         ;

henrik@PrinsAugust:~/my_hellex$ cat libmain.c 
#include "y.tab.h"
#include <stdio.h>
int main(void)
{
     yyparse();
     return 0;
}

int yywrap(void)
{
     return 0;
}

int yyerror(char *errormsg)
{
      fprintf(stderr, "%s\n", errormsg);
}

henrik@PrinsAugust:~/my_hellex$ cat readme.txt 
flex hello.l
bison -dy hello.y
g++ -Wno-write-strings libmain.c lex.yy.c y.tab.c -ly -lfl -o hello.exe

The error will appear during the linking stage. It is the "yylex" symbol inside the libfl.a or its share object counterpart that cause the trouble.
Quick-fix: If I remove the "-lfl" and replace it with "-ll" the error will go away! I do not use anything from libfl.a that is not there in libl.a as it happens.

**Comment by Explorer09** [comment]
@gaaloe 
1. We have no control over how downstream (Linux distributions) package our software, so stating the distribution version is not helpful for us to diagnose the problem. You should reproduce the problem in our (upstream) version instead.
2. The conflict with main() definition in libfl is expected, since [POSIX lex](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/lex.html) specifies a main() function in libl, and libfl do so for compatibility. For your use case, just avoid the `-lfl` or `-ll` flags altogether and supply your own main() and yywrap() functions. Will that help?

**Comment by gaaloe** [comment]
I can manage using libl.a instead of libfl.a since I only use yywrap() from it. But the more people start using Ubuntu 18.04, the more issues this linker error in libfl.a will cause. Only some of them will be able to use libl.a as I can. I suggest someone get a machine with Ubuntu 18.04 distribution ASAP and experience the issue. Regarding the expected 2) issue, that situation is what ranlib(1) shall take care of and allow internal references within a lib.

**Comment by westes** [comment]
Is there a reason you're not using %option nomain?

On Saturday, 26 May 2018,  7:36 am -0700, gaaloe <notifications@github.com> wrote:

> I can manage using libl.a instead of libfl.a since I only use yywrap() from it. But the more people start using Ubuntu 18.04, the more issues this linker error in libfl.a will cause. Only some of them will be able to use libl.a as I can. I suggest someone get a machine with Ubuntu 18.04 distribution ASAP and experience the issue. Regarding the expected 2) issue, that situation is what ranlib(1) shall take care of and allow internal references within a lib.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/359#issuecomment-392265507

-- 
Will Estes
westes575@gmail.com

**Comment by Explorer09** [comment]
@gaaloe And excuse me, where is the libl.a you are talking about? From another implementation of lex? If so, which implementation?

**Comment by gaaloe** [comment]
Reporting an issue in this forum is like opening a can of worms! Ubuntu 18.10 will be out before this is finalized. Now I have to scrutinize the linking phase:
libll.a is only a symbolic link to static library libfl.a, probably installed by the flex rpm(?). This was the original library name when the things were named yacc&lex, remember? By writing -ll instead of -lfl I also unexpectedly changed from dynamic to static binding, and the issue went away! The same effect is achieved using "-static -lfl", linking statically using library libfl.a. So the issue in the original post appears when linking dynamically using libfl.so.2.0.0, the default way, using the newest Ubuntu, flex, g++ and ld-linker.
Regarding the %option, I have not actively used flex for decades, I just maintain some of my old code between Ubuntu releases. So if something is wrong in my *.l files, it has been wrong for decades. The snippet above was just yanked from GitLab hellex, and hellex uses the internal main(), but I changed that to external for my sample.

**Comment by Explorer09** [comment]
@gaaloe

We have been politely saying that we can't handle problems caused by distributions. So you should either report to the distribution first, or try reproducing the bug in our version.

It seems that you didn't build Flex by yourself. You only use libfl bundled by the distribution, hence we can't help solve your problem _directly_.

Sorry, but this is your first offense (please report to distribution before reporting here).

I have a brief idea of what caused the problem you are facing (making `main` a weak symbol in `libfl` would probably solve it), but as the fix would be too specific to your case, I think I would reject the fix here, until a more general case appears that proves the need of fixing here.

@westes, What would you say?

**Comment by Explorer09** [comment]
@gaaloe Sorry to bother again, but I have to ask another question:
Was there any reason you compile a flex scanner with g++? If you compile a flex scanner with C++ compiler, linking with libfl.so which is compiled by a C compiler would guarantee to fail. (This is due to language difference -- Flex doesn't use `extern "C"` so yylex symbol will become [mangled](https://en.wikipedia.org/wiki/Name_mangling) when compiled in C++. This is not our bug.)

Perhaps you could look at this StackOverflow queston:
https://stackoverflow.com/questions/5521892/how-can-i-use-the-flex-lexical-scanner-generator-as-part-of-my-program

**Comment by westes** [comment]
I haven't seen anything wrong in flex in this report. As suggested, reporting this bug to the distribution would be more helpful for your case.

On Sunday, 27 May 2018,  2:00 am -0700, "Kang-Che Sung (宋岡哲)" <notifications@github.com> wrote:

> @gaaloe
> 
> We have been politely saying that we can't handle problems caused by distributions. So you should either report to the distribution first, or try reproducing the bug in our version.
> 
> It seems that you didn't build Flex by yourself. You only use libfl bundled by the distribution, hence we can't help solve your problem _directly_.
> 
> Sorry, but this is your first offense (please report to distribution before reporting here).
> 
> I have a brief idea of what caused the problem you are facing (making `main` a weak symbol in `libfl` would probably solve it), but as the fix would be too specific to your case, I think I would reject the fix here, until a more general case appears that proves the need of fixing here.
> 
> @westes, What would you say?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/359#issuecomment-392316274

-- 
Will Estes
westes575@gmail.com

**Comment by gaaloe** [comment]
I have a correction to my definitions now, based on the fact pointed out here that the C++ linkage may be causing the issue, so I added some explicit "C" linkage for yylex() to my definitions:
diff --git a/my_hellex/hello.l b/my_hellex/hello.l
index 245a438..b6c99e5 100644
--- a/my_hellex/hello.l
+++ b/my_hellex/hello.l
@@ -2,6 +2,7 @@
 
   #include "y.tab.h"
   int yyerror(char *errormsg);
+#define YY_DECL extern "C" int yylex(void)
 
 %}
   
diff --git a/my_hellex/hello.y b/my_hellex/hello.y
index fcf2414..558ba1a 100644
--- a/my_hellex/hello.y
+++ b/my_hellex/hello.y
@@ -2,7 +2,7 @@
 
   #include <stdio.h>
   #include <stdlib.h>
-  int yylex(void);
+  extern "C" int yylex(void);
   extern "C" int yyerror(const char *s);
 
 %}
----------------
This resolves my issue. Now the application can live for another decade hopefully. But the issues forum should be aware that this issue will pop up by others using Flex and C++. Before Ubuntu 18.04 the g++ and ld for shared objects were not so picky with the "C" linkage as they obviously are now. They are still not picky for static linkage, maybe that will change too someday.

**Comment by Explorer09** [comment]
@gaaloe Shared objects ought to be picky about the "C" linkage. It's not just Ubuntu. 
Although the existence of libfl.so might have contributed to the problem you face.

Failing to address the linkage when using Flex is a user problem. There's nothing we can fix in libfl side. A better solution is to use `%option nomain` or `%option noyywrap` in your scanner file and avoid linking with libfl altogether.

**Comment by gaaloe** [comment]
Actually you could: You could generate the "#ifdef __cplusplus ..." alternative standard stuff in the lex.yy.c file to match both C and C++:
#ifdef __cplusplus
extern "C" int yylex(void);
#else
extern int yylex(void);
#endif

**Comment by Explorer09** [comment]
@gaaloe
 
> ```
> #ifdef __cplusplus
> extern "C" int yylex(void);
> #else
> extern int yylex(void);
> #endif
> ```

That's redundant considering you can override the function name with YY_DECL macro in lex.yy.c. The generated scanner code is expected to be compiled by a C compiler, not C++, in order to link with libfl.
If you use C++ compiler, you already know what you are doing.

**Comment by gaaloe** [comment]
I almost knew what I was doing decades ago when I wrote this, but at that time I missed the unused (!) posix main() in the libfl.so trying to link downstream to my yylex() expecting "C" linkage.The ld up to now did not fuzz when I provided C++ linkage instead. Something in the distribution has changed, and "C" linkage must now be explicit, and you can provide it in lex.yy.c. Why hesitate? Other C++-users will fall in this trap and probably just toss the old flex code.

**Comment by Explorer09** [comment]
Assuming a "C" linkage would break users that expect C++ linkage for their yylex routine. Changing a default behavior for a minority of users would never be a good idea.

**Comment by westes** [comment]
Especially when mechanisms already exist to provide the right behavior.

On Tuesday, 29 May 2018,  2:22 am -0700, "Kang-Che Sung (宋岡哲)" <notifications@github.com> wrote:

> Assuming a "C" linkage would break users that expect C++ linkage for their yylex routine. Changing a default behavior for a minority of users would never be a good idea.
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/359#issuecomment-392710971

-- 
Will Estes
westes575@gmail.com

**Comment by Explorer09** [comment]
@gaaloe You should make a complete report on a problem, whenever you insist something is a bug. I find it tiring to read your descriptions and guess what caused the problem you mentioned.
* Most projects would require a bug reporter to state at least (1) steps to reproduce, (2) expected result, and (3) actual result, with as much detail as possible. You should do the same, as saying “it doesn't work”  can't help anything. You did not mention any error message (actual result) or your expected result.
* Don't just state the distribution version! Please at least state the linker and compiler versions inside your distribution, since we definitely have no time to install a distro just to test your problem. Stating gcc and ld versions can save our time as we can look up upstream changes on the Web, hence help solve the problem faster.

**Comment by zakaria-amghare** [comment]
Hi everyone,
I'm using Xubuntu and trying to work with Flex and Bison, but I'm running into an issue during compilation. Here's what I'm doing:

1. I created a .lex file and a .y file.


2. I used Flex and Bison to generate the corresponding C files.


3. When I try to compile them using gcc, I get the following error:


***

:~/Desktop/testc$ gcc lex.yy.c test.tab.c -o test -L/usr/lib -lfl
test.tab.c: In function ‘yyparse’:
test.tab.c:963:16: warning: implicit declaration of function ‘yylex’ [-Wimplicit-function-declaration]
  963 |       yychar = yylex ();
      |                ^~~~~
test.tab.c:1104:7: warning: implicit declaration of function ‘yyerror’; did you mean ‘yyerrok’? [-Wimplicit-function-declaration]
 1104 |       yyerror (YY_("syntax error"));
      |       ^~~~~~~
      |       yyerrok
/usr/bin/ld: /tmp/ccNKkczB.o: in function `yyparse':
test.tab.c:(.text+0x66e): undefined reference to `yyerror'
/usr/bin/ld: test.tab.c:(.text+0x805): undefined reference to `yyerror'
collect2: error: ld returned 1 exit status

***
Does anyone know what could be causing this issue? I'm using [insert your version of Flex, Bison, and GCC. Any help would be appreciated!

Thanks in advance!

**Comment by Mightyjo** [comment]
I think we can help, but can you do me a favor?

Please start a new issue for this question. Otherwise it won't appear in
the tracking list when we try to follow up.

When you make the new issue, please include the flex command line and
options you used. Please include your flex version number, too.

**Comment by zakaria-amghare** [comment]
thank you so much for your effort may god bless you
please help me as soon as possible as i have dead line to submit my work
https://github.com/westes/flex/issues/687
