### ISSUE TITLE
./autogen.sh don't work in my ubuntu 16.04

### ISSUE THREAD

**Issue by Hanseltu** [westes/flex#362]
Hello, I just followed your step and run the command  `./autogen.sh` in the top level of the flex source tree in my X86_64 ubuntu16.04 machine. Then I got an error in my terminal. The information is "error: libtoolize not working, re-run with LIBTOOLIZE=/path/to/libtoolize   LIBTOOLIZE is currently "" ".

How can I fix the error? Thanks a lot.

**Comment by westes** [comment]
Do you have libtoolize installed?

On Friday,  8 June 2018,  7:45 pm -0700, thx <notifications@github.com> wrote:

> Hello, I just followed your step and run the command  `./autogen.sh` in the top level of the flex source tree in my X86_64 ubuntu16.04 machine. Then I got an error in my terminal. The information is "error: libtoolize not working, re-run with LIBTOOLIZE=/path/to/libtoolize   LIBTOOLIZE is currently "" ".
> 
> How can I fix the error? Thanks a lot.
> 
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/362

-- 
Will Estes
westes575@gmail.com

**Comment by Hanseltu** [comment]
Thanks, it works when I use the command `sudo apt-get install libtool m4 automake` & `sudo apt-get install autopoint` in my ubuntu.
