### ISSUE TITLE
Simple guide for download and use?

### ISSUE THREAD

**Issue by mmichelle** [westes/flex#366]
Just trying to get it installed. I see that the README mentions an Install folder. I just don't seem to be able to find it. I don't have a need to add/develop FLEX... just trying to use it. Is there a quick way to get it going without downloading a great number of tools? Maybe a tutorial on the Wiki page?

**Comment by westes** [comment]
What flex release did you download?

What commands did you issue?

What was the result of those commands?

**Comment by mmichelle** [comment]
I believe 2.6.2 (I’m not in front of the computer at the moment). I started to collect and setup the items recommended in the README such as bash, but I wondered if I really needed to go through all of that just to use FLEX. The README mentioned an INSTALL file or directory, but there didn’t appear to be one.

**Comment by westes** [comment]
It is not possible to provide guidance if you ...

- don't know what you downloaded.
- don't know what you did with what you downloaded.
- don't know what part of the directions you're unable to follow.

**Comment by mmichelle** [comment]
It was 2.6.4 from the releases. The README for this project “claims” that INSTALL has basic installation information, but there is NO INSTALL information other than a list of tools to help reach the point where one could theoretically build the maintainers repository. It would be nice if there really were basic instructions... at minimum, remove the reference to the non-existent INSTALL file. Thanks.
