### ISSUE TITLE
Segfault during build (on master)

### ISSUE THREAD

**Issue by jadr2ddude** [westes/flex#371]
I have experienced a similar error to others when building flex. However, on each of these it supposedly compiled on master. In this case it does not:

```
libtool: link: x86_64-pc-linux-musl-gcc -g -O2 -o stage1flex stage1flex-scan.o stage1flex-buf.o stage1flex-ccl.o stage1flex-dfa.o stage1flex-ecs.o stage1flex-filter.o stage1flex-gen.o stage1flex-main.o stage1flex-misc.o stage1flex-nfa.o stage1flex-options.o stage1flex-parse.o stage1flex-regex.o stage1flex-scanflags.o stage1flex-scanopt.o stage1flex-skel.o stage1flex-sym.o stage1flex-tables.o stage1flex-tables_shared.o stage1flex-tblcmp.o stage1flex-yylex.o /usr/lib/libintl.so /usr/lib/libc.so -Wl,-rpath -Wl,/usr/lib -lm
./stage1flex -o stage1scan.c ./scan.l
make[3]: *** [Makefile:1727: stage1scan.c] Segmentation fault (core dumped)
```

Important info:
* libc: musl
* compiler: gcc 7.2.0

This could potentially be due to compatability issues with musl.

**Comment by westes** [comment]
Have you tried with the same version of gcc but against glibc?

On Monday, 25 June 2018,  6:58 am -0700, Jaden Weiss <notifications@github.com> wrote:

> I have experienced a similar error to others when building flex. However, on each of these it supposedly compiled on master. In this case it does not:
> 
> ```
> libtool: link: x86_64-pc-linux-musl-gcc -g -O2 -o stage1flex stage1flex-scan.o stage1flex-buf.o stage1flex-ccl.o stage1flex-dfa.o stage1flex-ecs.o stage1flex-filter.o stage1flex-gen.o stage1flex-main.o stage1flex-misc.o stage1flex-nfa.o stage1flex-options.o stage1flex-parse.o stage1flex-regex.o stage1flex-scanflags.o stage1flex-scanopt.o stage1flex-skel.o stage1flex-sym.o stage1flex-tables.o stage1flex-tables_shared.o stage1flex-tblcmp.o stage1flex-yylex.o /usr/lib/libintl.so /usr/lib/libc.so -Wl,-rpath -Wl,/usr/lib -lm
> ./stage1flex -o stage1scan.c ./scan.l
> make[3]: *** [Makefile:1727: stage1scan.c] Segmentation fault (core dumped)
> ```
> 
> Important info:
> * libc: musl
> * compiler: gcc 7.2.0
> 
> This could potentially be due to compatability issues with musl.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/371

-- 
Will Estes
westes575@gmail.com

**Comment by westes** [comment]
It's possible that there are both gcc7 and musl issues

On Monday, 25 June 2018,  7:10 am -0700, Will Estes <notifications@github.com> wrote:

> Have you tried with the same version of gcc but against glibc?
> 
> On Monday, 25 June 2018,  6:58 am -0700, Jaden Weiss <notifications@github.com> wrote:
> 
> > I have experienced a similar error to others when building flex. However, on each of these it supposedly compiled on master. In this case it does not:
> > 
> > ```
> > libtool: link: x86_64-pc-linux-musl-gcc -g -O2 -o stage1flex stage1flex-scan.o stage1flex-buf.o stage1flex-ccl.o stage1flex-dfa.o stage1flex-ecs.o stage1flex-filter.o stage1flex-gen.o stage1flex-main.o stage1flex-misc.o stage1flex-nfa.o stage1flex-options.o stage1flex-parse.o stage1flex-regex.o stage1flex-scanflags.o stage1flex-scanopt.o stage1flex-skel.o stage1flex-sym.o stage1flex-tables.o stage1flex-tables_shared.o stage1flex-tblcmp.o stage1flex-yylex.o /usr/lib/libintl.so /usr/lib/libc.so -Wl,-rpath -Wl,/usr/lib -lm
> > ./stage1flex -o stage1scan.c ./scan.l
> > make[3]: *** [Makefile:1727: stage1scan.c] Segmentation fault (core dumped)
> > ```
> > 
> > Important info:
> > * libc: musl
> > * compiler: gcc 7.2.0
> > 
> > This could potentially be due to compatability issues with musl.
> > 
> > -- 
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/westes/flex/issues/371
> 
> -- 
> Will Estes
> westes575@gmail.com
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/371#issuecomment-399965567

-- 
Will Estes
westes575@gmail.com

**Comment by jadr2ddude** [comment]
I have just successfully compiled it in a ubuntu 18 container with the same version of GCC. Also this compiles fine with an older copy of GCC and with musl using alpine - [see here](https://build.projectpanux.com/log.html?buildHash=5c38e596086e9d2f919c3a4d3710ee36a7c64d5edb4bca4c4a782a6a23bc8c08).

Also, a link to the full failed build log: https://build.projectpanux.com/log.html?buildHash=801e229fdd54d0e5ddcd07d22b6c3f3769bb462c142842be2e2034f3fd7f8177

**Comment by westes** [comment]
Thanks for the additional builds and links.

On Monday, 25 June 2018,  3:52 pm +0000, Jaden Weiss <notifications@github.com> wrote:

> I have just successfully compiled it in a ubuntu 18 container with the same version of GCC. Also this compiles fine with an older copy of GCC and with musl using alpine - [see here](https://build.projectpanux.com/log.html?buildHash=5c38e596086e9d2f919c3a4d3710ee36a7c64d5edb4bca4c4a782a6a23bc8c08).
> 
> Also, a link to the full failed build log: https://build.projectpanux.com/log.html?buildHash=801e229fdd54d0e5ddcd07d22b6c3f3769bb462c142842be2e2034f3fd7f8177
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/371#issuecomment-400001363

-- 
Will Estes
westes575@gmail.com

**Comment by jadr2ddude** [comment]
@Explorer09 sorry had to shut the server down for maintanence. Now is back up.

**Comment by jadr2ddude** [comment]
also note: here is my build script
https://gitlab.com/panux/packages-main/blob/a321da25ae2f6e15737ed6899825aff582b7fadc/dev/flex/pkgen.yaml

**Comment by Explorer09** [comment]
@jadr2ddude 
Because I have no musl system to test, can you please help us by turning on more verbose output during the build, or give us a stage1flex binary that we can test it?
Specifically, can you specify "-T -v" in $LFLAGS?

**Comment by jadr2ddude** [comment]
Ok so another, weirder thing:
I re-created the build environment exactly and for some reason it built fine.

**Comment by jadr2ddude** [comment]
Ok so I successfully recreated the environment. With default configuration it works, with this configuration it does not. I am going to experiment to determine the problematic option.

**Comment by jadr2ddude** [comment]
The problematic option appears to be `--prefix=/usr`.

**Comment by jadr2ddude** [comment]
The issue occurs in [flex-regcomp at line 52](https://github.com/westes/flex/blob/98018e3f58d79e082216d406866942841d4bdf8a/src/regex.c#L52)

GDB info:
```
(gdb) print preg
$1 = (regex_t *) 0x6551a0 <regex_linedir>
(gdb) print regex
$2 = 0x42ad81 "^#line ([[:digit:]]+) \"(.*)\""
(gdb) print cflags
$3 = 1
(gdb) print *preg
$4 = {re_nsub = 0, __opaque = 0x0, __padding = {0x0, 0x0, 0x0, 0x0}, __nsub2 = 0, __padding2 = 0 '\000'}
```

**Comment by jadr2ddude** [comment]
Also, I packaged my build environment in a docker image. You can load it with:
```
sudo docker run --cap-add SYS_PTRACE --rm -it jadr2ddude/flextest
```

**Comment by Explorer09** [comment]
@jadr2ddude I finally reproduced using the docker image you provided.
Unfortunately, this doesn't seem to be flex's fault. The SIGSEGV happened in the free() routine called internally by regcomp(), which had some obscure problems with linkage.

Anyway, here's the workaround I found:
In the configured makefile, note the two variables
```
INTLLIBS = /usr/lib/libintl.so /usr/lib/libc.so -Wl,-rpath -Wl,/usr/lib
LIBINTL = /usr/lib/libintl.so /usr/lib/libc.so -Wl,-rpath -Wl,/usr/lib
```
Override them with:
```
INTLLIBS = /usr/lib/libintl.so -Wl,-rpath -Wl,/usr/lib
LIBINTL = /usr/lib/libintl.so -Wl,-rpath -Wl,/usr/lib
```
And then it would work.
I still had no idea why the "/usr/lib/libc.so" string came up in the aforementioned variables, though.

**Comment by jadr2ddude** [comment]
Ok yes, it appears to be a libintl issue. Thanks!

**Comment by Explorer09** [comment]
@jadr2ddude Did the workaround I mentioned work? By the way, I looked at the `readelf --dynamic` output of the linked stage1flex binaries (between which works and which does not). I think it would give a hint to you for looking deeper into the problem.

**Comment by jadr2ddude** [comment]
@Explorer09 I had removed the `--prefix=/usr` which appears to have removed the extra libc link option from INTLLIBS
