### ISSUE TITLE
GCC 7.3.0 warns about emitted code: potential null pointer dereference

### ISSUE THREAD

**Issue by akimd** [westes/flex#377]
I installed the following patch in Bison:

```diff
commit ef98967ada3c1cd48c177d7349e65a709bb49b97
Author: Akim Demaille <akim.demaille@gmail.com>
Date:   Wed Aug 15 13:49:01 2018 +0200

    build: work around GCC warnings on Flex code
    
    With GCC 7.3.0 and Flex 2.6.4, we get warnings on all the generated
    scanners:
    
        examples/calc++/calc++-scanner.cc: In function 'void yyrestart(FILE*)':
        examples/calc++/calc++-scanner.cc:1611:20: error: potential null pointer dereference [-Werror=null-dereference]
         /* %endif */
          ~~~~~~~~~~~       ^
        examples/calc++/calc++-scanner.cc:1607:19: error: potential null pointer dereference [-Werror=null-dereference]
         /* %if-c-only */
          ~~~~~~~~~~~~~~~  ^
        examples/calc++/calc++-scanner.cc:1611:20: error: potential null pointer dereference [-Werror=null-dereference]
         /* %endif */
          ~~~~~~~~~~~       ^
        examples/calc++/calc++-scanner.cc:1607:19: error: potential null pointer dereference [-Werror=null-dereference]
         /* %if-c-only */
          ~~~~~~~~~~~~~~~  ^
        cc1plus: all warnings being treated as errors
    
    Obviously the lines are incorrect, and the warnings are emitted twice.
    Still, let's get rid of these warnings.
    
    * doc/bison.texi, src/flex-scanner.h: Disable these warnings in code
    generated by Flex.

diff --git a/doc/bison.texi b/doc/bison.texi
index 9f16f730..2882506b 100644
--- a/doc/bison.texi
+++ b/doc/bison.texi
@@ -11399,6 +11399,12 @@ parser's to get the set of defined tokens.
 # undef yywrap
 # define yywrap() 1
 
+// Pacify warnings in yy_init_buffer (observed with Flex 2.6.4)
+// and GCC 7.3.0.
+#if defined __GNUC__ && 7 <= __GNUC__
+# pragma GCC diagnostic ignored "-Wnull-dereference"
+#endif
+
 // The location of the current token.
 static yy::location loc;
 %@}
diff --git a/src/flex-scanner.h b/src/flex-scanner.h
index 4dec7e1f..e09a1c04 100644
--- a/src/flex-scanner.h
+++ b/src/flex-scanner.h
@@ -44,6 +44,20 @@ int   FLEX_PREFIX (lex_destroy) (void);
 
 #define last_string    FLEX_PREFIX (last_string)
 
+// Pacify warnings in yy_init_buffer (observed with Flex 2.6.4 and GCC
+// 7.3.0).
+//
+// ./src/scan-skel.c: In function 'skel_restart':
+// ./src/scan-skel.c:2035:20: error: potential null pointer dereference [-Werror=null-dereference]
+//   b->yy_fill_buffer = 1;
+//   ~~~~~~~~~~~~~~~~~~^~~
+// ./src/scan-skel.c:2031:19: error: potential null pointer dereference [-Werror=null-dereference]
+//   b->yy_input_file = file;
+//   ~~~~~~~~~~~~~~~~~^~~~~~
+#if defined __GNUC__ && 7 <= __GNUC__
+# pragma GCC diagnostic ignored "-Wnull-dereference"
+#endif
+
 /* It seems to be a nice "feature" of Flex that one cannot use yytext,
    yyleng etc. when a prefix is given, since there is no longer a
    #define, but rather the token is actually changed in the output.
```

Cheers!

**Comment by Explorer09** [comment]
@akimd Why silence a warning? That didn't make sense. It's better to fix that. Null pointer dereference can have a potential security impact and it shouldn't be taken lightly.

By the way, can you please attach the generated scanner file and the source so that we can analyze that?

**Comment by baryluk** [comment]
Could you share a full generated source code to look at and see what the actual issue is? Silencing warning unconditionally for entire file is definitively a bad idea. You can achieve the same by changing your compiler flags.

**Comment by akimd** [comment]
Of course it's a bad idea and of course I don't want to.  What is needed is that the generated scanners do not generate any warnings at all (obviously I'm referring to the part left to Flex, not the user actions).  And no, I don't want to change the compiler flags because that would apply to the whole build, which is fine: only the generated scanners are not.

I'll post the scanner.  I'm sorry that the warnings in the original messages are not helping, but because of the off-by-one error in the emitted `#line` in the scanner, the compiler quotes incorrect lines.

Cheers.

**Comment by baryluk** [comment]
@akimd Most build systems I can think off allow you to specific extra flags for individual targets or subtrees, so no need to disable it for the whole build or project.

**Comment by akimd** [comment]
I agree, but to do so you have to check what compiler you are running, and what version.  It's by far simpler to embed these rules in the file itself, until Flex is fixed and you no longer have to deal with its problems.

**Comment by Explorer09** [comment]
@akimd 
The two lines that you hinted about the potential null pointer dereference...

    b->yy_fill_buffer = 1;
    b->yy_input_file = file;

... seems to be in the `yy_init_buffer` function of flex skeleton (flex.skl). Although the function seem to have the risks of null pointer dereference, I cannot reproduce the exact gcc warning/error message as you described. (gcc version 7.4.0 / Ubuntu 18.04.1) That's why we need your scanner codes to test out.

(I was thinking if adding `__attribute__((__nonnull__))` to the `yy_init_buffer` prototype would solve the problem, but I need to reproduce the problem first before thinking how to patch.)

**Comment by akimd** [comment]
@Explorer09 Thanks for looking into this, and sorry for taking so long: I was unable to reproduce it.  Until the CI (https://travis-ci.org/akimd/bison/builds/605888930) revealed a critical piece of information: compile the scanner with `-O3`.

It would be quite useless to post the generated scanner, as you need many headers to compile it and see the problem.  It's probably more useful for you to look at that commit (https://github.com/akimd/bison/commit/e0c057cbc0517ea0d3e517a438d9bdcee8193d5b), and check the corresponding tarball (https://www.lrde.epita.fr/~akim/private/bison/bison-3.4.1.259-e0c05-dirty.tar.xz) on your machine.  It's the usual procedure: `./configure && make`.

Cheers!

**Comment by Explorer09** [comment]
@akimd The usual `./configure && make` doesn't produce the warning. I read your Travis CI log and saw what happened. It's `./configure --enable-gcc-warnings CFLAGS=-O3` that would generate the warnings.

I think #431 would fix it.

**Comment by akimd** [comment]
@Explorer09 Oh sorry about that, I meant the general protocol.  `./configure CFLAGS="-O3 -Werror=null-dereference"` should also do.
Thanks for the patch, it looks perfect to me.

**Comment by andy5995** [comment]
I'm not sure how related this is, but I get a lot of warnings like

```
In function ‘yy_init_buffer’:
src/cmdlex.c:1605:19: warning: dereference of NULL ‘b’ [CWE-476] [-Wanalyzer-null-dereference]
 1605
```
when adding the `-fanalyzer` flag with gcc 10 and 11 when building [modemu2k](https://github.com/theimpossibleastronaut/modemu2k)

[deref-log.txt](https://github.com/westes/flex/files/6819145/deref-log.txt)

**Comment by Mightyjo** [comment]
It's related, but the warnings in your deref-log.txt should be fixed in HEAD. Please open a new issue if you still see this on the HEAD of master. There is still a macro that might be annoying GCC.

**Comment by andy5995** [comment]
Thanks @Mightyjo , the warnings did indeed go away when I used HEAD.
