### ISSUE TITLE
hard bison name dependency

### ISSUE THREAD

**Issue by GitMensch** [westes/flex#386]
The current configure.ac has:

AC_PROG_YACC

which leads to `configure --help` saying:

>   YACC        The `Yet Another Compiler Compiler' implementation to use. Defaults to the first program found out of: `bison -y', `byacc', `yacc'.

So far everything is fine, but then configure.ac borks it by:

```
AS_IF([test "$YACC" != 'bison -y'], [
	YACC="\${top_srcdir}/build-aux/missing bison -y"
	AC_MSG_NOTICE(no bison program found: only required for maintainers)
	])
AM_CONDITIONAL([HAVE_BISON], [test "$YACC" = 'bison -y'])
```

Which results in this branch as soon as somebody does something like
`../configure YACC=/mydir/bison -y`.

**Comment by westes** [comment]
Yup, the assumption is clearly that if bison is found it is found on the path. Which may not be the case. The test suite does very specifically require bison, however.

On Sunday, 16 September 2018,  7:22 am -0700, Simon Sobisch <notifications@github.com> wrote:

> The current configure.ac has:
> 
> AC_PROG_YACC
> 
> which leads to `configure --help` saying:
> 
> >   YACC        The `Yet Another Compiler Compiler' implementation to use. Defaults to the first program found out of: `bison -y', `byacc', `yacc'.
> 
> So far everything is fine, but then configure.ac borks it by:
> 
> ```
> AS_IF([test "$YACC" != 'bison -y'], [
> 	YACC="\${top_srcdir}/build-aux/missing bison -y"
> 	AC_MSG_NOTICE(no bison program found: only required for maintainers)
> 	])
> AM_CONDITIONAL([HAVE_BISON], [test "$YACC" = 'bison -y'])
> ```
> 
> Which results in this branch as soon as somebody does something like
> `../configure YACC=/mydir/bison -y`.
> 
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/386

-- 
Will Estes
westes575@gmail.com

**Comment by Explorer09** [comment]
What precise error do you get? Flex's own parser can only be regenerated by Bison and not other Yacc implementations. So the breakage was intentional.
It's not a problem if you build from a release tarball, as the parser code would be generated already there.

**Comment by GitMensch** [comment]
The error is that bison is not found.

Instead of checking for `bison -y` the test should be for `$YACC --version | $GREP -q 'GNU Bison'` evaluating to zero.

**Comment by westes** [comment]
So submit a pr for that, separately.

On Sunday, 16 September 2018,  7:49 am -0700, Simon Sobisch <notifications@github.com> wrote:

> The error is that bison is not found.
> 
> Instead of checking for `bison -y` the test should be for `$YACC --version | $GREP -q 'GNU Bison'` evaluating to zero.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/386#issuecomment-421777214

-- 
Will Estes
westes575@gmail.com

**Comment by GitMensch** [comment]
Checking further this is what the generated configure script uses in other places:

```sh
test -n "$STRIP" && $STRIP -V 2>&1 | $GREP "GNU strip" >/dev/null
```

Therefore I'll check if this works fine and do a PR with this.

**Comment by GitMensch** [comment]
While the [PR passes configure/make check][1] I've recognized that the `-y` parameter is always needed because of the way the ylwrap script works and the expected include names.
So I wonder if configure should auto-extend either `YACC` or `YFLAGS` with `-y`, to remove the need to be specified by the user (I've tested both to be working and none of my Bison binaries complained when `-y` was passed multiple times, so I tend to auto-add this to `YFLAGS`).
Opinions?

[1]:https://travis-ci.org/westes/flex/builds/429294045

**Comment by westes** [comment]
Honestly, if we insist on bison, then is there something in the autoconf archive that already does all that sort of thing for us?

On Sunday, 16 September 2018, 12:02 pm -0700, Simon Sobisch <notifications@github.com> wrote:

> While the [PR passes configure/make check][1] I've recognized that the `-y` parameter is always needed because of the way the ylwrap script works and the expected include names.
> So I wonder if configure should auto-extend either `YACC` or `YFLAGS` with `-y`, to remove the need to be specified by the user (I've tested both to be working and none of my Bison binaries complained when `-y` was passed multiple times, so I tend to auto-add this to `YFLAGS`).
> Opinions?
> 
> [1]:https://travis-ci.org/westes/flex/builds/429294045
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/386#issuecomment-421814109

-- 
Will Estes
westes575@gmail.com

**Comment by GitMensch** [comment]
https://www.gnu.org/software/autoconf-archive/ax_prog_bison.html looks reasonable and should be a drop-in-replacement for `AC_PROG_YACC`, but it changes the rules by explicit removing the POSIX yacc-compatibility and fixes ylwrap usage by specifying the posix output-name.
This would therefore theoretically allow flex's parser and the testuite parsers to use bison-only features.

Do you want me to add it to this PR?

**Comment by westes** [comment]
We need to make sure that it's license compatible, but this pr isn't going to get reviewed for a bit (I've got to make 2.6.5 and my life is too busy right now), so it's probably ok to do so.

On Sunday, 16 September 2018, 12:27 pm -0700, Simon Sobisch <notifications@github.com> wrote:

> https://www.gnu.org/software/autoconf-archive/ax_prog_bison.html looks reasonable and should be a drop-in-replacement for `AC_PROG_YACC`, but it changes the rules by explicit removing the POSIX yacc-compatibility and fixes ylwrap usage by specifying the posix output-name.
> This would therefore theoretically allow flex's parser and the testuite parsers to use bison-only features.
> 
> Do you want me to add it to this PR?
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/386#issuecomment-421817869

-- 
Will Estes
westes575@gmail.com

**Comment by GitMensch** [comment]
In this case I suggest to include the PR as is and come back to this later.
Using this PR we get:

* no change to the default behaviour
* *If* the users sets `YACC` manually we check for GNU Bison (the user just has to manually add `-y`, too; but earlier there was no chance to specify *anything*)
* ... nicer messages

**Comment by Explorer09** [comment]
@GitMensch, please, please, tell us how exactly the current configure script goes wrong, instead of opening a PR that no one know what you are fixing.
Give us reproduce step, what result you get that's considered incorrect, and what result is expected.
In other words, write a proper bug report for us. We should evaluate first if it's really a bug before you propose a fix for us.

**Comment by GitMensch** [comment]
> @GitMensch, please, please, tell us how exactly the current configure script goes wrong, instead of opening a PR that no one know what you are fixing.
Give us reproduce step, what result you get that's considered incorrect, and what result is expected.
In other words, write a proper bug report for us. We should evaluate first if it's really a bug before you propose a fix for us.

@Explorer09 I've already did this... in the first post:

> Which results in [configure showing "no bison program found: only required for maintainers"] as soon as somebody does uses `../configure YACC=/mydir/bison -y`.

It shouldn't matter if the user:

* wants to use a bison binary not in `$PATH`
* want to use a shell script wrapper `bison.sh` (which sets the data dir and actually may be needed when using a self-build not-yet-installed bison)
* specifies an unexpected executable name

The only prerequisite you have is: it must be bison.
And that is exactly what the PR fixes.

It is a bug to throw away what the user specifies (according to `configure --help`!) because it does not exactly match some standard value (which is... exactly the purpose of the YACC variable).
Side note: There are systems where `YACC` is actually set in the environment (obviously not to `bison -y`), I did not tested this but likely this will also lead to "bison not found".

**Comment by Explorer09** [comment]
@GitMensch 
Did you add single quotes around the YACC argument when invoking configure?
Like this: `../configure YACC='/mydir/bison -y'`

It matters. That's why I requested detailed steps to reproduce.
If the invocation I mentioned works, then what you mentioned is not a bug but a user error.

**Comment by GitMensch** [comment]
Note @Explorer09 

> @GitMensch, please, please, tell us how exactly the current configure script goes wrong, instead of opening a PR that no one know what you are fixing.

The PR was explicit written upon request:

@westes said:

> So submit a pr for that [...]

**Comment by westes** [comment]
This discussion is good. Thanks to the both of you for hasing out the details of why this is needed and some of the edge cases involved.

On Monday, 17 September 2018, 12:28 am -0700, Simon Sobisch <notifications@github.com> wrote:

> Note @Explorer09 
> 
> > @GitMensch, please, please, tell us how exactly the current configure script goes wrong, instead of opening a PR that no one know what you are fixing.
> 
> The PR was explicit written upon request:
> 
> @westes said:
> 
> > So submit a pr for that [...]
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/386#issuecomment-421913964

-- 
Will Estes
westes575@gmail.com
