### ISSUE TITLE
cannot compile flex

### ISSUE THREAD

**Issue by stanekb** [westes/flex#404]
the reason is in my opinion that the file src/scan.c is not in the repo -only the src/scan.l
is included, which is useless if you do not have already a working flex on your system

pi@raspberrypi ~/AP/flex-master $ make
Making all in src
make[1]: Entering directory `/home/pi/AP/flex-master/src'
make  all-am
make[2]: Entering directory `/home/pi/AP/flex-master/src'
/bin/bash ../build-aux/ylwrap scan.l .c scan.c -- /bin/bash /home/pi/AP/flex-master/build-aux/missing flex
/home/pi/AP/flex-master/build-aux/missing: line 81: flex: command not found
WARNING: 'flex' is missing on your system.
         You should only need it if you modified a '.l' file.
         You may want to install the Fast Lexical Analyzer package:
         <https://github.com/westes/flex>
make[2]: *** [scan.c] Error 127
make[2]: Leaving directory `/home/pi/AP/flex-master/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/pi/AP/flex-master/src'
make: *** [all-recursive] Error 1

I had to copy scan.l to another machine created a scan.c there and was able to compile

**Comment by westes** [comment]
If you need to bootstrap flex, your options are to either install a pre-compiled version of flex, use the distribution tarball -- which includes scan.c and a number of other intermediate files -- or to cross-compile flex.

**Comment by stanekb** [comment]
simply adding the scan.c would have solved the problem

**Comment by westes** [comment]
There is no problem to be solved.

I explained your bootstrapping options above.

The flex tarball, e.g. is built from source and bootstraps itself.

On Wednesday, 14 November 2018,  7:37 am -0800, stanekb <notifications@github.com> wrote:

> simply adding the scan.c would have solved the problem
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/404#issuecomment-438706008

-- 
Will Estes
westes575@gmail.com

**Comment by theedge456** [comment]
Just to add that using the pre-compiled version of flex (2.5.4) on debian/stretch fails.
Hope that may help

**Comment by vpshastry** [comment]
I hit this problem now on the version 2.5.37. Just to confirm the solution here that you need flex to install flex?
