### ISSUE TITLE
No any Doc or Tutorial

### ISSUE THREAD

**Issue by Duk3m0n** [westes/flex#405]
It semms there is no doc or tutorial in this repo. As a beginner, how can I learm flex well? Is there any place   
I can get any instruction?

**Comment by westes** [comment]
Read the included manual.

**Comment by jannick0** [comment]
... or the [online manual](http://westes.github.io/flex/manual) which is as of now a little bit behind (version 2.6.2), but probably a good start if the manual in the repo is not at hand. Current flex version is 2.6.4.

**Comment by hhaoao** [comment]
[flex manual 2.6.3](https://www.cs.virginia.edu/~cr4bd/flex-manual/)
