### ISSUE TITLE
problem with build-aux/missing and runnnig sh scripts with bash.

### ISSUE THREAD

**Issue by informatimago** [westes/flex#411]
I see in the sources of flex, quite a few files that are scripts, with .sh extensions.  This is wrong.
Besides, two of them are actually bash scripts!

On the other hand, for `build-aux/missing`, you named it rightly, but you don't run it correctly!
Instead of running `build-aux/missing makeinfo ...` you apply /bin/bash on it:
```
/bin/bash /home/pjb/gcc/src/flex/build-aux/missing makeinfo   -I .  -o flex.info flex.texi
```
This is bad!
First, build-aux/missing is a sh script, not a bash script!
Then it could be modified to be a compiled program or a script in another programming language.

But the main problem I have with this missing script, is that it breaks the current environment.
I have a makeinfo (and a lot of other tools I want to use specifically for some builds) in the PATH of the parent process to make. Using bash to run the scripts ignores the current environment:
```
$ ./examplecaller 
User's BASH_ENV and ENV:
BASH_ENV=/home/pjb/.bash_env
ENV=/home/pjb/.bash_env
==================== Without BASH_ENV or ENV
example bash
TEST_ENV_VAR = Try without BASH_ENV or ENV, defined in examplecaller.
example sh
TEST_ENV_VAR = Try without BASH_ENV or ENV, defined in examplecaller.
--------------------
And with bash running the script:
example bash
TEST_ENV_VAR = Try without BASH_ENV or ENV, defined in examplecaller.
example sh
TEST_ENV_VAR = Try without BASH_ENV or ENV, defined in examplecaller.
==================== With BASH_ENV and ENV
example bash
TEST_ENV_VAR = Defined in BASH_ENV and ENV
example sh
TEST_ENV_VAR = Try with BASH_ENV and ENV, defined in examplecaller.
--------------------
And with bash running the script:
example bash
TEST_ENV_VAR = Defined in BASH_ENV and ENV
example sh
TEST_ENV_VAR = Defined in BASH_ENV and ENV
```
[example.shar.txt](https://github.com/westes/flex/files/2663247/example.shar.txt)

As you can see in the example scripts, when there is no BASH_ENV or ENV defined, it works as expected;  But when those environment variables are defined, a script run by bash will load BASH_ENV, and this will (possibly) reset the environment for the script.  
On the other hand, if missing was run by itself, being a sh script, it would keep inheriting the environment from its parent, without taking into account ENV (6th case).  But if you run those scripts with /bin/bash, in both cases, BASH_ENV is loaded.

Furthermore, /bin/bash is not always the right bash to use!  For example, Apple is known to distribute an old bash version 3 in /bin/bash, and we often have to use a newer bash installed elsewhere!
 
(Note for users encountering the same problem:  in the meantime, we can kill BASH_ENV and ENV in our compilation scripts, to fall back to the cases 3 and 4, but this may break other scripts...)

> Unix scripts should not have any file extension
> 
>     They unnecessarily expose implementation detail (breaking encapsulation).
>     They uselessly and incompletely mimic detail from the #! line.
>     They capture insufficient detail to be useful at the system level (and aren't used).
>     They clash with recommended Unix (and Linux) practice.
>     They add noise to the command-level API.
>     They are very commonly technically incorrect for the script.
>     They give incorrect impressions about the use of the files they adorn.
>     They aren't validated even for what little info is present in them.
>     They interfere with switching scripting languages.
>     They interfere with changing scripting language versions.
>     They interfere with changing to presumably-faster compiled forms.
>     They encourage naively running scripts with the extension-implied interpreter.
>     They infect novice scripters with misinformation about Unix scripting.
>     They ironically are only a problem when interpreted by humans.
> 
> See more at:
> 
>     http://www.talisman.org/~erlkonig/documents/commandname-extensions-considered-harmful
>

**Comment by westes** [comment]
The "missing" script is brought in by the autotools tool chain. If you have a bug to report about its invokation, then report it to the relevant project.

Try using the SHELL environment variable if you need to control which shell is used to run scripts.

The example scripts you refer to are not part of flex. Please report any problems you have with flex or its files; we cannot control files outside of the flex codebase or official flex cdistribution.

If you have custom tools you wish to use in building flex, consult the documentation for automake/autoconf to see what environment variables to use to prefer those tools to what autoconf/automake would otherwise choose.

On Monday, 10 December 2018,  5:18 am -0800, "Pascal J. Bourguignon" <notifications@github.com> wrote:

> I see in the sources of flex, quite a few files that are scripts, with .sh extensions.  This is wrong.
> Besides, two of them are actually bash scripts!
> 
> On the other hand, for `build-aux/missing`, you named it rightly, but you don't run it correctly!
> Instead of running `build-aux/missing makeinfo ...` you apply /bin/bash on it:
> ```
> /bin/bash /home/pjb/gcc/src/flex/build-aux/missing makeinfo   -I .  -o flex.info flex.texi
> ```
> This is bad!
> First, build-aux/missing is a sh script, not a bash script!
> Then it could be modified to be a compiled program or a script in another programming language.
> 
> But the main problem I have with this missing script, is that it breaks the current environment.
> I have a makeinfo (and a lot of other tools I want to use specifically for some builds) in the PATH of the parent process to make. Using bash to run the scripts ignores the current environment:
> ```
> $ ./examplecaller 
> User's BASH_ENV and ENV:
> BASH_ENV=/home/pjb/.bash_env
> ENV=/home/pjb/.bash_env
> ==================== Without BASH_ENV or ENV
> example bash
> TEST_ENV_VAR = Try without BASH_ENV or ENV, defined in examplecaller.
> example sh
> TEST_ENV_VAR = Try without BASH_ENV or ENV, defined in examplecaller.
> --------------------
> And with bash running the script:
> example bash
> TEST_ENV_VAR = Try without BASH_ENV or ENV, defined in examplecaller.
> example sh
> TEST_ENV_VAR = Try without BASH_ENV or ENV, defined in examplecaller.
> ==================== With BASH_ENV and ENV
> example bash
> TEST_ENV_VAR = Defined in BASH_ENV and ENV
> example sh
> TEST_ENV_VAR = Try with BASH_ENV and ENV, defined in examplecaller.
> --------------------
> And with bash running the script:
> example bash
> TEST_ENV_VAR = Defined in BASH_ENV and ENV
> example sh
> TEST_ENV_VAR = Defined in BASH_ENV and ENV
> ```
> [example.shar.txt](https://github.com/westes/flex/files/2663247/example.shar.txt)
> 
> As you can see in the example scripts, when there is no BASH_ENV or ENV defined, it works as expected;  But when those environment variables are defined, a script run by bash will load BASH_ENV, and this will (possibly) reset the environment for the script.  
> On the other hand, if missing was run by itself, being a sh script, it would keep inheriting the environment from its parent, without taking into account ENV (6th case).  But if you run those scripts with /bin/bash, in both cases, BASH_ENV is loaded.
> 
> Furthermore, /bin/bash is not always the right bash to use!  For example, Apple is known to distribute an old bash version 3 in /bin/bash, and we often have to use a newer bash installed elsewhere!
>  
> (Note for users encountering the same problem:  in the meantime, we can kill BASH_ENV and ENV in our compilation scripts, to fall back to the cases 3 and 4, but this may break other scripts...)
> 
> > Unix scripts should not have any file extension
> > 
> >     They unnecessarily expose implementation detail (breaking encapsulation).
> >     They uselessly and incompletely mimic detail from the #! line.
> >     They capture insufficient detail to be useful at the system level (and aren't used).
> >     They clash with recommended Unix (and Linux) practice.
> >     They add noise to the command-level API.
> >     They are very commonly technically incorrect for the script.
> >     They give incorrect impressions about the use of the files they adorn.
> >     They aren't validated even for what little info is present in them.
> >     They interfere with switching scripting languages.
> >     They interfere with changing scripting language versions.
> >     They interfere with changing to presumably-faster compiled forms.
> >     They encourage naively running scripts with the extension-implied interpreter.
> >     They infect novice scripters with misinformation about Unix scripting.
> >     They ironically are only a problem when interpreted by humans.
> > 
> > See more at:
> > 
> >     http://www.talisman.org/~erlkonig/documents/commandname-extensions-considered-harmful
> > 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/411

-- 
Will Estes
westes575@gmail.com
