### ISSUE TITLE
Support for regular expression backreference

### ISSUE THREAD

**Issue by lightyear15** [westes/flex#418]
It seems like regular expressions' backreference does not work.
I am trying to match raw string literals declared like in C++11:
 R "delimiter( raw_characters )delimiter"
I have tested with the following regular expressions ( R is replaced by the character @):
```
\@\"\\(.*\\)(\\(.*\\))\\1\"" 
```
or 
```
"\@\"(.*)\((.*)\)\1\""  
```
and none of them works. 
Quick test using regex implementation of gnu libc (same one flex is linked against) shows that at least the first regex works in matching the string 
```
"@\"prefix(hello!!!)prefix\""
```

**Comment by zmajeed** [comment]
`flex` regex does not support backreferences. You can keep state in application code or use states called "start conditions" in the rules file. Here's a  rule for C++ raw strings that extracts and matches the left and right delimiters

```
R\"[^() \\]{0,16}\((.|\n)*\)[^() \\]{0,16}\" {
  const char* delim=yytext + 2;
  size_t len=strchr(yytext, '(') - yytext - 2;
  const char* closeparen=yytext + yyleng - len - 2;
  if(*closeparen != ')' || strncmp(closeparen+1, delim, len)) {
    exit(1);
  }
  yyterminate();
}
```

Alternatively, `strchr` can be avoided with a start condition state

```
%x RSTRING_HAVE_LEFT_DELIM
%%
 char delim[17];
 size_t delim_len;

R\"[^() \\]{0,16}\( {
  BEGIN(RSTRING_HAVE_LEFT_DELIM);
  delim_len=yyleng-3;
  strncpy(delim, yytext+2, delim_len);
}

<RSTRING_HAVE_LEFT_DELIM>(.|\n)*\)[^() \\]{0,16}\" {
  if(yyleng - 2 < delim_len) {
    exit(1);
  }
  const char* closeparen=yytext + yyleng - 2 - delim_len;
  if(*closeparen != ')' || strncmp(closeparen+1, delim, delim_len)) {
    exit(2);
  }
  yyterminate();
}
```

**Comment by lightyear15** [comment]
Yes, I suspected that I had to do something like you suggested.
Thanks
