### ISSUE TITLE
ERROR: end of file in string

### ISSUE THREAD

**Issue by Fazendaaa** [westes/flex#422]
Hey, I'm trying to compile my file with

```sh
flex ./src/syntactic.l -o ./src/lex.yy.c
```

But the following error message is given:

```sh
flex: can't open -o
/usr/bin/m4:stdin:3187: ERROR: end of file in string
```

When I try to compile with the following:

```sh
flex ./src/syntactic.l
```

It works just fine, but what I want is to save the generated `lex.yy.c` in the `./src/` folder; what is my mistake?

**Comment by zmajeed** [comment]
Try putting all options before any arguments:

```bash
flex -o ./src/lex.yy.c ./src/syntactic.l
```
