### ISSUE TITLE
Missing assets for flex 2.5.39

### ISSUE THREAD

**Issue by bbulkow** [westes/flex#423]
I am trying to install flex 2.5.39, yes I know it is old but I am working with a codebase that I hope to improve, first I have to get things building, and I find that the source code is available but the actual flex packages are not. Flex packages seem only available back to 2.6.1.

For those of us stuck in some ancient land, at least having the 'end of the road' for 2.5 available, it would seem very reasonable to have these old flex packages available for download, not just the source. Thanks.

**Comment by zmajeed** [comment]
I see flex 2.5.39 https://github.com/westes/flex/archive/flex-2.5.39.tar.gz on the release page https://github.com/westes/flex/releases

**Comment by westes** [comment]
I dug up the files and added them to https://github.com/westes/flex/releases/tag/flex-2.5.39
