### ISSUE TITLE
Build Issue on Fedora 31 (with fix)

### ISSUE THREAD

**Issue by nobozo** [westes/flex#434]
A clone of today's head (8b1fbf674f2e038df9cf1fe7725617e3837ae2a9) fails to build on Fedora 31 x86_64. The error message is:

```
Can't exec "autopoint": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 345.
autoreconf: failed to run autopoint: No such file or directory
autoreconf: autopoint is needed because this package uses Gettext
```

The solution is trivial. Run

`dnf install gettext-devel`

**Comment by westes** [comment]
This is not a bug in flex. It is known and documented that autopoint is required to build flex, so failure to install it is a bug in the environment.
