### ISSUE TITLE
Typo in Getting Started document ( Unicornscan-Getting_Started.pdf)

### ISSUE THREAD

**Issue by ijf8090** [westes/flex#439]
Section 1.2., 1.2.3,  1.2.4 and 1.4
 As a priveldeged user, make install:
# make install

Should be 
 As a privileged user, make install:
# make install.

If somebody can point me to the source document, I will try and make the change.

**Comment by Explorer09** [comment]
Did you report to the right project? This is Flex, the lexical analyzer generator. And I didn't find your said typo in Flex's documentation.

**Comment by westes** [comment]
Flex has no such getting started document.
