### ISSUE TITLE
Missing `version.texi` when generating document from `doc/flex.texi`

### ISSUE THREAD

**Issue by jondy** [westes/flex#440]
Build html page from `doc/flex.texi` by this command
```
makeinfo --html --no-split flex.texi
```
It complains of missing `version.texi`, and I find it list in the `.gitingore` when I search `version.texi` in this repo.

**Comment by westes** [comment]
The file version.texi is included in the flex source distribution, e.g. flex-2.6.4.tar.gz. If you're working from the git codebase itself, then you need to run autogen.sh, configure and make.
