### ISSUE TITLE
flex 2.6.4 produces 0 octet lex.yy.c file

### ISSUE THREAD

**Issue by cprudhom** [westes/flex#441]
Hi,

I'm trying to run simple commands from [FLEX Tutorial](http://alumni.cs.ucr.edu/~lgao/teaching/flex.html#practice)) but it produces 0 octet lex.yy.c file:

```bash
$ flex -V
flex 2.6.4
$ flex sample1.lex 
$ ls -la lex.yy.c
-rw-r--r--  1 cprudhom  staff  0 17 mar 11:11 lex.yy.c
```
I'm on my Mac (Version 10.14.6 (18G2022)) using Flex 2.6.4.
When I run the first command with `-T`, I got:

```bash
%option %%
1	username
...
``` 
Is there any way to check what is going wrong ?

Best regards,
CP

**Comment by jannick0** [comment]
Hi,

just a couple of points I can contribute:
* First of all, this is not the site covering questions on other flex manuals. So be better prepared that the responses and assistance you should expect from here on other flex manuals could be very limited.
* From very very far sight, it might be that your input files need a conversion of the end-of-line character for MAC purposes ... a general cross-platform issue. Maybe using the executable `unix2mac` or similar?
* Here a minimal testing example to start off: `echo %% > test.l; flex test.l` should generate `lex.yy.c`.
* More on flex and much more meaningful flex input files in the [online flex manual](https://westes.github.io/flex/manual/) (version 2.6.2).

HTH.

**Comment by cprudhom** [comment]
> First of all, ...

Ok, got it

> Here a minimal testing example to start off: `echo %% > test.l; flex test.l` should generate lex.yy.c.

It does but once again, the file is empty (0 octet).

> More on flex ...

I'll have a look and let you know

**Comment by jannick0** [comment]
`flex` requires `m4` to be installed. If `flex` cannot find `m4` on its own, then try to set the environment variable `M4` to the absolute path of `m4` to make `flex` be aware of it.

Hope that helps.

**Comment by cprudhom** [comment]
That fixes my issue

**Comment by cprudhom** [comment]
And thank you for your help !
