### ISSUE TITLE
flex-2.5.35 security consultation

### ISSUE THREAD

**Issue by eshiont** [westes/flex#459]
In the process of using the component (flex-2.5.35), we analyzed and evaluated the password security,
The following types of suspected security problems were found:

1. Secret Keyword
2. Base64 High Entropy String

15 of the above problems have been found. We hope to get technical support from your organization for evaluation or modification. For details, please contact: mao.biao @ zte.com.cn

**Comment by westes** [comment]
Please use a currently suported version of flex.
