### ISSUE TITLE
Basic information for quick installation on Linux

### ISSUE THREAD

**Issue by PauloBoaventura** [westes/flex#473]
I would like to ask the developers and contributors that if possible, create the file again in the current directory.
I have seen that the file no longer counts

 The reason for this request is so that you have a brief description of quick and effective installation and are thus a basis for any distribution.

There is an indication to install Tools from the repository maintainer.
 it as a list but requested a reference to this list via the command line.

 Just as it should be cloned and first steps taken.

 As the base for Linux installation, this must be the base system for sterilization.

A brief explanation, stating the reason for this request.

 I've been installing snort, which gave me a compilation error referring to trying to install Flex.
 When I came across flex's Github, I didn't find any reference to install. and I also had doubts about how to install tools to make the Flex installation work.

 so I was confused and with that I didn’t proceed with the installation of Flex or Tools, let alone snort.

 What set me up Ah, you're requesting this information.
 Although I have a medium level experience. I had no confidence in installing it by searching. or any reference found on the web.
 because it could be installing the wrong dependencies and still not solve the installation.

 Thank you in advance for any contribution

**Comment by westes** [comment]
Your request is unclear.

What did you try? What was the result? Why was that not what you expected? Is there some reason why your upstream distribution's packaging of flex isn't enough?
