### ISSUE TITLE
gnuwin32 distribution doesn't support --nounistd

### ISSUE THREAD

**Issue by JC3** [westes/flex#477]
The binaries at http://gnuwin32.sourceforge.net/packages/flex.htm (which link here, so I'm assuming this is the same project) are version 2.5.4a-1.

For some reason this version doesn't support the `--nounistd` option:

```
C:\Programs\Qt\5.12.6\mingw73_32>flex --version
flex version 2.5.4

C:\Programs\Qt\5.12.6\mingw73_32>flex --nounistd
flex: unknown flag '-'.  For usage, try
        flex --help
```

This then makes that version incompatible with Qt's qmake, which uses that option on Windows.

While the workaround is relatively straightforward -- find a compatible version of flex and install that instead -- the gnuwin32 release page is the top search result and the most readily available, and also it's probably expected to be the latest version, or at least a fully functional version.

So the gnuwin32 project builds should probably be updated.

**Comment by Mightyjo** [comment]
I see how you got here from GnuWin's sourceforge site. Not sure why it's linked here like that.

At any rate, please report this to [GnuWin, here](http://gnuwin32.sourceforge.net/lists.html). They build those binaries and it looks like they're working with version 2.5.4 from 1996. There are loads of modern features missing from that version; lack of --nounistd is just the beginning.

**Comment by JC3** [comment]
Will do; thanks.
