### ISSUE TITLE
several potential bugs 

### ISSUE THREAD

**Issue by Hyxl1017** [westes/flex#498]
hello,I found some bugs in source code,would you help me check whether these bugs are true?thank you very much.

there is a potential bug of  Memory Leak :
==============================================================================

step  1 : 
	 In file  flex/src/regex.c , function  regmatch_dup   line  80 :
 		 Allocate memory to str 

step  2 : 
	 In file  flex/src/regex.c , function  regmatch_dup   line  81 :
 		 Select the false branch at this point (str==null is false) 

step  3 : 
	 In file  flex/src/regex.c , function  regmatch_strtol   line  142 :
 		 Function regmatch_dup executes and stores the return value to s 

step  4 : 
	 In file  flex/src/regex.c , function  regmatch_strtol   line  146 :
 		 Select the false branch at this point (s!=buf[0] is false), the allocated memory is leaked 

there is a potential bug of  NULL Pointer Dereference :
==============================================================================

step  1 : 
	 In file  flex/src/regex.c , function  regmatch_dup   line  76 :
 		 Select the true branch at this point (m->rm_eo<m->rm_so is true) 

step  2 : 
	 In file  flex/src/regex.c , function  regmatch_dup   line  85 :
 		 Return null to caller 

step  3 : 
	 In file  flex/src/filter.c , function  filter_fix_linedirs   line  354 :
 		 Function regmatch_dup executes and stores the return value to fname (fname can be null) 

step  4 : 
	 In file  flex/src/filter.c , function  filter_fix_linedirs   line  356 :
 		 fname is used as the 1st parameter in function strcmp (fname can be null) 

there is a potential bug of  Unchecked Return Value to NULL Pointer Dereference :
==============================================================================

step  1 : 
	 In file  flex/src/filter.c , function  filter_tee_header   line  245 :
 		 Function fdopen executes and stores the return value to to_c (to_c can be null) (lacking failure check, 2 out of 5 file openings checked failures) 

step  2 : 
	 In file  flex/src/filter.c , function  filter_tee_header   line  270 :
 		 to_c is used as the 2nd parameter in function fputs (to_c can be null)

**Comment by westes** [comment]
Please report these bugs separately -- one bug per issue.

**Comment by westes** [comment]
additionally, please provide the versions of the tools in your tool chain and sample files that trigger the undesired behavior. You can reach out privately if you would rather.

**Comment by Hyxl1017** [comment]
> additionally, please provide the versions of the tools in your tool chain and sample files that trigger the undesired behavior. You can reach out privately if you would rather.

Sorry, I'm afraid I can't provide the sample file you want. The above bugs are obtained through static analysis of the source code. but,If the bug I reported may have such behavior, it's beneficial and harmless to pay effort to repair it in order to avoid the possibility of such undesired behavior.I will report two bugs above separately,thanks for your advice.
