### ISSUE TITLE
'flex' is missing on your system while installing flex

### ISSUE THREAD

**Issue by yhg926** [westes/flex#503]
Here is my command to install flex:
yihuiguang@amax: flex-2.6.4:$./autogen.sh
yihuiguang@amax: flex-2.6.4:$./configure --prefix=/data/yihuiguang/
yihuiguang@amax: flex-2.6.4:$make
Making all in src
make[1]: Entering directory '/data/yihuiguang/tools/flex-2.6.4/src'
make  all-am
make[2]: Entering directory '/data/yihuiguang/tools/flex-2.6.4/src'
/bin/bash ../build-aux/ylwrap scan.l .c scan.c -- /bin/bash /home/yihuiguang/work/tools/flex-2.6.4/build-aux/missing flex
/home/yihuiguang/work/tools/flex-2.6.4/build-aux/missing: line 81: flex: command not found
WARNING: 'flex' is missing on your system.
         You should only need it if you modified a '.l' file.
         You may want to install the Fast Lexical Analyzer package:
         <https://github.com/westes/flex>
make[2]: *** [Makefile:1463: scan.c] Error 127
make[2]: Leaving directory '/data/yihuiguang/tools/flex-2.6.4/src'
make[1]: *** [Makefile:575: all] Error 2
make[1]: Leaving directory '/data/yihuiguang/tools/flex-2.6.4/src'
make: *** [Makefile:533: all-recursive] Error 1

**Comment by westes** [comment]
As stated in the documentation, you need to start by building from the distribution tar ball which contains all files necessary for building flex directly from source. Then you can check out the git repository and build from it.
