### ISSUE TITLE
Request to tag an old release

### ISSUE THREAD

**Issue by doraskayo** [westes/flex#512]
Version 2.5.11 of flex was released back in 2002, but it seems that it's not tagged in the repository.

This version is important for being able to bootstrap flex, and is used in projects that focus on creating a bootstrap path for modern software and operating systems which is dependant entirely on source code and very minimal binary seeds (see https://bootstrappable.org/).

It would be nice to have this release tagged in the official repository; GitHub should then provide a tarball for it as well.

This is the relevant commit: https://github.com/westes/flex/commit/d160f0247ba1611aa59d28f027d6292ba24abb50

**Comment by stikonas** [comment]
By the way, original tarball is available from
http://download.nust.na/pub2/openpkg1/sources/DST/flex/flex-2.5.11.tar.gz

**Comment by westes** [comment]
versions of flex before 2.6.0 are not supported.

**Comment by fosslinux** [comment]
Not interested for support for it, just for it to be tagged in the repository, as has been done for all 2.6.x releases and 2.5.39.

It has value for the aformentioned bootstrapping reason. While again, we are not interested for any support for it, it would be useful to have a reliable source tarball for this version, rather from some random website.

**Comment by westes** [comment]
The autogenerated tarball will not contain the intermediate files necessary to build flex from source. That wil cause people to request support for an outdated release which will take away time from future development. Since it's 20 years old, I'm comfortable not supporting it any more.
