### ISSUE TITLE
fix Travis - and how to do so

### ISSUE THREAD

**Issue by GitMensch** [westes/flex#515]
This can only be done by @westes as repo owner, so there's no chance for a PR.
To fix:
* go to https://docs.travis-ci.com/user/migrate/open-source-repository-migration#migrating-a-repository - and follow the few steps (done in 5-30 minutes)
* change README.md: s/travis-ci.org/travis-ci.com/g

done - the builds should work again

**Comment by Croydon** [comment]
Obsolete by migrating to GitHub Actions via https://github.com/westes/flex/pull/523
