### ISSUE TITLE
make: *** [Makefile:541: install-recursive] Error 1

### ISSUE THREAD

**Issue by acteam-ux** [westes/flex#516]
i am installing the latest version. after cloning, i ran `./autogun.sh`, after that, i ran `./configure && make && make install` 
after some hassle and installing `texinfo`, `flex` (??) and some others, it gives me this error while installing:
`make: *** [Makefile:541: install-recursive] Error 1`

**Comment by westes** [comment]
We'll need a bit more of the error log to figure out what you're missing.

YOu -should- be able to build flex from the distribution without having to install flex itself, so what is "the latest version" that you downloaded?

**Comment by acteam-ux** [comment]
i mean i am doing this right away after cloning so it isn't old.

**Comment by westes** [comment]
You haven't provided enough information to diagnose the problem. See my previous comment for what is needed.

**Comment by acteam-ux** [comment]
I ran `./autogun.sh`, it runs without any errors. but when i run `./configure && make && make install` it gives me errors:
`
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... gawk
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking whether NLS is requested... yes
checking for msgfmt... no
checking for gmsgfmt... :
checking for xgettext... no
checking for msgmerge... no
checking for ld used by gcc... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking for shared library run path origin... done
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking for GNU gettext in libc... yes
checking whether to use NLS... yes
checking where the gettext function comes from... libc
checking for bison... bison -y
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... -lfl
checking whether yytext is a pointer... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking how to run the C preprocessor... gcc -E
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking dependency style of g++... gcc3
checking whether ln -s works... yes
checking for gawk... (cached) gawk
checking for help2man... ${top_srcdir}/build-aux/missing help2man
configure: WARNING: help2man: program not found: building man page will not work
checking for gtexi2dvi... no
checking for texi2dvi... /usr/bin/texi2dvi
checking for m4 that supports -P... /usr/bin/m4
checking for indent... ${top_srcdir}/build-aux/missing indent
checking if ${top_srcdir}/build-aux/missing indent is GNU indent... no
configure: WARNING: ${top_srcdir}/build-aux/missing indent does not appear to be GNU indent; 'make indent' may not function properly
checking regex.h usability... yes
checking regex.h presence... yes
checking for regex.h... yes
checking for strings.h... (cached) yes
checking sys/wait.h usability... yes
checking sys/wait.h presence... yes
checking for sys/wait.h... yes
checking for unistd.h... (cached) yes
checking for inttypes.h... (cached) yes
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking for pthread_mutex_lock in -lpthread... yes
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking for log10 in -lm... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking for working alloca.h... yes
checking for alloca... yes
checking for pid_t... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for dup2... yes
checking for memset... yes
checking for regcomp... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strdup... yes
checking for strtol... yes
checking for pow... yes
checking for setlocale... yes
checking for reallocarr... no
checking for reallocarray... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating doc/Makefile
config.status: creating examples/Makefile
config.status: creating examples/fastwc/Makefile
config.status: creating examples/manual/Makefile
config.status: creating po/Makefile.in
config.status: creating src/libfl.pc
config.status: creating src/Makefile
config.status: creating tools/Makefile
config.status: creating tests/Makefile
config.status: creating src/config.h
config.status: src/config.h is unchanged
config.status: executing libtool commands
config.status: executing depfiles commands
config.status: executing po-directories commands
config.status: creating po/POTFILES
config.status: creating po/Makefile
Making all in src
make[1]: Entering directory '/home/abolfazl/Desktop/flex/src'
make  all-am
make[2]: Entering directory '/home/abolfazl/Desktop/flex/src'
make[2]: Leaving directory '/home/abolfazl/Desktop/flex/src'
make[1]: Leaving directory '/home/abolfazl/Desktop/flex/src'
Making all in doc
make[1]: Entering directory '/home/abolfazl/Desktop/flex/doc'
../build-aux/missing help2man --name='the fast lexical analyser generator' --section=1 \
--source='The Flex Project' --manual='Programming' \
--output=flex.1 ../src/flex \
|| rm -f flex.1
../build-aux/missing: 81: help2man: not found
WARNING: 'help2man' is missing on your system.
         You should only need it if you modified a dependency of a man page.
         You may want to install the GNU Help2man package:
         <https://www.gnu.org/software/help2man/>
make[1]: Leaving directory '/home/abolfazl/Desktop/flex/doc'
Making all in examples
make[1]: Entering directory '/home/abolfazl/Desktop/flex/examples'
Making all in manual
make[2]: Entering directory '/home/abolfazl/Desktop/flex/examples/manual'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/abolfazl/Desktop/flex/examples/manual'
Making all in fastwc
make[2]: Entering directory '/home/abolfazl/Desktop/flex/examples/fastwc'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/abolfazl/Desktop/flex/examples/fastwc'
make[2]: Entering directory '/home/abolfazl/Desktop/flex/examples'
make[2]: Nothing to be done for 'all-am'.
make[2]: Leaving directory '/home/abolfazl/Desktop/flex/examples'
make[1]: Leaving directory '/home/abolfazl/Desktop/flex/examples'
Making all in po
make[1]: Entering directory '/home/abolfazl/Desktop/flex/po'
make flex.pot-update
make[2]: Entering directory '/home/abolfazl/Desktop/flex/po'
package_gnu=""no""; \
test -n "$package_gnu" || { \
  if { if (LC_ALL=C find --version) 2>/dev/null | grep GNU >/dev/null; then \
         LC_ALL=C find -L .. -maxdepth 1 -type f \
                       -size -10000000c -exec grep 'GNU flex' \
                       /dev/null '{}' ';' 2>/dev/null; \
       else \
         LC_ALL=C grep 'GNU flex' ../* 2>/dev/null; \
       fi; \
     } | grep -v 'libtool:' >/dev/null; then \
     package_gnu=yes; \
   else \
     package_gnu=no; \
   fi; \
}; \
if test "$package_gnu" = "yes"; then \
  package_prefix='GNU '; \
else \
  package_prefix=''; \
fi; \
if test -n 'flex-devel@lists.sourceforge.net' || test 'flex-help@lists.sourceforge.net' = '@'PACKAGE_BUGREPORT'@'; then \
  msgid_bugs_address='flex-devel@lists.sourceforge.net'; \
else \
  msgid_bugs_address='flex-help@lists.sourceforge.net'; \
fi; \
case `: --version | sed 1q | sed -e 's,^[^0-9]*,,'` in \
  '' | 0.[0-9] | 0.[0-9].* | 0.1[0-5] | 0.1[0-5].* | 0.16 | 0.16.[0-1]*) \
    : --default-domain=flex --directory=.. \
      --add-comments=TRANSLATORS: --language=C --keyword=_ --keyword=N_  \
      --files-from=./POTFILES.in \
      --copyright-holder='' \
      --msgid-bugs-address="$msgid_bugs_address" \
    ;; \
  *) \
    : --default-domain=flex --directory=.. \
      --add-comments=TRANSLATORS: --language=C --keyword=_ --keyword=N_  \
      --files-from=./POTFILES.in \
      --copyright-holder='' \
      --package-name="${package_prefix}flex" \
      --package-version='2.6.4' \
      --msgid-bugs-address="$msgid_bugs_address" \
    ;; \
esac
test ! -f flex.po || { \
  if test -f ./flex.pot-header; then \
    sed -e '1,/^#$/d' < flex.po > flex.1po && \
    cat ./flex.pot-header flex.1po > flex.po; \
    rm -f flex.1po; \
  fi; \
  if test -f ./flex.pot; then \
    sed -f remove-potcdate.sed < ./flex.pot > flex.1po && \
    sed -f remove-potcdate.sed < flex.po > flex.2po && \
    if cmp flex.1po flex.2po >/dev/null 2>&1; then \
      rm -f flex.1po flex.2po flex.po; \
    else \
      rm -f flex.1po flex.2po ./flex.pot && \
      mv flex.po ./flex.pot; \
    fi; \
  else \
    mv flex.po ./flex.pot; \
  fi; \
}
make[2]: Leaving directory '/home/abolfazl/Desktop/flex/po'
test ! -f ./flex.pot || \
  test -z "bg.gmo ca.gmo da.gmo de.gmo en@boldquot.gmo en@quot.gmo eo.gmo es.gmo fi.gmo fr.gmo ga.gmo hr.gmo ko.gmo nl.gmo pl.gmo pt.gmo pt_BR.gmo ro.gmo ru.gmo sr.gmo sv.gmo tr.gmo uk.gmo vi.gmo zh_CN.gmo zh_TW.gmo" || make bg.gmo ca.gmo da.gmo de.gmo en@boldquot.gmo en@quot.gmo eo.gmo es.gmo fi.gmo fr.gmo ga.gmo hr.gmo ko.gmo nl.gmo pl.gmo pt.gmo pt_BR.gmo ro.gmo ru.gmo sr.gmo sv.gmo tr.gmo uk.gmo vi.gmo zh_CN.gmo zh_TW.gmo
make[1]: Leaving directory '/home/abolfazl/Desktop/flex/po'
Making all in tests
make[1]: Entering directory '/home/abolfazl/Desktop/flex/tests'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/abolfazl/Desktop/flex/tests'
Making all in tools
make[1]: Entering directory '/home/abolfazl/Desktop/flex/tools'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/abolfazl/Desktop/flex/tools'
make[1]: Entering directory '/home/abolfazl/Desktop/flex'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/abolfazl/Desktop/flex'
Making install in src
make[1]: Entering directory '/home/abolfazl/Desktop/flex/src'
make  install-am
make[2]: Entering directory '/home/abolfazl/Desktop/flex/src'
make[3]: Entering directory '/home/abolfazl/Desktop/flex/src'
 /usr/bin/mkdir -p '/usr/local/lib'
 /bin/bash ../libtool   --mode=install /usr/bin/install -c   libfl.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libfl.so.2.0.0 /usr/local/lib/libfl.so.2.0.0
/usr/bin/install: cannot create regular file '/usr/local/lib/libfl.so.2.0.0': Permission denied
make[3]: *** [Makefile:721: install-libLTLIBRARIES] Error 1
make[3]: Leaving directory '/home/abolfazl/Desktop/flex/src'
make[2]: *** [Makefile:1643: install-am] Error 2
make[2]: Leaving directory '/home/abolfazl/Desktop/flex/src'
make[1]: *** [Makefile:1637: install] Error 2
make[1]: Leaving directory '/home/abolfazl/Desktop/flex/src'
make: *** [Makefile:542: install-recursive] Error 1
`
this is the whole log, so not all of it are errors.

**Comment by Mightyjo** [comment]
You're trying to install in /usr/local. You need to run 
`sudo make install`

**Comment by westes** [comment]
closing due to user error
