### ISSUE TITLE
Reporting security issues

### ISSUE THREAD

**Issue by the-storm** [westes/flex#520]
Hello Flex team
Is there any guidance to report security issues? Should we file them as issue on github or is there a more private channel to communicate them? 

Thanks
Ibrahim

**Comment by westes** [comment]
Like a lot of things, "it depends". My email address is easy to find, so if you think it needs to be private, send it directly. If you think it is easy and straight forward, then just post a pr.

**Comment by the-storm** [comment]
Thanks for the quick reply. I found multiple emails wlestes@users.sourceforge.net or westes575@gmail.com just double checking they are valid and if you have any preferences :)
