### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by Vertexwahn** [westes/flex#536]
The last release was flex 2.6.4 from 2017. Would make sense to publish a new release since it seems several issues have been resolved since then.

Could help for instance [here] (https://github.com/jmillikin/rules_flex/blob/c40bf6a62dfcd4e849eef9bf1489f75ee987944e/flex/internal/versions.bzl#L33) to support a wider range of new compiler (VS2019, VS2022)

**Comment by westes** [comment]
Work to make this easier is in progress already.
