### ISSUE TITLE
Compile failed on MacOS 12.4 (arm chip)

### ISSUE THREAD

**Issue by wendajiang** [westes/flex#539]
clang 13 or gcc 12 both compile error 
```
./cpp-flex.h:9:69: error: expected expression
  "m4_define([[M4_PROPERTY_TRACE_LINE_REGEXP]], [[^#line ([0-9]+) ",\"(.*)\"]])
                                                                    ^
./cpp-flex.h:9:70: warning: missing terminating '"' character [-Winvalid-pp-token]
  "m4_define([[M4_PROPERTY_TRACE_LINE_REGEXP]], [[^#line ([0-9]+) ",\"(.*)\"]])

```

It look like m4 process error.

My m4 version is 

<img width="533" alt="image" src="https://user-images.githubusercontent.com/13445879/183837348-d5b07ba1-0795-46d3-97d2-22479f50e845.png">

and generate `cpp-flex.h`

![image](https://user-images.githubusercontent.com/13445879/183837463-3b84ede5-9a99-4d02-af10-fd385af7f74f.png)

As I'm not familiar with m4, why it generate the ",\" ?

**Comment by wendajiang** [comment]
https://github.com/westes/flex/pull/353 resolve this

**Comment by wendajiang** [comment]
After resolve mkskl.sh, new problem occur:
```
scan.l:677:10: error: implicit declaration of function 'yyinput' is invalid in C99 [-Werror,-Wimplicit-function-declaration]

```

**Comment by biergaizi** [comment]
I created Pull Request #554 to fix this problem. Please take a try.

**Comment by biergaizi** [comment]
Also see https://github.com/biergaizi/flex/commit/cce2df853386d5b5b60445b1204dcca08e9f259e for backport to v2.6.4.

**Comment by wendajiang** [comment]
scan.l:677:10: error: call to undeclared function 'yyinput'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                                if ( yyinput() != ']' )
                                     ^
scan.l:677:10: note: did you mean 'yyunput'?
scan.c:2266:17: note: 'yyunput' declared here
    static void yyunput ( int c, char *buf_ptr  );


> #353 resolve this

And this pr not merged.

**Comment by biergaizi** [comment]
I'm not the maintainer but I noticed that you're reporting two bugs in the same issue. I suggest you to open another bug for the original issue.
