### ISSUE TITLE
flex --noline outputs a #line directive

### ISSUE THREAD

**Issue by srivasta** [westes/flex#55]
Hi,

  This issue was reported by a Debian user in [Bug 729927]( https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=729927)

The command
   flex --noline name.lex 

generates the line
   #line 3 "lex.yy.c"

This causes some confusion when:
1: line 3 is really line 2, and,
2: when (in order to compile using C++) the file has
   been renamed to (something like) lex.yy.cpp causing
   error messages to specify file lex.yy.c instead of
   lex.yy.cpp (or some other name).

   Manoj

**Comment by westes** [comment]
As per recent changes to master, this is now resolved.
