### ISSUE TITLE
Using help2man to generate manpages does not work when cross-compiling

### ISSUE THREAD

**Issue by th-otto** [westes/flex#560]
In the doc directory, help2man is used to generate the manpage. help2man executes the binary and parses its output; obviously that doesn't work when cross-compiling. Luckily, when cross-compiling, flex already has a binary for the host. Attached patch fixes the Makefile to use that instead.

(the patch is against the source of the last official 2.6.4 release, and might need adjustments for current source, but its minimal)

```
--- a/doc/Makefile.am	2023-04-07 09:32:49.975936180 +0200
+++ b/doc/Makefile.am	2023-04-07 09:33:47.699833005 +0200
@@ -1,4 +1,8 @@
+if CROSS
+FLEX = $(top_builddir)/src/stage1flex
+else
 FLEX = $(top_builddir)/src/flex$(EXEEXT)
+endif
 
 info_TEXINFOS =	flex.texi
 dist_man_MANS = flex.1
```

**Comment by westes** [comment]
Thanks for this -- good catch. It's merged to master now.

**Comment by th-otto** [comment]
That was quick ;) thanks.

BTW, imho its a bit useless to use help2man to provide a manpage. It won't give any information that is not already available by running ```flex --help```. But flex is not the only package where that is done ;)

**Comment by westes** [comment]
The purpose of help2man isn't to provide additional information. It is to make having a current man page happen automatically.
