### ISSUE TITLE
GnuLib update renders Flex lexers uncompilable

### ISSUE THREAD

**Issue by paul-j-lucas** [westes/flex#564]
This recent [commit](https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=commit;h=8ad7bc671475d3291df10a1a1d64fddfd30e5175) in [GnuLib](https://www.gnu.org/software/gnulib/) renders Flex generated lexers uncompilable.  If you use GnuLib, you're using wrappers around standard headers like `stdio.h`.  The recent commit added lines to such wrappers like [this](https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blobdiff;f=lib/stdio.in.h;h=9c63e36b2af7cbe15170b5a93c55def523106641;hp=f3180149783f058b10e740f5c65e57d5cd608eaf;hb=8ad7bc671475d3291df10a1a1d64fddfd30e5175;hpb=eebb3a74aecc84cc2a316015ca58dc8ba3f35875):
```
#if !_GL_CONFIG_H_INCLUDED
 #error "Please include config.h first."
#endif
```
The problem is a Flex-generated lexer's `.c` file has:
```
/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
```
generated near the top and the project's include path is set to pick up the wrapper headers first — and the lexer's `.c` file doesn't have:
```
#include "config.h"
```
_before_ the include of the wrapper headers, so it complains.

AFAIK, there's no way to request that Flex insert code at the very beginning of a file like `%code top` in Bison.

So how can this be fixed?

**Comment by paul-j-lucas** [comment]
Of course an obvious work-around is to add `-D_GL_CONFIG_H_INCLUDED` to `CFLAGS`, but then that defeats the purpose of the check.

**Comment by westes** [comment]
For planning purposes, what is the update cycle for gnulib users? That is, how quickly is this going to effect folks?

**Comment by paul-j-lucas** [comment]
I have no idea. I'm just a GnuLib user. If you look at GnuLib's git log, the project seems pretty active.  AFAIK, there aren't "releases"; developers just push to the master branch and users (like me) just `git pull` occasionally.

**Comment by westes** [comment]
Ah, so one day a gnulib user will be able to compile flex generated lexers, then "suddenly" / "randomly" upon "git pull" from gnulib, they won't. and "occasionally" could mean a lot of things depending on what a gnulib user happpens to need; that is helpful to know, thank you!

**Comment by paul-j-lucas** [comment]
Actually, I think I misread your question. I _thought_ you asked what the release cycle of GnuLib itself, i.e., how often do the GnuLib developers release a new version of GnuLib.

I have no idea what other GnuLib users do, but I, as a GnuLib user, only tend to update GnuLib right before I'm about to release a new release of my software that uses GnuLib just so it has the latest and greatest, though there generally isn't any other compelling reason since my project's current snapshot works as-is.

**Comment by westes** [comment]
Thanks -- it turns out I should have asked both questions.

**Comment by paul-j-lucas** [comment]
If you're using Autotools, another work-around is to augment the generated lexer on-the-fly to `#include "config.h"` by using a custom `Makefile.am` rule to make the lexer rather than let Autotools use `ylwrap`:
```
# ...

BUILT_SOURCES = parser.c parser.h lexer.c

lexer.c: lexer.l
        { echo '#include "config.h"'; flex $(AM_LFLAGS) -t lexer.l; } > lexer.c

# ...
```

**Comment by bhaible** [comment]
Gnulib's answer is here: https://lists.gnu.org/archive/html/bug-gnulib/2023-04/msg00094.html
In particular, the workaround/fix (a) is very easy to put in place, and already used by several GNU packages.

**Comment by paul-j-lucas** [comment]
Apparently, I missed the fact that Flex _does_ have an equivalent to Bison's `%code top`. In Flex, it's just `%top`:
```
%top {
#include "config.h"
}
```
So I guess never mind.

**Comment by Mightyjo** [comment]
Thank goodness! I was pretty worried to think %top was broken. Glad it
worked out!

**Comment by bhaible** [comment]
> there aren't "releases"; developers just push to the master branch and users (like me) just `git pull` occasionally.

In Gnulib, there are no releases. But there are stable branches: https://www.gnu.org/software/gnulib/manual/html_node/Stable-Branches.html
