### ISSUE TITLE
flex fails to build on the system with too old flex

### ISSUE THREAD

**Issue by yurivict** [westes/flex#570]
Current revision [a97872a](https://github.com/westes/flex/commit/a97872a31146ddbd652994f3b05a7e86705a89c2) fails to build on the system with flex-2.5.4

Configure succeeds:
```
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... -lfl
```

But the build then fails:
```
yuri@xx:~/flex $ make
Making all in src
make[1]: Entering directory '/u/yuri/flex/src'
make  all-am
make[2]: Entering directory '/u/yuri/flex/src'
/bin/sh ../build-aux/ylwrap scan.l lex.yy.c scan.c -- flex
"/u/yuri/flex/src/scan.l", line 3: unrecognized '%' directive
"/u/yuri/flex/src/scan.l", line 6: bad character: #
"/u/yuri/flex/src/scan.l", line 6: unknown error processing section 1
"/u/yuri/flex/src/scan.l", line 6: unknown error processing section 1
"/u/yuri/flex/src/scan.l", line 6: bad character: "
"/u/yuri/flex/src/scan.l", line 6: unknown error processing section 1
"/u/yuri/flex/src/scan.l", line 6: bad character: .
"/u/yuri/flex/src/scan.l", line 6: unknown error processing section 1
"/u/yuri/flex/src/scan.l", line 6: bad character: "
"/u/yuri/flex/src/scan.l", line 7: bad character: }
make[2]: *** [Makefile:1433: scan.c] Error 1
make[2]: Leaving directory '/u/yuri/flex/src'
make[1]: *** [Makefile:551: all] Error 2
make[1]: Leaving directory '/u/yuri/flex/src'
make: *** [Makefile:530: all-recursive] Error 1
yuri@xx:~/flex $ flex --version
flex version 2.5.4
```

Configure should check if the pre-installed flex version is compatible and it should recommend what the minimal compatible version is.

Or, even better, do not require flex dependency at all - it isn't a good idea to depend on itself. flex can just store the C module that results in the flex run in the source tree.

**Comment by yurivict** [comment]
> Did the output you provided come from building a clone of this repo or from
> building the tarball produced by make distcheck?

It is a git clone.

**Comment by westes** [comment]
A few thoughts:

- 2.5.4 is really ancient and will not work.
- If you're building directly from git, you need a recent version of flex installed; no way around that.
- If you build the release tarball, you don't need a recent version of flex; which is how you get around the bootstrapping problem.

While I'm going to close this issue, I will open up a separate one to document clearly the need for flex in building flex. It's about half there in the INSTALL.md file, but not as clearly as it might be.
