### ISSUE TITLE
Request for latest release

### ISSUE THREAD

**Issue by 0O0o0oOoO00** [westes/flex#585]

**Comment by westes** [comment]
Flex releases are found on the releases page: https://github.com/westes/flex/releases

**Comment by westes** [comment]
Flex releases can be found on the release page: https://github.com/westes/flex/releasesFlex releases are found on the releases page: https://github.com/westes/flex/releases

**Comment by 0O0o0oOoO00** [comment]
> Flex releases can be found on the release page: https://github.com/westes/flex/releasesFlex releases are found on the releases page: https://github.com/westes/flex/releases

But in release page, it shows that the latest release is published on May 7, 2017

**Comment by westes** [comment]
That is correct.

**Comment by 0O0o0oOoO00** [comment]
ok, thak you very much
