### ISSUE TITLE
Add Scorecard Action to monitor project's security posture

### ISSUE THREAD

**Issue by pnacht** [westes/flex#589]
Hey, it's Pedro and I'm back (see #563 and #582) with another security suggestion:

I detected the issues fixed by those PRs by using [Scorecard](https://github.com/ossf/scorecard). It's a tool that scans a repository looking for settings that may make the project more vulnerable to supply-chain threats.

It is also available as the [Scorecard Action](https://github.com/ossf/scorecard-action), which continuously monitors the repository and adds security suggestions directly to the project's [Security Panel](https://github.com/westes/flex/security/code-scanning). In doing so, it can let you know if something accidentally lowers the project's security posture.

I'll send a PR along with this issue adding the Action.

Spoiler alert: flex's current score of 7.2/10 places it in the top 5% of projects important to the open-source ecosystem!

**Comment by Mightyjo** [comment]
What's the code scanning part of the Security Panel look like? I see that the action is running on the Scorecard repo itself, but I get a 404 on its [code-scanning](https://github.com/ossf/scorecard-action/security/code-scanning/) page.

**Comment by pnacht** [comment]
Yeah, that page is only visible to maintainers. But here's an example of what it'll look like with Scorecard's results:

<img width="962" alt="Screenshot 2023-09-19 at 07 07 10" src="https://github.com/westes/flex/assets/15221358/3f134bbe-5c1c-45df-9897-c9755d66558d">

Each of those items lead to a page that explains why each thing is important and how to remediate the issue. Here's an example:

![Screenshot 2023-09-09 at 13 41 06](https://github.com/westes/flex/assets/15221358/efa565ea-3845-46d7-a088-f0c62ad504de)
