### ISSUE TITLE
BSD licensing while containing GPL-2.0 header in some files 

### ISSUE THREAD

**Issue by maxhbr** [westes/flex#603]
Hey,

I browsed through your source code and saw that some files are under the GNU Library General Public License version  2 without any exception. 
https://github.com/westes/flex/blob/ee2d527aa0454df4ae8970853829e492db3b4bc7/src/gettext.h#L1-L18

But on top level and in the [README.md](https://github.com/westes/flex/blob/master/README.md) and [COPYING](https://github.com/westes/flex/blob/master/COPYING) it is just mentions BSD-2-Clause. 

It might be worth to clarify this in the readme and explain why the copyleft does not apply to the project.

**Comment by westes** [comment]
Because gettext works like that; you're welcome to submit a pull request containing the relevant explanation if you genuinely think it's needed.

**Comment by maxhbr** [comment]
Ah, it is a GNU **Library** General Public License. A fairly old LGPL-2.0. Sorry for missing the important **L**.

So, including the header files is fine. 

[the current release is under the](https://www.gnu.org/software/gettext/manual/html_node/Licenses.html) GNU **Lesser** General Public License (LGPL).
