### ISSUE TITLE
Toy lexer in Flex Simple Examples page has typo

### ISSUE THREAD

**Issue by andychu** [westes/flex#66]
On this line, the \\^ should be turned into ^, so it's negating the character class.

       "{"[\^{}}\n]*"}"     /* eat up one-line comments */

I ran this on my machine, and parsing Pascal-style comments like:

{ this is a comment }  

doesn't work without the change.  It treats the comments as code.

I didn't see the flex-www repo migrated to Github.  If I missed it, please point me there and I can send you a pull request if desired.

http://flex.sourceforge.net/manual/Simple-Examples.html#Simple-Examples

http://flex.cvs.sourceforge.net/viewvc/flex/flex-www/manual/Simple-Examples.html?revision=1.3&view=markup

**Comment by westes** [comment]
Looking at this, there is no need for the second right brace in the character class either.

**Comment by westes** [comment]
The manual posted at srouceforge is built from a(n old) copy of the flex texinfo manual. I've updated the example to address this issue and it's now pushed to master and will be included in the next release.
