### ISSUE TITLE
Macro BEGIN clashes with suggested token name

### ISSUE THREAD

**Issue by srivasta** [westes/flex#68]
Hi,

  This issue was reported by a debian user in:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=512906

According to section 1.2 in the Bison manual (v 2.3):

"A terminal symbol that stands for a particular keyword in the language 
should be named after that keyword converted to upper case."

However, flex defines a macro with the name BEGIN, which makes it 
impossible to follow this convention if the language contains the 
keyword `begin'.

I suggest renaming BEGIN to FLEX_BEGIN or YY_BEGIN.

   Thanks,

  Manoj

**Comment by brunexgeek** [comment]
Changing the name of the BEGIN macro will break compatibility (causing problems for a lot of people out there that uses flex). Also, I believe that naming the terminal symbol after the keyword doesn't means you can't use a prefix: I always use the prefix **TOK_** to avoid name collision.

**Comment by westes** [comment]
Firstly, the problem passage is in the bison manual, over which flex has no control. Secondly, the name of this macro is sufficiently long standing that, as noted, significant breakage would occur.
