### ISSUE TITLE
[advice] Add https://westes.github.io/flex/manual/ to github Edit repository details's Website

### ISSUE THREAD

**Issue by Freed-Wu** [westes/flex#680]
Like this:

![Screenshot from 2024-10-17 17-14-48](https://github.com/user-attachments/assets/90a25865-38f5-44da-966e-fa5465982c3c)

TIA!

**Comment by ethanc8** [comment]
It currently does not appear there.

![Image](https://github.com/user-attachments/assets/337810a9-21f9-4ed4-859c-aee0e4c75f1f)
