### ISSUE TITLE
compilation question when using flex and bison

### ISSUE THREAD

**Issue by zakaria-amghare** [westes/flex#687]
Created a .lex file and a .y file.

    Ran the following commands to generate the C files and compile them:

 ```
   flex test.l
    bison -d test.y
    gcc lex.yy.c test.tab.c -o test -L/usr/lib -lfl -ly
```

    However, I'm encountering the following errors during compilation:

   ```
 test.tab.c: In function ‘yyparse’:
    test.tab.c:963:16: warning: implicit declaration of function ‘yylex’ [-Wimplicit-function-declaration]
      963 |       yychar = yylex ();
          |                ^~~~~
    test.tab.c:1104:7: warning: implicit declaration of function ‘yyerror’; did you mean ‘yyerrok’? [-Wimplicit-function-declaration]
     1104 |       yyerror (YY_("syntax error"));
          |       ^~~~~~~
          |       yyerrok
    /usr/bin/ld: cannot find -ly: No such file or directory
    collect2: error: ld returned 1 exit status

```
    **Steps I've Tried:**

        Verified that Flex and Bison are installed.

        Checked GCC installation and libraries.
    My Environment:

        **Flex version: flex 2.6.4

        Bison version: bison (GNU Bison) 3.8.2

        GCC version: gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0**

    Does anyone know what might be causing these issues? Any help would be greatly appreciated!

    **Thanks in advance!**
**may god bless you**

**Comment by Mightyjo** [comment]
I think you just need to add the --bison-bridge option to your flex command
line. Bison expects a slightly different prototype for yylex.

**Comment by zakaria-amghare** [comment]
zakaria@zakaria-HP-Laptop-15-da0xxx:~/Desktop/compil$ flex lexical.l  --bison-bridge
flex: can't open --bison-bridge

**Comment by zakaria-amghare** [comment]
What can I do 
Well if you have time and it does not bother you  can we do a meet to fix the issue 
Sorry if this is rude in your culture 
But I am very pressed

**Comment by Mightyjo** [comment]
Try 'flex --bison-bridge lexical.l'

**Comment by zakaria-amghare** [comment]
i did and it did work but when treid to make the parser look what happend 
```
zakaria@zakaria-HP-Laptop-15-da0xxx:~/Desktop/compil$ flex --bison-bridge lexical.l 
zakaria@zakaria-HP-Laptop-15-da0xxx:~/Desktop/compil$ gcc y.tab.c lex.yy.c -o parser
cc1: fatal error: y.tab.c: No such file or directory
compilation terminated.
lexical.l:2:14: fatal error: y.tab.h: No such file or directory
    2 |     #include "y.tab.h"
      |              ^~~~~~~~~
compilation terminated.
zakaria@zakaria-HP-Laptop-15-da0xxx:~/Desktop/compil$ bison -d synt.y
zakaria@zakaria-HP-Laptop-15-da0xxx:~/Desktop/compil$ flex --bison-bridge lexical.l 
zakaria@zakaria-HP-Laptop-15-da0xxx:~/Desktop/compil$ gcc y.tab.c lex.yy.c -o parser
cc1: fatal error: y.tab.c: No such file or directory
compilation terminated.
lexical.l:2:14: fatal error: y.tab.h: No such file or directory
    2 |     #include "y.tab.h"
      |              ^~~~~~~~~
compilation terminated.
```then i removed the #include "y.tab.h" from lixical.l
and this happend
```
zakaria@zakaria-HP-Laptop-15-da0xxx:~/Desktop/compil$ bison -d synt.y
zakaria@zakaria-HP-Laptop-15-da0xxx:~/Desktop/compil$ flex --bison-bridge lexical.l 
zakaria@zakaria-HP-Laptop-15-da0xxx:~/Desktop/compil$ gcc y.tab.c lex.yy.c -o parser
cc1: fatal error: y.tab.c: No such file or directory
compilation terminated.
```

**Comment by Mightyjo** [comment]
Looks like bison failed to produce its output. Did it produce errors?

**Comment by zakaria-amghare** [comment]
> Looks like bison failed to produce its output. Did it produce errors

No it didn't produce errors 
And it produced files 
`Synt.tab.h` 
And 
`Synt.tab.c`

**Not** `y.tab.h`

**Comment by zakaria-amghare** [comment]
I think the problem is somehow related to librerys
I have sow someone with different sut up`(windows blocknote)` he coppied evry file from  librerys from flex and bison putted them codebloks librerys

**Comment by Mightyjo** [comment]
Okay, you're almost there. Since bison produced files named Synt.tab.h and
.c, substitute those names wherever you find y.tab.h and .c right now.

**Comment by zakaria-amghare** [comment]
Sorry to insist, but can we do a **meet**
As it is showing me an error 
And trying to fix bugs only via messages would take so much time. I really appreciate you thank you

**Comment by Mightyjo** [comment]
Sorry, I can't

**Comment by zakaria-amghare** [comment]
it s ok 
the issue now is 
`zakaria@zakaria-HP-Laptop-15-da0xxx:~/Desktop/compil$ gcc -ly -lfl  y.tab.c lex.yy.c -o parser
y.tab.c:91:10: fatal error: synt.tab.h: No such file or directory
   91 | #include "synt.tab.h"
      |          ^~~~~~~~~~~~
compilation terminated.
lexical.l:3:14: fatal error: synt.tab.h: No such file or directory
    3 |     #include "synt.tab.h"
      |              ^~~~~~~~~~~~
compilation terminated.
zakaria@zakaria-HP-Laptop-15-da0xxx:~/Desktop/compil$ gcc   y.tab.c lex.yy.c -o parser
y.tab.c:91:10: fatal error: synt.tab.h: No such file or directory
   91 | #include "synt.tab.h"
      |          ^~~~~~~~~~~~
compilation terminated.
lexical.l:3:14: fatal error: synt.tab.h: No such file or directory
    3 |     #include "synt.tab.h"
      |              ^~~~~~~~~~~~
compilation terminated.
zakaria@zakaria-HP-Laptop-15-da0xxx:~/Desktop/compil$ gcc   y.tab.c lex.yy.c -o parser
y.tab.c:91:10: fatal error: synt.tab.h: No such file or directory
   91 | #include "synt.tab.h"
      |          ^~~~~~~~~~~~
compilation terminated.
lexical.l:3:14: fatal error: synt.tab.h: No such file or directory
    3 |     int nb_l=1;
      |              ^~          
compilation terminated.
zakaria@zakaria-HP-Laptop-15-da0xxx:~/Desktop/compil$ bison -d synt.y
zakaria@zakaria-HP-Laptop-15-da0xxx:~/Desktop/compil$ flex lexical.l --bison-bridge
flex: can't open --bison-bridge
zakaria@zakaria-HP-Laptop-15-da0xxx:~/Desktop/compil$ flex --bison-bridge lexical.l 
zakaria@zakaria-HP-Laptop-15-da0xxx:~/Desktop/compil$ gcc   y.tab.c lex.yy.c -o parser
y.tab.c: In function ‘yyparse’:
y.tab.c:955:16: warning: implicit declaration of function ‘yylex’ [-Wimplicit-function-declaration]
  955 |       yychar = yylex ();
      |                ^~~~~
synt.y:5:8: warning: implicit declaration of function ‘printf’ [-Wimplicit-function-declaration]
    5 | S:imp {printf("pgm correct");}
      |        ^~~~~~
synt.y:5:1: note: include ‘<stdio.h>’ or provide a declaration of ‘printf’
    4 | %%
  +++ |+#include <stdio.h>
    5 | S:imp {printf("pgm correct");}
synt.y:5:8: warning: incompatible implicit declaration of built-in function ‘printf’ [-Wbuiltin-declaration-mismatch]
    5 | S:imp {printf("pgm correct");}
      |        ^~~~~~
synt.y:5:8: note: include ‘<stdio.h>’ or provide a declaration of ‘printf’
synt.tab.c:1096:7: warning: implicit declaration of function ‘yyerror’; did you mean ‘yyerrok’? [-Wimplicit-function-declaration]
 1096 |       yyerror (YY_("syntax error"));
      |       ^~~~~~~
      |       yyerrok
synt.y: At top level:
synt.y:8:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
    8 | main()
      | ^~~~
synt.y:10:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
   10 | yywrap(){}
      | ^~~~~~
/usr/bin/ld: /tmp/cc3Bw7Pz.o: in function `yyparse':
y.tab.c:(.text+0x65f): undefined reference to `yyerror'
/usr/bin/ld: y.tab.c:(.text+0x7f6): undefined reference to `yyerror'
collect2: error: ld returned 1 exit status`

**Comment by zakaria-amghare** [comment]
I did, and it didn't work heres what I will do 
I will try to build a compiler in java 
So, do you have any idea about how to do the synaxical analysis in java 
(And any resources would be so sk helpful )
Thanks for your time 
May God guide us and bless us

**Comment by Mightyjo** [comment]
Sorry I couldn't help more. For Java, look at ANTLR.

**Comment by zakaria-amghare** [comment]
What is it

**Comment by Mightyjo** [comment]
It's a scanner and parser generator that targets Java

**Comment by zakaria-amghare** [comment]
Thank you soooo muchhhh 
You are the best 
I will pray for you 
Your kindness touched me
I feel like I took a lot from your time
