### ISSUE TITLE
the path to m4

### ISSUE THREAD

**Issue by westes** [westes/flex#73]
Add an option, say, --with-m4 to configure that allows a user to specify which m4 flex should use. This option, when passed, should cause a symbol to be set in config.h. src/main.c should use that symbol to call m4. If that option is not passed, then configure should do its best to find a suitable m4 and set the config.h symbol as previously described.

In particular, this effects Solaris, where /usr/bin/m4 is not suitable for use with flex and where GNU m4 is not in a standard place.

**Comment by Explorer09** [comment]
Um... what is this issue report about? Isn't `./configure M4=/path_to_your_gnu_m4/m4` already sufficient?

**Comment by westes** [comment]
No, this is about the path to the runtime m4.

On Monday,  2 January 2017, 11:28 pm -0800, "Kang-Che Sung (宋岡哲)" <notifications@github.com> wrote:

> Um... what is this issue report about? Isn't `./configure M4=/path_to_your_gnu_m4/m4` already sufficient?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/73#issuecomment-270062236

-- 
Will Estes
westes575@gmail.com

**Comment by Explorer09** [comment]
I still don't get it. The current config.h already `#define`'s the M4 symbol (1). That is what will be compiled into flex code. And flex honors the M4 environment variable if set (2). What else do we lack then?

(1): In configure.ac, AC_DEFINE_UNQUOTED([M4], ...)
(2): In src/main.c, the getenv("M4") part of code.

**Comment by westes** [comment]
The compile time and runtime m4 paths are not necessarily the same. That's the issue. Yes, one work around is  to use the environment variable.

There might also be some stuff about using a better check for which m4 we're using. Not all m4 are useable from flex's point of view.

There's a third issue that we probably want to internalize macro processing anyway since we don't use a lot of m4 features. (But that's covered in another issue.)

On Tuesday,  3 January 2017,  5:42 am -0800, "Kang-Che Sung (宋岡哲)" <notifications@github.com> wrote:

> I still don't get it. The current config.h already `#define`'s the M4 symbol (1). That is what will be compiled into flex code. And flex honors the M4 environment variable if set (2). What else do we lack then?
> 
> (1): In configure.ac, AC_DEFINE_UNQUOTED([M4], ...)
> (2): In src/main.c, the getenv("M4") part of code.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/73#issuecomment-270116456

-- 
Will Estes
westes575@gmail.com

**Comment by Explorer09** [comment]
@westes No, I don't think we will need M4 at compile time -- as long as user builds it from a release tarball. The M4 variable in configure is intended for (hard-coded default path in) runtime, which is what you will want already.
In case we need a compile-time M4, that's easy to workaround, something like this:

```
$ ./configure --build=x86_64-linux-gnu --host=x86_64-solaris2 --disable-bootstrap M4=/usr/local/bin/gnum4 # Runtime gnum4 for Solaris here
$ make M4=/usr/bin/m4 # My build time m4 here
```

And in case that we need a build time M4 (e.g. for bootstrap), that would be M4_FOR_BUILD, not the M4 variable we specify in configure.

**Comment by westes** [comment]
No, I mean like...

Maybe at compile time, it's /usr/bin/m4 but then you try and install that package on a machine where it's /usr/local/bin/m4 or ... /opt/xyzzy/bin/m4 or something like that.

On Tuesday,  3 January 2017,  5:56 am -0800, "Kang-Che Sung (宋岡哲)" <notifications@github.com> wrote:

> @westes No, I don't think we will need M4 at compile time -- as long as user builds it from a release tarball. The M4 variable in configure is intended for (hard-coded default path in) runtime, which is what you will want already.
> In case we need a compile-time M4, that's easy to workaround, something like this:
> 
> ```
> $ ./configure --build=x86_64-linux-gnu --host=x86_64-solaris2 --disable-bootstrap M4=/usr/local/bin/gnum4 # Runtime gnum4 for Solaris here
> $ make M4=/usr/bin/m4 # My build time m4 here
> ```
> 
> And in case that we need a build time M4 (e.g. for bootstrap), that would be M4_FOR_BUILD, not the M4 variable we specify in configure.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/issues/73#issuecomment-270119096

-- 
Will Estes
westes575@gmail.com

**Comment by Explorer09** [comment]
That's exactly the problem I was addressing.
It won't be '--with-m4' option, but what we need are (a) M4_FOR_BUILD variable, and (b) making it a warning and not an error for configure's 'm4 -P' check if we are cross-compiling.

**Comment by westes** [comment]
Looking at this, having a configure time path for m4 isn't helpful.
