### ISSUE TITLE
M4 macro expanded in source string literal

### ISSUE THREAD

**Issue by DemiMarie** [westes/flex#79]
The following simple lexer produces the wrong output:

    %{
    #include <stdio.h>
    %}
    %%
    (.|\n) { puts("YY_G(alpha)"); }
    %%

When run, it produces `(alpha)` for every input character, instead of `YY_G(alpha)`.

This is due to M4 macro expansion and is a bug.  Namespaces are not an issue here, since `YY_G` occurs in a string literal.

This can be fixed by quoting all user-supplied input.

**Comment by westes** [comment]
This is fixed as per the pr's you've submitted.
