### ISSUE TITLE
makeinfo not checked by configure but requested for documentation

### ISSUE THREAD

**Issue by EricDeveaud** [westes/flex#93]
Hello, 

by default makeinfo is needed for documentation generation, but not checked by configure.

furthermore no make info ends p with the following error
'''
/local/gensoft2/src/flex/flex-2.6.1/build-aux/missing: line 81: makeinfo: command not found
WARNING: 'makeinfo' is missing on your system.
         You should only need it if you modified a '.texi' file, or
         any other file indirectly affecting the aspect of the manual.
         You might want to install the Texinfo package:
         <http://www.gnu.org/software/texinfo/>
         The spurious makeinfo call might also be the consequence of
         using a buggy 'make' (AIX, DU, IRIX), in which case you might
         want to install GNU make:
         <http://www.gnu.org/software/make/>
'''

even if

'''
c6builder:flex/flex-2.6.1 > make --version 
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-redhat-linux-gnu
'''

regards

    Eric

**Comment by westes** [comment]
How did you invoke make to get this error?

Did you start from the 2.6.1 tar ball?

Thanks!

**Comment by EricDeveaud** [comment]
'''
wget -qO- https://github.com/westes/flex/archive/v2.6.1.tar.gz | tar xz --strip-components 1
./autogen.sh
./configure --prefix=/local/gensoft2/exe/flex/2.6.1 --htmldir=/local/gensoft2/exe/flex/2.6.1/html
make 
'''

using 
m4/1.4.17 autoconf/2.69 automake/1.15 libtool/2.4.6 gettext/0.19.8.1

best

    Eric

**Comment by westes** [comment]
Would you remove the autogen.sh, please. That's likely rewriting things and you don't need it if you start from the archive. (You need it when working directly in the git tree.)

-- That's the point of building the tar archive, to put in all the things that aren't just "compile this".

If you're just building and not modifying things, then the usual configure / make should do what you want.

**Comment by westes** [comment]
Oh, you're grabbing the tag from the tree. You want this instead:

https://github.com/westes/flex/releases/flex-2.6.1.tar.gz

(or xz if you like)

That's the thing that has the files you want -- so the makeinfo stuff is already built.

It's expected that if you're working from the git tree that you have all the tools in the tool chain.

**Comment by EricDeveaud** [comment]
OK my bad.

**Comment by westes** [comment]
That's already noted in #49.
