### ISSUE TITLE
Very old releases missing?

### ISSUE THREAD

**Issue by ncafferkey** [westes/flex#94]
Have some very old releases been deleted recently? My project still relies on 2.5.4a. Is there any chance they could be restored if the effort involved is small? I think it would be good to have them somewhere on the net for historical purposes anyway.

**Comment by westes** [comment]
If you have a scanner that works under 2.5.4a and not under the current flex code, then I'm happy to look at it.

Beyond that, older releases of flex have been superceded by newer ones. And any report of a scanner under 2.5.4a that doesn't possess some desired feature would be checked against the current codebase.

Why are you still using 2.5.4a?

**Comment by ncafferkey** [comment]
We use it under a non-Linux/Unix OS (AROS) and patch it to work in that environment (admittedly the patch is trivial, at least for this version). Manpower is limited, and we don't have time at the moment to test that newer versions work in our OS. I don't expect any support for such an old version, but I was just wondering if the old versions could be retained.

**Comment by westes** [comment]
Could you contact me off this issue and tell me about the patch/es you need to get flex working?

Depending on what it is, it might make sense to include it in flex.

Also, could you link me to the project?

**Comment by ncafferkey** [comment]
Do you mean you want me to get in touch off-thread? I don't see a way to send you a PM or email here. But the issue can be described briefly.

The patch is here (it only adds two lines):
https://trac.aros.org/trac/browser/AROS/trunk/contrib/gnu/flex/flex-2.5.4a-aros.diff

The project homepage is at http://www.aros.org/

**Comment by westes** [comment]
Yeah it's not obvious how to reach out to someone. The links help.

Thanks.

**Comment by westes** [comment]
For the record, that patch would not be needed in the current codebase -- the flex #includes are unified / modernized / etc.

**Comment by westes** [comment]
I'm happy to put in any portability changes that are needed for flex to work on this platform, particularly if you point me at an instance I can ssh into and build/test the code.

Beyond that, I think the best thing to do is to close this issue since I see the AROS folks are giong to find another source to link for the old version.
